// AUTO-GENERATED by lambda/gen_coeff_vocab.py from lambda program metadata — do not edit
// Registry transforms, structural chips, and profile metadata shared with the frontend.
window._coeffRegistryVocab = {
  "aliasToCanonical": {
    "scale100": "linear",
    "exp_affine": "exp",
    "pow_affine": "pow",
    "power_series": "power"
  },
  "sourceAliasByName": {
    "exp": "exp_affine",
    "pow": "pow_affine",
    "power": "power_series"
  },
  "chipNameByRegistryName": {
    "exp": "exp_affine",
    "power": "power_series"
  },
  "ctCatalog": {
    "rev": {
      "category": "structural",
      "desc": "Reverse the coefficient vector end to end (cf[k] <-> cf[n-1-k]): the reversed polynomial's nonzero roots are the reciprocals of the originals.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "conj": {
      "category": "structural",
      "desc": "Conjugate every coefficient (negate imaginary parts): roots reflect across the real axis.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "normalize": {
      "category": "structural",
      "desc": "Divide every coefficient by the leading one, making the polynomial monic; a near-zero leading coefficient (|cf[0]|^2 < 1e-30) leaves the vector unchanged.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "deriv": {
      "category": "structural",
      "desc": "Formal derivative: multiply each cf[k] by its power (n-1-k), drop the constant term; length shrinks by one.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "safe": {
      "category": "structural",
      "desc": "Replace any non-finite (inf/NaN) component with 0; finite values pass through untouched.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "negate_odd": {
      "category": "structural",
      "desc": "Negate odd-indexed coefficients \u2014 the polynomial evaluated at -z (up to overall sign), so roots flip through the origin.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "max2one": {
      "category": "structural",
      "desc": "Find the largest-magnitude coefficient and overwrite it with exactly 1; every other coefficient is untouched.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "sort_mod_keep_angle": {
      "category": "accumulation",
      "desc": "Sort the moduli ascending and hand them back out by position: cf[k] keeps its own angle but takes the k-th smallest modulus.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "sort_angle_keep_mod": {
      "category": "accumulation",
      "desc": "Sort the angles ascending and hand them back out by position: cf[k] keeps its own modulus but takes the k-th smallest angle.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "sort_abs": {
      "category": "accumulation",
      "desc": "Reorder whole coefficients by ascending magnitude (values unchanged, positions sorted).",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "cumsum": {
      "category": "accumulation",
      "desc": "Running complex sum: cf[k] becomes cf[0] + ... + cf[k].",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "cummax": {
      "category": "accumulation",
      "desc": "Running magnitude peak: cf[k] becomes the largest-magnitude coefficient seen so far (the winning complex value is carried forward).",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "sort_cumsum": {
      "category": "accumulation",
      "desc": "Rank positions by the running-sum magnitude |cf[0]+...+cf[k]| of the original order, then reorder the coefficients by that ranking.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "linear": {
      "category": "elementwise",
      "desc": "Affine map on every coefficient: z -> z*field1 + field2 (complex multiply-add); non-finite results become 0. scale100-compatible.",
      "label": "linear",
      "params": [
        {
          "ph": "field1",
          "label": "field1",
          "def": "100",
          "complex": true,
          "scalarExpr": "complex",
          "complexWide": true,
          "title": "Complex multiplier in z*[field1]+[field2]. {SCALAR_EXPR_HELP}"
        },
        {
          "ph": "field2",
          "label": "field2",
          "def": "0",
          "complex": true,
          "scalarExpr": "complex",
          "complexWide": true,
          "title": "Complex offset in z*[field1]+[field2]. {SCALAR_EXPR_HELP}"
        },
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "swirler": {
      "category": "elementwise",
      "desc": "Multiply each coefficient z by exp(a^4 + b^4 + i*2*pi*a*b) where a = frac(|100z|) and b = frac(|10z|): a modulus-keyed spiral, so nearby magnitudes land at very different phases.",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "exp": {
      "category": "elementwise",
      "desc": "Map each coefficient z to exp(z*field1 + field2) (complex exponential of an affine map); non-finite results become 0.",
      "label": "exp",
      "params": [
        {
          "ph": "field1",
          "label": "field1",
          "def": "1",
          "scalarExpr": "real",
          "exprWide": true,
          "title": "Real multiplier component. {SCALAR_EXPR_HELP}"
        },
        {
          "ph": "field2",
          "label": "field2",
          "def": "0",
          "scalarExpr": "real",
          "exprWide": true,
          "title": "Imaginary multiplier component. {SCALAR_EXPR_HELP}"
        },
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "cos": {
      "category": "elementwise",
      "desc": "Complex cosine of each coefficient: z -> cos(z); non-finite results become 0.",
      "label": "cos",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "sin": {
      "category": "elementwise",
      "desc": "Complex sine of each coefficient: z -> sin(z); non-finite results become 0.",
      "label": "sin",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "tan": {
      "category": "elementwise",
      "desc": "Complex tangent of each coefficient: z -> tan(z); values at poles and non-finite results become 0.",
      "label": "tan",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "cosh": {
      "category": "elementwise",
      "desc": "Complex hyperbolic cosine of each coefficient: z -> cosh(z); non-finite results become 0.",
      "label": "cosh",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "sinh": {
      "category": "elementwise",
      "desc": "Complex hyperbolic sine of each coefficient: z -> sinh(z); non-finite results become 0.",
      "label": "sinh",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "tanh": {
      "category": "elementwise",
      "desc": "Complex hyperbolic tangent of each coefficient: z -> tanh(z); values at poles and non-finite results become 0.",
      "label": "tanh",
      "params": [
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "round": {
      "category": "elementwise",
      "desc": "Scale then snap to the integer grid: z -> round(Re(z*multiplier)) + i*round(Im(z*multiplier)); non-finite results become 0.",
      "label": "round",
      "params": [
        {
          "ph": "multiplier",
          "label": "mult",
          "def": "1",
          "complex": true,
          "scalarExpr": "complex",
          "complexWide": true,
          "title": "Complex multiplier in round(z*multiplier). {SCALAR_EXPR_HELP}"
        },
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "pow": {
      "category": "elementwise",
      "desc": "Complex power of an affine map: z -> (z*multiplier)^exponent (principal branch); |z*multiplier|^2 < 1e-60 or non-finite results become 0.",
      "label": "pow",
      "params": [
        {
          "ph": "field1",
          "label": "field1",
          "def": "1",
          "complex": true,
          "scalarExpr": "complex",
          "complexWide": true,
          "title": "Complex multiplier in pow(z*field1, field2)."
        },
        {
          "ph": "field2",
          "label": "field2",
          "def": "1",
          "complex": true,
          "scalarExpr": "complex",
          "complexWide": true,
          "title": "Complex exponent in pow(z*field1, field2)."
        },
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "power": {
      "category": "elementwise",
      "desc": "Index-weighted geometric series: cf[i] at position i becomes (i+1) * (1 + z + z^2 + ... + z^k) evaluated at z = cf[i]; non-finite becomes 0.",
      "label": "p",
      "params": [
        {
          "ph": "k",
          "def": "8",
          "title": "Series order: cf[i] becomes (i+1)*(1 + z + ... + z^k)."
        },
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "invpower": {
      "category": "elementwise",
      "desc": "Bounded reciprocal of the geometric series: with s = 1 + z + ... + z^k per coefficient, cf[i] becomes 1/s when |s| > 1 and exactly 1 otherwise.",
      "label": "invp",
      "params": [
        {
          "ph": "k",
          "def": "4",
          "title": "Series order in s = 1 + z + ... + z^k; result is 1/s when |s| > 1, else 1."
        },
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "roots_cm": {
      "category": "roots",
      "desc": "Feed back the roots as coefficients: solve the current vector with the companion-matrix eigensolver and write its roots into the coefficient slots, zero-padding one slot (hi = leading, lo = constant) to keep the length.",
      "params": [
        {
          "ph": "hi|lo",
          "def": "hi",
          "title": "Which slot takes the zero pad: hi = leading (highest power), lo = constant term.",
          "choices": [
            "hi",
            "lo"
          ]
        },
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    },
    "roots": {
      "category": "roots",
      "desc": "Feed back the roots as coefficients: run k Aberth-Ehrlich iterations (leading/trailing zeros trimmed first) and write the \u2014 possibly unconverged for small k \u2014 roots into the coefficient slots, zero-padded hi or lo.",
      "label": "roots",
      "params": [
        {
          "ph": "k",
          "def": "8",
          "title": "Aberth-Ehrlich iteration count; small values leave roots deliberately unconverged."
        },
        {
          "ph": "hi|lo",
          "def": "hi",
          "title": "Which slot takes the zero pad: hi = leading (highest power), lo = constant term.",
          "choices": [
            "hi",
            "lo"
          ]
        },
        {
          "kind": "andy",
          "ph": "andy",
          "label": "andy",
          "def": "0",
          "scalarExpr": "real",
          "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
        }
      ]
    }
  },
  "categoryMeta": {
    "structural": {
      "title": "Structural",
      "help": "reorder, normalize, sanitize, or resize the coefficient vector"
    },
    "accumulation": {
      "title": "Ordering + accumulation",
      "help": "sort or accumulate coefficients across the vector"
    },
    "elementwise": {
      "title": "Elementwise functions",
      "help": "apply a complex function to each coefficient independently"
    },
    "roots": {
      "title": "Root-derived",
      "help": "replace coefficients with roots computed from the current coefficient vector"
    }
  },
  "programParamDefs": {
    "exp": [
      {
        "ph": "field1",
        "label": "field1",
        "def": "1",
        "complex": true,
        "scalarExpr": "complex",
        "complexWide": true,
        "title": "Complex multiplier in exp(z*field1+field2). {SCALAR_EXPR_HELP}"
      },
      {
        "ph": "field2",
        "label": "field2",
        "def": "0",
        "complex": true,
        "scalarExpr": "complex",
        "complexWide": true,
        "title": "Complex offset in exp(z*field1+field2). {SCALAR_EXPR_HELP}"
      },
      {
        "kind": "andy",
        "ph": "andy",
        "label": "andy",
        "def": "0",
        "scalarExpr": "real",
        "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
      }
    ],
    "round": [
      {
        "ph": "multiplier",
        "label": "mult",
        "def": "1",
        "complex": true,
        "scalarExpr": "complex",
        "complexWide": true,
        "title": "Complex multiplier in round(z*multiplier). {SCALAR_EXPR_HELP}"
      },
      {
        "kind": "andy",
        "ph": "andy",
        "label": "andy",
        "def": "0",
        "scalarExpr": "real",
        "title": "Blend amount in [0,1]. {SCALAR_EXPR_HELP}"
      }
    ]
  },
  "structuralChips": {
    "version": 1,
    "program_kind": "coeff_program",
    "notes": [
      "Structural Coeff Program chip vocabulary. Registry transforms live in coeff_legacy_registry.json.",
      "Selector values are owned by program_profiles.json; chips reference selector slots by name."
    ],
    "selector_slots": {
      "src": "coeff.src",
      "tgt": "coeff.tgt",
      "push_src": "coeff.push_src",
      "set_tgt": "coeff.set_tgt",
      "vector_src": "coeff.vector_src",
      "typed_vector_src": "coeff.typed_vector_src"
    },
    "chips": [
      {
        "name": "push_const",
        "op_symbol": "COEFF_OP_CONST",
        "op": 1,
        "aliases": [
          "const",
          "push_vec"
        ],
        "source_aliases": [
          "fill"
        ],
        "args": [
          {
            "name": "length",
            "type": "length_expr"
          },
          {
            "name": "value",
            "type": "complex_expr"
          }
        ]
      },
      {
        "name": "push",
        "op_symbol": "COEFF_OP_PUSH",
        "op": 2,
        "selector_slots": {
          "src": "push_src"
        }
      },
      {
        "name": "emit",
        "op_symbol": "COEFF_OP_EMIT",
        "op": 3
      },
      {
        "name": "duplicate",
        "op_symbol": "COEFF_OP_DUPLICATE",
        "op": 4,
        "aliases": [
          "dup"
        ]
      },
      {
        "name": "swap",
        "op_symbol": "COEFF_OP_SWAP",
        "op": 5
      },
      {
        "name": "pop",
        "op_symbol": "COEFF_OP_POP",
        "op": 6,
        "source_aliases": [
          "drop"
        ]
      },
      {
        "name": "flush",
        "op_symbol": "COEFF_OP_FLUSH",
        "op": 7
      },
      {
        "name": "blend",
        "op_symbol": "COEFF_OP_BLEND",
        "op": 8,
        "args": [
          {
            "name": "t",
            "type": "real_expr"
          }
        ]
      },
      {
        "name": "legacy",
        "op_symbol": "COEFF_OP_LEGACY",
        "op": 9,
        "args": [
          {
            "name": "name",
            "type": "registry_transform"
          },
          {
            "name": "src",
            "type": "selector",
            "slot": "src"
          },
          {
            "name": "tgt",
            "type": "selector",
            "slot": "tgt"
          }
        ]
      },
      {
        "name": "poke_poly",
        "op_symbol": "COEFF_OP_POKE_POLY",
        "op": 10,
        "args": [
          {
            "name": "index",
            "type": "int_literal"
          },
          {
            "name": "value",
            "type": "complex_expr"
          }
        ]
      },
      {
        "name": "poke_tos",
        "op_symbol": "COEFF_OP_POKE_TOS",
        "op": 11,
        "args": [
          {
            "name": "index",
            "type": "int_literal"
          },
          {
            "name": "value",
            "type": "complex_expr"
          }
        ]
      },
      {
        "name": "vector_binary",
        "op_symbol": "COEFF_OP_VECTOR_BINARY",
        "op": 12,
        "family": true,
        "selector_slots": {
          "tgt": "tgt",
          "src1": "vector_src",
          "src2": "vector_src"
        },
        "sub_ops": [
          {
            "name": "add",
            "symbol": "COEFF_VEC_ADD",
            "value": 1
          },
          {
            "name": "subtract",
            "symbol": "COEFF_VEC_SUBTRACT",
            "value": 2,
            "source_aliases": [
              "sub"
            ]
          },
          {
            "name": "multiply",
            "symbol": "COEFF_VEC_MULTIPLY",
            "value": 3,
            "source_aliases": [
              "mul"
            ]
          },
          {
            "name": "divide",
            "symbol": "COEFF_VEC_DIVIDE",
            "value": 4,
            "source_aliases": [
              "div"
            ]
          },
          {
            "name": "power",
            "symbol": "COEFF_VEC_POWER",
            "value": 5,
            "source_aliases": [
              "pow"
            ]
          },
          {
            "name": "ge",
            "symbol": "COEFF_VEC_GE",
            "value": 6
          },
          {
            "name": "gt",
            "symbol": "COEFF_VEC_GT",
            "value": 7
          },
          {
            "name": "le",
            "symbol": "COEFF_VEC_LE",
            "value": 8
          },
          {
            "name": "lt",
            "symbol": "COEFF_VEC_LT",
            "value": 9
          },
          {
            "name": "eq",
            "symbol": "COEFF_VEC_EQ",
            "value": 10
          },
          {
            "name": "rem",
            "symbol": "COEFF_VEC_REM",
            "value": 11
          }
        ]
      },
      {
        "name": "vector_unary",
        "op_symbol": "COEFF_OP_VECTOR_UNARY",
        "op": 13,
        "family": true,
        "selector_slots": {
          "tgt": "tgt",
          "src": "vector_src"
        },
        "sub_ops": [
          {
            "name": "angle",
            "symbol": "COEFF_VEC_ANGLE",
            "value": 1
          },
          {
            "name": "mod",
            "symbol": "COEFF_VEC_MOD",
            "value": 2,
            "canonical": "abs"
          },
          {
            "name": "abs",
            "symbol": "COEFF_VEC_ABS",
            "value": 3
          },
          {
            "name": "neg",
            "symbol": "COEFF_VEC_NEG",
            "value": 4
          },
          {
            "name": "conj",
            "symbol": "COEFF_VEC_CONJ",
            "value": 5
          },
          {
            "name": "sqrt",
            "symbol": "COEFF_VEC_SQRT",
            "value": 6
          },
          {
            "name": "log",
            "symbol": "COEFF_VEC_LOG",
            "value": 7
          },
          {
            "name": "real",
            "symbol": "COEFF_VEC_REAL",
            "value": 8
          },
          {
            "name": "imag",
            "symbol": "COEFF_VEC_IMAG",
            "value": 9
          },
          {
            "name": "exp",
            "symbol": "COEFF_VEC_EXP",
            "value": 10
          },
          {
            "name": "sin",
            "symbol": "COEFF_VEC_SIN",
            "value": 11
          },
          {
            "name": "cos",
            "symbol": "COEFF_VEC_COS",
            "value": 12
          },
          {
            "name": "tan",
            "symbol": "COEFF_VEC_TAN",
            "value": 13
          },
          {
            "name": "sinh",
            "symbol": "COEFF_VEC_SINH",
            "value": 14
          },
          {
            "name": "cosh",
            "symbol": "COEFF_VEC_COSH",
            "value": 15
          },
          {
            "name": "tanh",
            "symbol": "COEFF_VEC_TANH",
            "value": 16
          }
        ]
      },
      {
        "name": "vector_roll",
        "op_symbol": "COEFF_OP_VECTOR_ROLL",
        "op": 14,
        "family": true,
        "selector_slots": {
          "tgt": "tgt",
          "src": "vector_src"
        },
        "sub_ops": [
          {
            "name": "roll",
            "symbol": "COEFF_VEC_ROLL_LEFT",
            "value": 1
          },
          {
            "name": "rolr",
            "symbol": "COEFF_VEC_ROLL_RIGHT",
            "value": 2
          }
        ]
      },
      {
        "name": "argsort",
        "op_symbol": "COEFF_OP_VECTOR_ARGSORT",
        "op": 15,
        "selector_slots": {
          "tgt": "tgt",
          "src1": "vector_src",
          "src2": "vector_src"
        }
      },
      {
        "name": "littlewood",
        "op_symbol": "COEFF_OP_LITTLEWOOD",
        "op": 16,
        "selector_slots": {
          "tgt": "tgt"
        },
        "args": [
          {
            "name": "value1",
            "type": "complex_expr"
          },
          {
            "name": "value2",
            "type": "complex_expr"
          },
          {
            "name": "andy",
            "type": "real_expr"
          }
        ]
      },
      {
        "name": "push_linspace",
        "op_symbol": "COEFF_OP_LINSPACE",
        "op": 17,
        "source_aliases": [
          "linspace"
        ],
        "args": [
          {
            "name": "length_or_start",
            "type": "real_expr"
          }
        ]
      },
      {
        "name": "push_range",
        "op_symbol": "COEFF_OP_RANGE",
        "op": 18,
        "source_aliases": [
          "arange",
          "range"
        ],
        "args": [
          {
            "name": "length_or_start",
            "type": "real_expr"
          }
        ]
      },
      {
        "name": "set",
        "op_symbol": "COEFF_OP_SET",
        "op": 19,
        "selector_slots": {
          "tgt": "set_tgt",
          "src": "src"
        }
      },
      {
        "name": "affine",
        "op_symbol": "COEFF_OP_AFFINE",
        "op": 20,
        "aliases": [
          "linear"
        ],
        "source_aliases": [
          "scale",
          "shift"
        ],
        "selector_slots": {
          "tgt": "tgt",
          "src": "src"
        },
        "args": [
          {
            "name": "multiplier",
            "type": "complex_expr"
          },
          {
            "name": "offset",
            "type": "complex_expr"
          }
        ]
      },
      {
        "name": "_typed_push_scalar",
        "op_symbol": "COEFF_OP_TYPED_PUSH_SCALAR",
        "op": 21,
        "aliases": [
          "push_scalar"
        ],
        "internal": true,
        "args": [
          {
            "name": "value",
            "type": "complex_expr"
          }
        ]
      },
      {
        "name": "_typed_push_vector",
        "op_symbol": "COEFF_OP_TYPED_PUSH_VECTOR",
        "op": 22,
        "internal": true,
        "selector_slots": {
          "src": "typed_vector_src"
        }
      },
      {
        "name": "_typed_binary",
        "op_symbol": "COEFF_OP_TYPED_BINARY",
        "op": 23,
        "internal": true,
        "sub_ops_from": "vector_binary"
      },
      {
        "name": "_typed_unary",
        "op_symbol": "COEFF_OP_TYPED_UNARY",
        "op": 24,
        "internal": true,
        "sub_ops_from": "vector_unary"
      },
      {
        "name": "_typed_get_scalar",
        "op_symbol": "COEFF_OP_TYPED_GET_SCALAR",
        "op": 25,
        "internal": true
      },
      {
        "name": "_typed_set_poly",
        "op_symbol": "COEFF_OP_TYPED_SET_POLY",
        "op": 26,
        "internal": true
      },
      {
        "name": "_typed_poke_poly",
        "op_symbol": "COEFF_OP_TYPED_POKE_POLY",
        "op": 27,
        "internal": true
      },
      {
        "name": "_typed_fill",
        "op_symbol": "COEFF_OP_TYPED_FILL",
        "op": 28,
        "internal": true
      },
      {
        "name": "_native_transform",
        "op_symbol": "COEFF_OP_NATIVE_TRANSFORM",
        "op": 29,
        "internal": true,
        "args": [
          {
            "name": "name",
            "type": "registry_transform"
          },
          {
            "name": "src",
            "type": "selector",
            "slot": "src"
          },
          {
            "name": "tgt",
            "type": "selector",
            "slot": "tgt"
          }
        ]
      },
      {
        "name": "_native_transform_stack_args",
        "op_symbol": "COEFF_OP_NATIVE_TRANSFORM",
        "op": 29,
        "internal": true,
        "args": [
          {
            "name": "name",
            "type": "registry_transform"
          },
          {
            "name": "src",
            "type": "selector",
            "slot": "src"
          },
          {
            "name": "tgt",
            "type": "selector",
            "slot": "tgt"
          },
          {
            "name": "stack_arg_count",
            "type": "int_literal"
          }
        ]
      },
      {
        "name": "_typed_blend",
        "op_symbol": "COEFF_OP_TYPED_BLEND",
        "op": 30,
        "internal": true
      },
      {
        "name": "scan",
        "op_symbol": "COEFF_OP_SCAN",
        "op": 31,
        "args": [
          {
            "name": "length",
            "type": "int_literal"
          },
          {
            "name": "k0",
            "type": "int_literal"
          },
          {
            "name": "init",
            "type": "complex_expr"
          },
          {
            "name": "step",
            "type": "complex_expr"
          }
        ]
      },
      {
        "name": "slice",
        "op_symbol": "COEFF_OP_SLICE_READ",
        "op": 32,
        "args": [
          {
            "name": "source",
            "type": "selector",
            "slot": "push_src"
          },
          {
            "name": "start",
            "type": "int_literal"
          },
          {
            "name": "stop",
            "type": "int_literal"
          }
        ]
      },
      {
        "name": "poke_slice",
        "op_symbol": "COEFF_OP_SLICE_WRITE",
        "op": 33,
        "args": [
          {
            "name": "start",
            "type": "int_literal"
          },
          {
            "name": "stop",
            "type": "int_literal"
          }
        ]
      },
      {
        "name": "reduce",
        "op_symbol": "COEFF_OP_REDUCE",
        "op": 34,
        "args": [
          {
            "name": "fn",
            "type": "enum",
            "values": [
              "sum",
              "prod"
            ]
          }
        ]
      },
      {
        "name": "macro",
        "op_symbol": null,
        "op": null,
        "compile_time_only": true,
        "args": [
          {
            "name": "name",
            "type": "saved_program_name"
          }
        ]
      }
    ]
  },
  "programProfiles": {
    "version": 1,
    "profiles": {
      "param": {
        "program_kind": "param_program",
        "value_caps": {
          "program_tokens": 64,
          "total_stack": 16,
          "vector_len": 0,
          "vector_capable_stack": 0,
          "max_args": 8,
          "scalar_exprs": 64,
          "expr_tokens": 32,
          "lowered_expr_tokens": 32
        },
        "symbols": {
          "t1": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr",
              "selector"
            ]
          },
          "t2": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr",
              "selector"
            ]
          },
          "p1": {
            "type": "scalar_complex",
            "access": "read_write",
            "role": "output",
            "initial": "t1",
            "contexts": [
              "expr",
              "lhs",
              "selector"
            ]
          },
          "p2": {
            "type": "scalar_complex",
            "access": "read_write",
            "role": "output",
            "initial": "t2",
            "contexts": [
              "expr",
              "lhs",
              "selector"
            ]
          }
        },
        "selectors": {
          "legacy_src": [
            "p1",
            "p2",
            "both",
            "pop1",
            "pop2"
          ],
          "legacy_tgt": [
            "p1",
            "p2",
            "both",
            "push1",
            "push2"
          ],
          "push": [
            "t1",
            "t2"
          ],
          "emit": [
            "p1",
            "p2"
          ]
        },
        "selector_aliases": {
          "push": {
            "0": "t1",
            "1": "t2"
          },
          "emit": {
            "0": "p1",
            "1": "p2"
          }
        },
        "source": {
          "stack_op_aliases": {
            "dup": "duplicate",
            "duplicate": "duplicate",
            "swap": "swap",
            "pop": "pop",
            "flush": "flush"
          },
          "binary_ops": [
            "add",
            "subtract",
            "sub",
            "mul",
            "ratio",
            "div"
          ],
          "unary_ops": [
            "negate",
            "conj",
            "conjugate",
            "reciprocal",
            "unit_circle",
            "square",
            "cube",
            "exp"
          ],
          "targetable_unary": [
            "negate",
            "conj",
            "conjugate",
            "reciprocal",
            "unit_circle",
            "square",
            "cube",
            "exp"
          ],
          "unary_targets": [
            "p1",
            "p2"
          ],
          "push_sources": [
            "t1",
            "t2"
          ],
          "emit_aliases": {
            "emit_p1": "p1",
            "emit_p2": "p2"
          },
          "expression_namespace": {
            "constants": [
              "pi",
              "pi2",
              "pi2i"
            ],
            "functions": [
              "exp",
              "real",
              "imag",
              "abs",
              "mod"
            ]
          },
          "rejected_forms": [
            {
              "form": "push(both)",
              "code": "bad_selector",
              "use": "push(t1) or push(t2)"
            },
            {
              "form": "emit(p1)",
              "code": "noncanonical_emit",
              "use": "emit_p1, emit_p2, or p1 = expr"
            }
          ]
        },
        "outputs": [
          "p1",
          "p2"
        ],
        "output_contract": {
          "kind": "scalar_registers",
          "default_initialization": true
        }
      },
      "coeff": {
        "program_kind": "coeff_program",
        "value_caps": {
          "program_tokens": 256,
          "total_stack": 64,
          "vector_len": 256,
          "vector_capable_stack": 64,
          "max_args": 8,
          "scalar_exprs": 64,
          "expr_tokens": 64,
          "legacy_int_arg": 4096
        },
        "symbols": {
          "t1": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr"
            ]
          },
          "t2": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr"
            ]
          },
          "p1": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr"
            ]
          },
          "p2": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr"
            ]
          },
          "cf": {
            "type": "vector_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr_index_base",
              "selector",
              "rhs"
            ]
          },
          "poly": {
            "type": "vector_complex",
            "access": "read_write",
            "role": "output",
            "initial": "cf",
            "contexts": [
              "expr_index_base",
              "selector",
              "lhs",
              "rhs"
            ]
          },
          "poly_len": {
            "type": "int",
            "access": "read",
            "role": "derived",
            "from": "poly.length",
            "contexts": [
              "expr",
              "length_arg"
            ]
          },
          "tos": {
            "type": "stack_pseudo",
            "access": "read",
            "role": "stack_top",
            "contexts": [
              "expr_index_base",
              "rhs"
            ]
          }
        },
        "selectors": {
          "src": [
            "cf",
            "poly",
            "pop",
            "peek"
          ],
          "tgt": [
            "poly",
            "push"
          ],
          "push_src": [
            "cf",
            "poly"
          ],
          "set_tgt": [
            "poly"
          ],
          "vector_src": [
            "poly",
            "pop",
            "peek"
          ],
          "typed_vector_src": [
            "cf",
            "poly",
            "pop",
            "peek",
            "tos"
          ]
        },
        "outputs": [
          "poly"
        ],
        "output_contract": {
          "kind": "fixed_vector",
          "initial": "cf",
          "fixed_output_length": true
        }
      },
      "root": {
        "program_kind": "root_program",
        "value_caps": {
          "program_tokens": 16,
          "total_stack": 0,
          "vector_len": 256,
          "vector_capable_stack": 0
        },
        "source": {
          "registry": "root_legacy_registry.json",
          "args": "finite_real_static"
        },
        "symbols": {
          "roots": {
            "type": "vector_float",
            "access": "read_write",
            "role": "input_output",
            "contexts": [
              "lhs",
              "rhs"
            ]
          }
        },
        "selectors": {},
        "outputs": [
          "roots"
        ],
        "output_contract": {
          "kind": "in_place_vector",
          "length_preserving": true,
          "nan_policy": "poison"
        }
      },
      "solve_score": {
        "program_kind": "solve_score_program",
        "value_caps": {
          "program_tokens": 32,
          "total_stack": 64,
          "vector_len": 0,
          "vector_capable_stack": 0,
          "max_metric_slots": 16,
          "max_output_channels": 8
        },
        "source": {
          "locals": {
            "type": "scalar_score",
            "access": "read_write"
          },
          "reserved_output": "score",
          "metric_sources": [
            "slv",
            "cf",
            "pm"
          ],
          "output_calls": [
            "emit",
            "emit_norm",
            "emit_none"
          ],
          "metric_kwargs": {
            "q": "percent",
            "lag": [
              0,
              1
            ]
          }
        },
        "symbols": {
          "metrics": {
            "type": "metric_slot",
            "access": "read",
            "role": "metric",
            "namespace": {
              "prefix": "m",
              "count": 16,
              "lag_depths": [
                0,
                1
              ]
            },
            "contexts": [
              "expr",
              "rhs"
            ]
          }
        },
        "selectors": {},
        "outputs": [
          "score"
        ],
        "output_contract": {
          "kind": "terminal_scalar_or_emit_channels",
          "default_terminal_stack": true
        }
      }
    }
  }
};
