// AUTO-GENERATED by lambda/gen_merged_opcodes.py from lambda/merged_opcodes.json; do not edit
window._mergedOpcodeRegistry = {
  "opcodes": [
    {
      "id": 1,
      "name": "const",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_CONST",
      "symbol": "MERGED_OP_COEFF_CONST"
    },
    {
      "id": 2,
      "name": "push",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_PUSH",
      "symbol": "MERGED_OP_COEFF_PUSH"
    },
    {
      "id": 3,
      "name": "emit",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_EMIT",
      "symbol": "MERGED_OP_COEFF_EMIT"
    },
    {
      "id": 4,
      "name": "duplicate",
      "profile": "common",
      "source_symbol": "COEFF_OP_DUPLICATE",
      "symbol": "MERGED_OP_DUPLICATE"
    },
    {
      "id": 5,
      "name": "swap",
      "profile": "common",
      "source_symbol": "COEFF_OP_SWAP",
      "symbol": "MERGED_OP_SWAP"
    },
    {
      "id": 6,
      "name": "pop",
      "profile": "common",
      "source_symbol": "COEFF_OP_POP",
      "symbol": "MERGED_OP_POP"
    },
    {
      "id": 7,
      "name": "flush",
      "profile": "common",
      "source_symbol": "COEFF_OP_FLUSH",
      "symbol": "MERGED_OP_FLUSH"
    },
    {
      "id": 8,
      "name": "blend",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_BLEND",
      "symbol": "MERGED_OP_COEFF_BLEND"
    },
    {
      "id": 9,
      "name": "legacy",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_LEGACY",
      "symbol": "MERGED_OP_COEFF_LEGACY"
    },
    {
      "id": 10,
      "name": "poke_poly",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_POKE_POLY",
      "symbol": "MERGED_OP_COEFF_POKE_POLY"
    },
    {
      "id": 11,
      "name": "poke_tos",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_POKE_TOS",
      "symbol": "MERGED_OP_COEFF_POKE_TOS"
    },
    {
      "id": 12,
      "name": "vector_binary",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_VECTOR_BINARY",
      "symbol": "MERGED_OP_COEFF_VECTOR_BINARY"
    },
    {
      "id": 13,
      "name": "vector_unary",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_VECTOR_UNARY",
      "symbol": "MERGED_OP_COEFF_VECTOR_UNARY"
    },
    {
      "id": 14,
      "name": "vector_roll",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_VECTOR_ROLL",
      "symbol": "MERGED_OP_COEFF_VECTOR_ROLL"
    },
    {
      "id": 15,
      "name": "vector_argsort",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_VECTOR_ARGSORT",
      "symbol": "MERGED_OP_COEFF_VECTOR_ARGSORT"
    },
    {
      "id": 16,
      "name": "littlewood",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_LITTLEWOOD",
      "symbol": "MERGED_OP_COEFF_LITTLEWOOD"
    },
    {
      "id": 17,
      "name": "linspace",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_LINSPACE",
      "symbol": "MERGED_OP_COEFF_LINSPACE"
    },
    {
      "id": 18,
      "name": "range",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_RANGE",
      "symbol": "MERGED_OP_COEFF_RANGE"
    },
    {
      "id": 19,
      "name": "set",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_SET",
      "symbol": "MERGED_OP_COEFF_SET"
    },
    {
      "id": 20,
      "name": "affine",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_AFFINE",
      "symbol": "MERGED_OP_COEFF_AFFINE"
    },
    {
      "id": 21,
      "name": "typed_push_scalar",
      "profile": "common",
      "source_symbol": "COEFF_OP_TYPED_PUSH_SCALAR",
      "symbol": "MERGED_OP_TYPED_PUSH_SCALAR"
    },
    {
      "id": 22,
      "name": "typed_push_vector",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_TYPED_PUSH_VECTOR",
      "symbol": "MERGED_OP_TYPED_PUSH_VECTOR"
    },
    {
      "id": 23,
      "name": "typed_binary",
      "profile": "common",
      "source_symbol": "COEFF_OP_TYPED_BINARY",
      "symbol": "MERGED_OP_TYPED_BINARY"
    },
    {
      "id": 24,
      "name": "typed_unary",
      "profile": "common",
      "source_symbol": "COEFF_OP_TYPED_UNARY",
      "symbol": "MERGED_OP_TYPED_UNARY"
    },
    {
      "id": 25,
      "name": "typed_get_scalar",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_TYPED_GET_SCALAR",
      "symbol": "MERGED_OP_COEFF_TYPED_GET_SCALAR"
    },
    {
      "id": 26,
      "name": "typed_set_poly",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_TYPED_SET_POLY",
      "symbol": "MERGED_OP_COEFF_TYPED_SET_POLY"
    },
    {
      "id": 27,
      "name": "typed_poke_poly",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_TYPED_POKE_POLY",
      "symbol": "MERGED_OP_COEFF_TYPED_POKE_POLY"
    },
    {
      "id": 28,
      "name": "typed_fill",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_TYPED_FILL",
      "symbol": "MERGED_OP_COEFF_TYPED_FILL"
    },
    {
      "id": 29,
      "name": "native_transform",
      "profile": "common",
      "source_symbol": "COEFF_OP_NATIVE_TRANSFORM",
      "symbol": "MERGED_OP_NATIVE_TRANSFORM"
    },
    {
      "id": 30,
      "name": "typed_blend",
      "profile": "coeff",
      "source_symbol": "COEFF_OP_TYPED_BLEND",
      "symbol": "MERGED_OP_COEFF_TYPED_BLEND"
    },
    {
      "id": 31,
      "name": "push_t1",
      "profile": "param",
      "source_symbol": "PARAM_OP_PUSH_T1",
      "symbol": "MERGED_OP_PARAM_PUSH_T1"
    },
    {
      "id": 32,
      "name": "push_t2",
      "profile": "param",
      "source_symbol": "PARAM_OP_PUSH_T2",
      "symbol": "MERGED_OP_PARAM_PUSH_T2"
    },
    {
      "id": 33,
      "name": "push_p1",
      "profile": "param",
      "source_symbol": "PARAM_OP_PUSH_P1",
      "symbol": "MERGED_OP_PARAM_PUSH_P1"
    },
    {
      "id": 34,
      "name": "push_p2",
      "profile": "param",
      "source_symbol": "PARAM_OP_PUSH_P2",
      "symbol": "MERGED_OP_PARAM_PUSH_P2"
    },
    {
      "id": 35,
      "name": "emit_p1",
      "profile": "param",
      "source_symbol": "PARAM_OP_EMIT_P1",
      "symbol": "MERGED_OP_PARAM_EMIT_P1"
    },
    {
      "id": 36,
      "name": "emit_p2",
      "profile": "param",
      "source_symbol": "PARAM_OP_EMIT_P2",
      "symbol": "MERGED_OP_PARAM_EMIT_P2"
    },
    {
      "id": 37,
      "name": "ratio",
      "profile": "param",
      "source_symbol": "PARAM_OP_RATIO",
      "symbol": "MERGED_OP_PARAM_RATIO"
    },
    {
      "id": 38,
      "name": "divide",
      "profile": "param",
      "source_symbol": "PARAM_OP_DIVIDE",
      "symbol": "MERGED_OP_PARAM_DIVIDE"
    },
    {
      "id": 39,
      "name": "reciprocal",
      "profile": "param",
      "source_symbol": "PARAM_OP_RECIPROCAL",
      "symbol": "MERGED_OP_PARAM_RECIPROCAL"
    },
    {
      "id": 40,
      "name": "unit_circle",
      "profile": "param",
      "source_symbol": "PARAM_OP_UNIT_CIRCLE",
      "symbol": "MERGED_OP_PARAM_UNIT_CIRCLE"
    },
    {
      "id": 41,
      "name": "square",
      "profile": "param",
      "source_symbol": "PARAM_OP_SQUARE",
      "symbol": "MERGED_OP_PARAM_SQUARE"
    },
    {
      "id": 42,
      "name": "cube",
      "profile": "param",
      "source_symbol": "PARAM_OP_CUBE",
      "symbol": "MERGED_OP_PARAM_CUBE"
    },
    {
      "id": 64,
      "name": "reduce_metric",
      "profile": "solve_score",
      "symbol": "MERGED_OP_SCORE_REDUCE_METRIC"
    },
    {
      "id": 65,
      "name": "push_metric",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_PUSH_METRIC",
      "symbol": "MERGED_OP_SCORE_PUSH_METRIC"
    },
    {
      "id": 66,
      "name": "avg",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_AVG",
      "symbol": "MERGED_OP_SCORE_AVG"
    },
    {
      "id": 67,
      "name": "min",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_MIN",
      "symbol": "MERGED_OP_SCORE_MIN"
    },
    {
      "id": 68,
      "name": "max",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_MAX",
      "symbol": "MERGED_OP_SCORE_MAX"
    },
    {
      "id": 69,
      "name": "mul",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_MUL",
      "symbol": "MERGED_OP_SCORE_MUL"
    },
    {
      "id": 70,
      "name": "weighted_sum",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_WEIGHTED_SUM",
      "symbol": "MERGED_OP_SCORE_WEIGHTED_SUM"
    },
    {
      "id": 71,
      "name": "abs_diff",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_ABS_DIFF",
      "symbol": "MERGED_OP_SCORE_ABS_DIFF"
    },
    {
      "id": 72,
      "name": "geometric_mean",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_GEOMETRIC_MEAN",
      "symbol": "MERGED_OP_SCORE_GEOMETRIC_MEAN"
    },
    {
      "id": 73,
      "name": "omega_cosine",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_OMEGA_COSINE",
      "symbol": "MERGED_OP_SCORE_OMEGA_COSINE"
    },
    {
      "id": 74,
      "name": "sawtooth",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_SAWTOOTH",
      "symbol": "MERGED_OP_SCORE_SAWTOOTH"
    },
    {
      "id": 75,
      "name": "flip",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_FLIP",
      "symbol": "MERGED_OP_SCORE_FLIP"
    },
    {
      "id": 76,
      "name": "emit",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_EMIT",
      "symbol": "MERGED_OP_SCORE_EMIT"
    },
    {
      "id": 77,
      "name": "emit_norm",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_EMIT_NORM",
      "symbol": "MERGED_OP_SCORE_EMIT_NORM"
    },
    {
      "id": 78,
      "name": "const",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_CONST",
      "symbol": "MERGED_OP_SCORE_CONST"
    },
    {
      "id": 79,
      "name": "dup",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_DUP",
      "symbol": "MERGED_OP_SCORE_DUP"
    },
    {
      "id": 80,
      "name": "add",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_ADD",
      "symbol": "MERGED_OP_SCORE_ADD"
    },
    {
      "id": 81,
      "name": "mult",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_MULT",
      "symbol": "MERGED_OP_SCORE_MULT"
    },
    {
      "id": 82,
      "name": "subtract",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_SUBTRACT",
      "symbol": "MERGED_OP_SCORE_SUBTRACT"
    },
    {
      "id": 83,
      "name": "ratio",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_RATIO",
      "symbol": "MERGED_OP_SCORE_RATIO"
    },
    {
      "id": 84,
      "name": "clamp",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_CLAMP",
      "symbol": "MERGED_OP_SCORE_CLAMP"
    },
    {
      "id": 85,
      "name": "ema",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_EMA",
      "symbol": "MERGED_OP_SCORE_EMA"
    },
    {
      "id": 86,
      "name": "sin",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_SIN",
      "symbol": "MERGED_OP_SCORE_SIN"
    },
    {
      "id": 87,
      "name": "cos",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_COS",
      "symbol": "MERGED_OP_SCORE_COS"
    },
    {
      "id": 88,
      "name": "log",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_LOG",
      "symbol": "MERGED_OP_SCORE_LOG"
    },
    {
      "id": 89,
      "name": "exp",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_EXP",
      "symbol": "MERGED_OP_SCORE_EXP"
    },
    {
      "id": 90,
      "name": "pow",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_POW",
      "symbol": "MERGED_OP_SCORE_POW"
    },
    {
      "id": 91,
      "name": "emit_none",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_EMIT_NONE",
      "symbol": "MERGED_OP_SCORE_EMIT_NONE"
    },
    {
      "id": 92,
      "name": "flush",
      "profile": "solve_score",
      "source_symbol": "SOLVE_SCORE_OP_FLUSH",
      "symbol": "MERGED_OP_SCORE_FLUSH"
    },
    {
      "id": 43,
      "name": "push_reg",
      "profile": "param",
      "source_symbol": "PARAM_OP_PUSH_REG",
      "symbol": "MERGED_OP_PARAM_PUSH_REG"
    },
    {
      "id": 44,
      "name": "store_reg",
      "profile": "param",
      "source_symbol": "PARAM_OP_STORE_REG",
      "symbol": "MERGED_OP_PARAM_STORE_REG"
    }
  ],
  "ranges": {
    "coeff_reference": [
      1,
      30
    ],
    "param_specific": [
      31,
      47
    ],
    "reserved": [
      48,
      63
    ],
    "solve_score": [
      64,
      95
    ]
  },
  "registries": {
    "coeff": 1,
    "param": 2,
    "root": 3,
    "solve_score": 4
  },
  "version": 1
};
