// AUTO-GENERATED by lambda/gen_param_vocab.py from lambda Param Program metadata; do not edit
// Legacy Param transform names, argument display specs, and bridge compatibility metadata.
window._paramRegistryVocab = {
  "names": [
    "none",
    "unit_circle",
    "square",
    "cube",
    "reciprocal",
    "conjugate",
    "negate",
    "exp",
    "xim",
    "add_sub",
    "mul_div",
    "swap",
    "sum_prod",
    "roots2",
    "roots3",
    "roots5",
    "roots6",
    "rtheta",
    "moebius",
    "inv_t_plus_2",
    "crd",
    "hrt",
    "spdl",
    "lmc",
    "rsc",
    "lss",
    "ast",
    "asp",
    "lsp",
    "dlt",
    "rply",
    "star",
    "rect",
    "rrect",
    "z01",
    "coeff2",
    "coeff3",
    "coeff3a",
    "coeff4",
    "coeff5",
    "coeff5a",
    "coeff6",
    "coeff7",
    "coeff8",
    "coeff9",
    "coeff10",
    "coeff11",
    "coeff12",
    "zzold",
    "zz1",
    "zz2",
    "zz3",
    "t1radd",
    "t1iadd",
    "t2radd",
    "t2iadd",
    "radd",
    "iadd",
    "add",
    "cadd",
    "rscale",
    "iscale",
    "scale",
    "sdith",
    "ddith",
    "ndith",
    "adth",
    "ldth",
    "crdth",
    "scdth"
  ],
  "categoryMeta": {
    "maps": {
      "title": "Maps",
      "help": "direct complex maps applied to t1/t2"
    },
    "arithmetic": {
      "title": "Arithmetic",
      "help": "offset, scale, invert, or remix parameter values"
    },
    "shapes": {
      "title": "Curves + shapes",
      "help": "replace selected parameters with points on analytic curves"
    },
    "roots": {
      "title": "Root-derived",
      "help": "derive t1/t2 from roots of small polynomials"
    },
    "dither": {
      "title": "Dither",
      "help": "jitter parameters before coefficient generation"
    },
    "legacy": {
      "title": "Legacy coefficient maps",
      "help": "older named parameter recipes kept for compatibility"
    }
  },
  "uiFunctions": {
    "none": {
      "category": "legacy",
      "desc": "no-op; leave selected parameter values unchanged"
    },
    "unit_circle": {
      "category": "maps",
      "desc": "map z to exp(2*pi*i*z)",
      "effect": "f(z) = exp(2*pi*i*z). For z = a + i*b: f(z) = exp(-2*pi*b) * (cos(2*pi*a) + i*sin(2*pi*a)).",
      "notes": [
        "For normal real grid inputs x, this is x -> cos(2*pi*x) + i*sin(2*pi*x), mapping [0,1] around the unit circle.",
        "If the input has an imaginary part, it changes the radius: positive imaginary shrinks by exp(-2*pi*b), negative imaginary expands.",
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "square": {
      "category": "maps",
      "desc": "square each parameter",
      "effect": "f(z) = z^2. For z = a + i*b: f(z) = (a^2 - b^2) + i*(2*a*b).",
      "notes": [
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "cube": {
      "category": "maps",
      "desc": "cube each parameter",
      "effect": "f(z) = z^3. For z = a + i*b: f(z) = (a^3 - 3*a*b^2) + i*(3*a^2*b - b^3).",
      "notes": [
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "reciprocal": {
      "category": "maps",
      "desc": "complex reciprocal of each parameter",
      "effect": "f(z) = 1/z, computed as conj(z)/|z|^2.",
      "notes": [
        "If |z|^2 <= 1e-30 the output is set to 0 instead of overflowing.",
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "conjugate": {
      "category": "maps",
      "desc": "complex conjugate of each parameter",
      "effect": "f(z) = conj(z): a + i*b becomes a - i*b (reflection across the real axis).",
      "notes": [
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "negate": {
      "category": "maps",
      "desc": "negate each parameter",
      "effect": "f(z) = -z: both real and imaginary parts flip sign (point reflection through the origin).",
      "notes": [
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "exp": {
      "category": "maps",
      "desc": "complex exponential of each parameter",
      "effect": "f(z) = exp(z). For z = a + i*b: f(z) = exp(a) * (cos(b) + i*sin(b)).",
      "notes": [
        "This is the ordinary complex exponential, not unit_circle; angles are in radians, not turns.",
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "xim": {
      "category": "maps",
      "desc": "move real part into the imaginary axis",
      "effect": "f(z) = i*Re(z). For z = a + i*b: f(z) = 0 + i*a.",
      "notes": [
        "The original imaginary part is discarded.",
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "add_sub": {
      "category": "arithmetic",
      "desc": "emit t1+t2 and t1-t2",
      "effect": "out1 = z1 + z2; out2 = z1 - z2. Both computed from the original inputs.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "mul_div": {
      "category": "arithmetic",
      "desc": "emit t1*t2 and t1/t2",
      "effect": "out1 = z1 * z2; out2 = z1 / z2. Both computed from the original inputs.",
      "notes": [
        "If |z2|^2 <= 1e-30 the quotient out2 is set to 0 instead of overflowing.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "swap": {
      "category": "maps",
      "desc": "swap t1 and t2",
      "effect": "out1 = z2; out2 = z1.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "sum_prod": {
      "category": "arithmetic",
      "desc": "emit t1+t2 and t1*t2",
      "effect": "out1 = z1 + z2; out2 = z1 * z2. Both computed from the original inputs.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "roots2": {
      "category": "roots",
      "desc": "roots of the quadratic (9/64)z^2 + t1*z + t2",
      "effect": "Solves (9/64)*z^2 + z1*z + z2 = 0. out1, out2 are the two roots.",
      "notes": [
        "With a repeated root both outputs receive it; if no root exists both outputs are 0.",
        "Any non-finite root (solver overflow/degenerate leading coefficient) is replaced by 0.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "roots3": {
      "category": "roots",
      "desc": "extreme roots of a cubic built from t1+t2 and t1*t2",
      "effect": "Solves a*z^3 + b*z^2 + c*z + d = 0 with a = z1 + z2, b = 1, c = 1, d = z1*z2. out1 = root of smallest magnitude, out2 = root of largest magnitude.",
      "notes": [
        "Any non-finite root (solver overflow/degenerate leading coefficient) is replaced by 0.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "roots5": {
      "category": "roots",
      "desc": "extreme roots of a cubic with trig/imaginary coefficients",
      "effect": "Solves a*z^3 + b*z^2 + c*z + d = 0 with a = cos(100*z1), b = i*z1, c = i*z2, d = sin(100*z2). out1 = root of smallest magnitude, out2 = root of largest magnitude.",
      "notes": [
        "The factor 100 inside cos/sin makes the coefficients oscillate rapidly, so nearby grid points can land on very different roots.",
        "Any non-finite root (solver overflow/degenerate leading coefficient) is replaced by 0.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "roots6": {
      "category": "roots",
      "desc": "extreme roots of a quartic mixing t1 and t2",
      "effect": "Solves a*z^4 + b*z^3 + c*z^2 + d*z + e = 0 with a = sin(5*z1), b = i*z1, c = (z1-z2)^3 + (z1+z2)^2 + z1*z2 + 1, d = i*z2, e = sin(z2). out1 = root of smallest magnitude, out2 = root of largest magnitude.",
      "notes": [
        "Any non-finite root (solver overflow/degenerate leading coefficient) is replaced by 0.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "rtheta": {
      "category": "maps",
      "desc": "polar disk map using paired real parts as radius and angle",
      "effect": "For inputs z1,z2, let x=Re(z1), y=Re(z2). out1 = x^p * (cos(2*pi*y) + i*sin(2*pi*y)); out2 = y^p * (cos(2*pi*x) + i*sin(2*pi*x)).",
      "notes": [
        "The imaginary parts of both inputs are ignored.",
        "p defaults to 1 and is applied as a power to the radius coordinate.",
        "In Param Program source, use legacy(rtheta, src, tgt, p). The old raw target selector argument is represented by src/tgt.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "moebius": {
      "category": "maps",
      "desc": "Mobius map (a*t+b)/(c*t+d) on t1 and t2",
      "effect": "f(t) = (a*t + b)/(c*t + d), applied to both parameters with the same coefficients. With no arguments the legacy fixed map f(t) = 1/(t + 2) is used.",
      "notes": [
        "Defaults a=1, b=0, c=0, d=1 give the identity map.",
        "If the denominator magnitude is ~0 the output is set to 0.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "inv_t_plus_2": {
      "category": "arithmetic",
      "desc": "invert each parameter after a complex shift",
      "effect": "out1 = 1/(z1 + c1); out2 = 1/(z2 + c2), each computed as conj(w)/|w|^2. Defaults c1 = c2 = 2 reproduce the original fixed 1/(t+2) map.",
      "notes": [
        "If |w|^2 <= 1e-30 the output is set to 0 instead of overflowing.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "crd": {
      "category": "shapes",
      "desc": "cardioid curve",
      "effect": "theta = 2*pi*Re(z); r = size * (1 + cos(theta)); f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the cardioid angle.",
        "size defaults to 1. The maximum radius is 2*size at theta=0, and the cusp is at theta=pi.",
        "In Param Program source, use legacy(crd, src, tgt, size). The old raw n selector is represented by src/tgt; size is the only explicit transform argument.",
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1/pop2 read one/two stack values.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1/push2 push one/two outputs."
      ]
    },
    "hrt": {
      "category": "shapes",
      "desc": "heart curve",
      "effect": "t = 2*pi*Re(z) + pi/2; base = (16*sin(t)^3)/40 + i*((13*cos(t)-5*cos(2*t)-2*cos(3*t)-cos(4*t))/40 + 0.1); f(z) = size * exp(2*pi*i*turns) * base.",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the curve parameter.",
        "size defaults to 1 and scales the heart. turns defaults to 0 and rotates the result by full turns.",
        "In Param Program source, use legacy(hrt, src, tgt, size, turns). The old raw n selector is represented by src/tgt."
      ]
    },
    "spdl": {
      "category": "shapes",
      "desc": "spindle / superellipse-like curve",
      "effect": "theta = 2*pi*Re(z); e = 2/max(vp, 0.01); f(z) = va*sign(cos(theta))*abs(cos(theta))^e + i*vb*sign(sin(theta))*abs(sin(theta))^e.",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the curve angle.",
        "va and vb scale the horizontal and vertical axes. vp controls the superellipse exponent through e=2/max(vp,0.01).",
        "In Param Program source, use legacy(spdl, src, tgt, va, vb, vp). The old raw n selector is represented by src/tgt."
      ]
    },
    "lmc": {
      "category": "shapes",
      "desc": "limacon curve",
      "effect": "theta = 2*pi*Re(z); r = a + b*cos(theta); f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the polar angle.",
        "a sets the base radius; b sets the cosine modulation.",
        "In Param Program source, use legacy(lmc, src, tgt, a, b). The old raw n selector is represented by src/tgt."
      ]
    },
    "rsc": {
      "category": "shapes",
      "desc": "rose curve",
      "effect": "theta = 2*pi*Re(z); r = amp*cos(k*theta); f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the polar angle.",
        "amp scales the radius; k controls the rose frequency/petal structure.",
        "In Param Program source, use legacy(rsc, src, tgt, amp, k). The old raw n selector is represented by src/tgt."
      ]
    },
    "lss": {
      "category": "shapes",
      "desc": "Lissajous curve",
      "effect": "theta = 2*pi*Re(z); delta = pi*phase; f(z) = A*sin(a*theta + delta) + i*B*sin(b*theta).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the time parameter.",
        "A/B scale x/y; a/b are the x/y frequencies; phase is measured in half-turns because delta=pi*phase.",
        "In Param Program source, use legacy(lss, src, tgt, A, B, a, b, phase). The old raw n selector is represented by src/tgt."
      ]
    },
    "ast": {
      "category": "shapes",
      "desc": "astroid curve",
      "effect": "theta = 2*pi*Re(z); f(z) = scale*cos(theta)^3 + i*scale*sin(theta)^3.",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the curve angle.",
        "scale defaults to 1 and scales both axes.",
        "In Param Program source, use legacy(ast, src, tgt, scale). The old raw n selector is represented by src/tgt."
      ]
    },
    "asp": {
      "category": "shapes",
      "desc": "Archimedean spiral",
      "effect": "theta = 2*pi*Re(z); r = a + b*theta; f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the spiral angle.",
        "a is the starting radius; b is the radial growth per radian.",
        "In Param Program source, use legacy(asp, src, tgt, a, b). The old raw n selector is represented by src/tgt."
      ]
    },
    "lsp": {
      "category": "shapes",
      "desc": "logarithmic spiral",
      "effect": "theta = 2*pi*Re(z); r = a*exp(b*theta); f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the spiral angle.",
        "a sets the initial radius; b sets exponential radial growth.",
        "In Param Program source, use legacy(lsp, src, tgt, a, b). The old raw n selector is represented by src/tgt."
      ]
    },
    "dlt": {
      "category": "shapes",
      "desc": "deltoid curve",
      "effect": "theta = 2*pi*Re(z); f(z) = R*(2*cos(theta)+cos(2*theta))/3 + i*R*(2*sin(theta)-sin(2*theta))/3.",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the curve angle.",
        "R defaults to 1 and scales the deltoid.",
        "In Param Program source, use legacy(dlt, src, tgt, R). The old raw n selector is represented by src/tgt."
      ]
    },
    "rply": {
      "category": "shapes",
      "desc": "regular polygon perimeter",
      "effect": "t = fract(Re(z)); ns = max(int(sides), 3); linearly interpolate along the ns regular-polygon edges at radius, then rotate by exp(2*pi*i*turns).",
      "notes": [
        "The imaginary part of the input is ignored; fract(Re(z)) chooses distance along the perimeter.",
        "sides is truncated to an integer and clamped to at least 3. turns rotates the polygon by full turns.",
        "In Param Program source, use legacy(rply, src, tgt, sides, radius, turns). The old raw n selector is represented by src/tgt."
      ]
    },
    "star": {
      "category": "shapes",
      "desc": "star polygon perimeter",
      "effect": "t = fract(Re(z)); np = max(int(points), 3); walk 2*np alternating vertices with radii outer and outer*inner_ratio, linearly interpolating along each edge.",
      "notes": [
        "The imaginary part of the input is ignored; fract(Re(z)) chooses distance along the star perimeter.",
        "points is truncated to an integer and clamped to at least 3. inner_ratio controls the inner radius as a fraction of outer.",
        "In Param Program source, use legacy(star, src, tgt, points, outer, inner_ratio). The old raw n selector is represented by src/tgt."
      ]
    },
    "rect": {
      "category": "shapes",
      "desc": "rectangle perimeter",
      "effect": "t = fract(Re(z)); walk distance t*2*(w+h) around a centered rectangle of width w and height h, then rotate by exp(2*pi*i*turns).",
      "notes": [
        "The imaginary part of the input is ignored; fract(Re(z)) chooses arc-length position around the rectangle perimeter.",
        "The walk starts on the bottom edge from left to right, then right edge, top edge, and left edge. turns rotates the result by full turns.",
        "In Param Program source, use legacy(rect, src, tgt, w, h, turns). The old raw n selector is represented by src/tgt."
      ]
    },
    "rrect": {
      "category": "shapes",
      "desc": "rounded rectangle / superellipse",
      "effect": "theta = 2*pi*fract(Re(z)); e = 2/max(m, 0.01); f(z) = (w/2)*sign(cos(theta))*abs(cos(theta))^e + i*(h/2)*sign(sin(theta))*abs(sin(theta))^e.",
      "notes": [
        "The imaginary part of the input is ignored; fract(Re(z)) is used as the curve parameter.",
        "w and h set the bounding box. m controls the superellipse exponent through e=2/max(m,0.01).",
        "In Param Program source, use legacy(rrect, src, tgt, w, h, m). The old raw n selector is represented by src/tgt."
      ]
    },
    "z01": {
      "category": "arithmetic",
      "desc": "real-part mirror remix",
      "effect": "For inputs z1,z2, let x=Re(z1), y=Re(z2). out1 = x + i*y; out2 = y + i*x.",
      "notes": [
        "The imaginary parts of both inputs are ignored.",
        "This is a pair transform: src=both reads p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs.",
        "It takes no explicit transform arguments."
      ]
    },
    "coeff2": {
      "category": "legacy",
      "desc": "legacy sum/product map",
      "effect": "out1 = z1 + z2; out2 = z1 * z2. Identical to sum_prod, kept under its legacy name.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff3": {
      "category": "legacy",
      "desc": "legacy shifted inversion 1/(t+2)",
      "effect": "out1 = 1/(z1 + 2); out2 = 1/(z2 + 2).",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff3a": {
      "category": "legacy",
      "desc": "legacy shifted inversion 1/(t+1)",
      "effect": "out1 = 1/(z1 + 1); out2 = 1/(z2 + 1).",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff4": {
      "category": "legacy",
      "desc": "legacy cos/sin map",
      "effect": "out1 = cos(z1); out2 = sin(z2), using the full complex cosine and sine.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff5": {
      "category": "legacy",
      "desc": "legacy cross-reciprocal map",
      "effect": "out1 = z1 + 1/z2; out2 = z2 + 1/z1. Each parameter is shifted by the reciprocal of the other.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff5a": {
      "category": "legacy",
      "desc": "legacy self-reciprocal (Joukowski-style) map",
      "effect": "out1 = z1 + 1/z1; out2 = z2 + 1/z2.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff6": {
      "category": "legacy",
      "desc": "legacy cubic Cayley-style map",
      "effect": "out = (t^3 + i)/(t^3 - i), applied to each parameter independently.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff7": {
      "category": "legacy",
      "desc": "legacy trig fractional map",
      "effect": "out = (t + sin(t))/(t + cos(t)), applied to each parameter independently.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff8": {
      "category": "legacy",
      "desc": "legacy cross-trig fractional map",
      "effect": "out1 = (z1 + sin(z2))/(z2 + cos(z1)); out2 = (z2 + sin(z1))/(z1 + cos(z2)).",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff9": {
      "category": "legacy",
      "desc": "legacy squared cross-fraction map",
      "effect": "out1 = (z1^2 + i*z2)/(z1^2 - i*z2); out2 = (z2^2 + i*z1)/(z2^2 - i*z1).",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff10": {
      "category": "legacy",
      "desc": "legacy fourth-power cross-fraction map",
      "effect": "out1 = (z1^4 - z2)/(z1^4 + z2); out2 = (z2^4 - z1)/(z2^4 + z1).",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff11": {
      "category": "legacy",
      "desc": "legacy log of fourth power map",
      "effect": "out = log(t^4 + 2), applied to each parameter independently (principal complex logarithm).",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "coeff12": {
      "category": "legacy",
      "desc": "legacy mixed quartic polynomial map",
      "effect": "out1 = 2*z1^4 - 3*z2^3 + 4*z1^2 - 5*z2; out2 = 2*z2^4 - 3*z1^3 + 4*z2^2 - 5*z1.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "zzold": {
      "category": "arithmetic",
      "desc": "duplicate t1 + i*t2 into both slots",
      "effect": "out1 = out2 = z1 + i*z2.",
      "notes": [
        "For z1 = a + i*b and z2 = c + i*d: z1 + i*z2 = (a - d) + i*(b + c). Both outputs use the original inputs.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "zz1": {
      "category": "arithmetic",
      "desc": "t1 + i*t2 and t1*t2 + i*(t1+t2)",
      "effect": "out1 = z1 + i*z2; out2 = z1*z2 + i*(z1 + z2).",
      "notes": [
        "For z1 = a + i*b and z2 = c + i*d: z1 + i*z2 = (a - d) + i*(b + c). Both outputs use the original inputs.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "zz2": {
      "category": "arithmetic",
      "desc": "t1 + i*t2 and t1 - i*t2",
      "effect": "out1 = z1 + i*z2; out2 = z1 - i*z2.",
      "notes": [
        "For z1 = a + i*b and z2 = c + i*d: z1 + i*z2 = (a - d) + i*(b + c). Both outputs use the original inputs.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "zz3": {
      "category": "arithmetic",
      "desc": "t1 + i*t2 and t2 + i*t1",
      "effect": "out1 = z1 + i*z2; out2 = z2 + i*z1.",
      "notes": [
        "For z1 = a + i*b and z2 = c + i*d: z1 + i*z2 = (a - d) + i*(b + c). Both outputs use the original inputs.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "t1radd": {
      "category": "arithmetic",
      "desc": "add to real part of t1 only",
      "effect": "Re(t1) += v. The other three components are unchanged.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "t1iadd": {
      "category": "arithmetic",
      "desc": "add to imaginary part of t1 only",
      "effect": "Im(t1) += v. The other three components are unchanged.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "t2radd": {
      "category": "arithmetic",
      "desc": "add to real part of t2 only",
      "effect": "Re(t2) += v. The other three components are unchanged.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "t2iadd": {
      "category": "arithmetic",
      "desc": "add to imaginary part of t2 only",
      "effect": "Im(t2) += v. The other three components are unchanged.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "radd": {
      "category": "arithmetic",
      "desc": "add to real parts of both parameters",
      "effect": "Re(t1) += v; Re(t2) += v. Imaginary parts are unchanged.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "iadd": {
      "category": "arithmetic",
      "desc": "add to imaginary parts of both parameters",
      "effect": "Im(t1) += v; Im(t2) += v. Real parts are unchanged.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "add": {
      "category": "arithmetic",
      "desc": "add offsets: one scalar to all components, or complex c1,c2 per parameter",
      "effect": "add(v): adds the real scalar v to all four components, Re and Im of both parameters. add(c1, c2): t1 += c1 and t2 += c2 with complex offsets.",
      "notes": [
        "The one-argument form is the legacy behavior: v lands on the imaginary parts too, not just the real parts.",
        "Complex offsets accept literals like 0.5+0.25i.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "cadd": {
      "category": "arithmetic",
      "desc": "add a complex constant to t1 and t2",
      "effect": "t1 += (re + i*im); t2 += (re + i*im).",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "rscale": {
      "category": "arithmetic",
      "desc": "scale real parts only",
      "effect": "Re(t1) *= v; Re(t2) *= v. Imaginary parts are unchanged.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "iscale": {
      "category": "arithmetic",
      "desc": "scale imaginary parts only",
      "effect": "Im(t1) *= v; Im(t2) *= v. Real parts are unchanged.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "scale": {
      "category": "arithmetic",
      "desc": "scale all components uniformly",
      "effect": "t1 *= v; t2 *= v, with real v: all four components are multiplied by v.",
      "notes": [
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "sdith": {
      "category": "dither",
      "desc": "square uniform jitter on all components",
      "effect": "Adds independent uniform noise in [-w/2, +w/2] to all four components (Re and Im of t1 and t2), where w = d/N.",
      "notes": [
        "N is the sweep grid resolution, so jitter is sized relative to one grid cell and stays sub-pixel as resolution grows.",
        "A fresh random offset is drawn for every grid sample; d <= 0 falls back to d = 1.",
        "Dithers always operate in place on the parameter registers (src and tgt are both)."
      ]
    },
    "ddith": {
      "category": "dither",
      "desc": "disk jitter with tunable radial density",
      "effect": "Adds a random offset inside a disk of radius rmax = d/N: angle uniform in [0, 2*pi), radius r = u^exp * rmax with u uniform in [0,1).",
      "notes": [
        "exp = 0.5 gives uniform density by area; larger exp concentrates samples toward the center, smaller exp toward the rim.",
        "target selects which parameter is jittered: 0 = t1, 1 = t2, 2 = both.",
        "N is the sweep grid resolution, so jitter is sized relative to one grid cell and stays sub-pixel as resolution grows.",
        "A fresh random offset is drawn for every grid sample; d <= 0 falls back to d = 1.",
        "Dithers always operate in place on the parameter registers (src and tgt are both)."
      ]
    },
    "ndith": {
      "category": "dither",
      "desc": "Gaussian jitter on all components",
      "effect": "Adds independent Gaussian noise with sigma = d/N to all four components (Re and Im of t1 and t2), sampled via the Box-Muller transform.",
      "notes": [
        "N is the sweep grid resolution, so jitter is sized relative to one grid cell and stays sub-pixel as resolution grows.",
        "A fresh random offset is drawn for every grid sample; d <= 0 falls back to d = 1.",
        "Dithers always operate in place on the parameter registers (src and tgt are both)."
      ]
    },
    "adth": {
      "category": "dither",
      "desc": "annulus jitter",
      "effect": "Adds a random offset inside the annulus with radii [inner*rmax, rmax], rmax = d/N: radius drawn area-uniform via r = sqrt(r0^2 + u*(r1^2 - r0^2)), angle uniform.",
      "notes": [
        "inner is clamped to [0,1]; inner = 0 degenerates to a full disk.",
        "target selects which parameter is jittered: 0 = t1, 1 = t2, 2 = both.",
        "N is the sweep grid resolution, so jitter is sized relative to one grid cell and stays sub-pixel as resolution grows.",
        "A fresh random offset is drawn for every grid sample; d <= 0 falls back to d = 1.",
        "Dithers always operate in place on the parameter registers (src and tgt are both)."
      ]
    },
    "ldth": {
      "category": "dither",
      "desc": "line-segment jitter",
      "effect": "Adds t * (cos(angle) + i*sin(angle)) with t uniform in [-h, +h], where h = (d/N) * len.",
      "notes": [
        "target selects which parameter is jittered: 0 = t1, 1 = t2, 2 = both.",
        "N is the sweep grid resolution, so jitter is sized relative to one grid cell and stays sub-pixel as resolution grows.",
        "A fresh random offset is drawn for every grid sample; d <= 0 falls back to d = 1.",
        "Dithers always operate in place on the parameter registers (src and tgt are both)."
      ]
    },
    "crdth": {
      "category": "dither",
      "desc": "cross-shaped jitter",
      "effect": "With 50/50 probability adds a horizontal or vertical displacement uniform in [-h, +h], where h = d/N.",
      "notes": [
        "target selects which parameter is jittered: 0 = t1, 1 = t2, 2 = both.",
        "N is the sweep grid resolution, so jitter is sized relative to one grid cell and stays sub-pixel as resolution grows.",
        "A fresh random offset is drawn for every grid sample; d <= 0 falls back to d = 1.",
        "Dithers always operate in place on the parameter registers (src and tgt are both)."
      ]
    },
    "scdth": {
      "category": "dither",
      "desc": "circular-sector jitter",
      "effect": "Adds a random offset inside a circular sector: radius r = sqrt(u) * rmax (area-uniform) with rmax = d/N, angle uniform in [center - half_ap*pi, center + half_ap*pi].",
      "notes": [
        "half_ap is a fraction of pi and is clamped to [0,1]: half_ap = 1 covers the full circle, 0.25 covers a quarter-turn aperture.",
        "target selects which parameter is jittered: 0 = t1, 1 = t2, 2 = both.",
        "N is the sweep grid resolution, so jitter is sized relative to one grid cell and stays sub-pixel as resolution grows.",
        "A fresh random offset is drawn for every grid sample; d <= 0 falls back to d = 1.",
        "Dithers always operate in place on the parameter registers (src and tgt are both)."
      ]
    }
  },
  "argSpecs": {
    "rtheta": [
      {
        "ph": "p",
        "def": "1",
        "scalarExpr": true,
        "title": "Power applied to the radius coordinate: out1 radius is Re(z1)^p and out2 radius is Re(z2)^p.",
        "exprWide": true
      }
    ],
    "moebius": [
      {
        "ph": "a",
        "def": "1",
        "scalarExpr": true,
        "title": "Coefficient a in f(t) = (a*t + b)/(c*t + d).",
        "complexWide": true
      },
      {
        "ph": "b",
        "def": "0",
        "scalarExpr": true,
        "title": "Coefficient b in f(t) = (a*t + b)/(c*t + d).",
        "complexWide": true
      },
      {
        "ph": "c",
        "def": "0",
        "scalarExpr": true,
        "title": "Coefficient c in f(t) = (a*t + b)/(c*t + d).",
        "complexWide": true
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Coefficient d in f(t) = (a*t + b)/(c*t + d).",
        "complexWide": true
      }
    ],
    "inv_t_plus_2": [
      {
        "ph": "z1",
        "def": "2",
        "scalarExpr": true,
        "title": "Complex offset c1 added to t1 before inversion: out1 = 1/(t1 + c1).",
        "complexWide": true
      },
      {
        "ph": "z2",
        "def": "2",
        "scalarExpr": true,
        "title": "Complex offset c2 added to t2 before inversion: out2 = 1/(t2 + c2).",
        "complexWide": true
      }
    ],
    "crd": [
      {
        "ph": "size",
        "def": "1",
        "scalarExpr": true,
        "title": "Cardioid scale. Maximum radius is 2*size.",
        "exprWide": true
      }
    ],
    "hrt": [
      {
        "ph": "size",
        "def": "1",
        "scalarExpr": true,
        "title": "Heart scale.",
        "exprWide": true
      },
      {
        "ph": "turns",
        "def": "0",
        "scalarExpr": true,
        "title": "Rotation in full turns after the heart is generated; 0.25 rotates by 90 degrees.",
        "exprWide": true
      }
    ],
    "spdl": [
      {
        "ph": "va",
        "def": "0.5",
        "scalarExpr": true,
        "title": "Horizontal scale.",
        "exprWide": true
      },
      {
        "ph": "vb",
        "def": "0.2",
        "scalarExpr": true,
        "title": "Vertical scale.",
        "exprWide": true
      },
      {
        "ph": "vp",
        "def": "1.5",
        "scalarExpr": true,
        "title": "Shape exponent control; native code uses e=2/max(vp,0.01).",
        "exprWide": true
      }
    ],
    "lmc": [
      {
        "ph": "a",
        "def": "0.3",
        "scalarExpr": true,
        "title": "Base radius in r=a+b*cos(theta).",
        "exprWide": true
      },
      {
        "ph": "b",
        "def": "0.5",
        "scalarExpr": true,
        "title": "Cosine radius modulation in r=a+b*cos(theta).",
        "exprWide": true
      }
    ],
    "rsc": [
      {
        "ph": "amp",
        "def": "0.5",
        "scalarExpr": true,
        "title": "Rose radius amplitude.",
        "exprWide": true
      },
      {
        "ph": "k",
        "def": "2",
        "scalarExpr": true,
        "title": "Rose angular frequency in r=amp*cos(k*theta).",
        "exprWide": true
      }
    ],
    "lss": [
      {
        "ph": "A",
        "def": "0.5",
        "scalarExpr": true,
        "title": "Horizontal amplitude.",
        "exprWide": true
      },
      {
        "ph": "B",
        "def": "0.5",
        "scalarExpr": true,
        "title": "Vertical amplitude.",
        "exprWide": true
      },
      {
        "ph": "a",
        "def": "3",
        "scalarExpr": true,
        "title": "Horizontal sine frequency.",
        "exprWide": true
      },
      {
        "ph": "b",
        "def": "2",
        "scalarExpr": true,
        "title": "Vertical sine frequency.",
        "exprWide": true
      },
      {
        "ph": "phase",
        "def": "0.5",
        "scalarExpr": true,
        "title": "Horizontal phase offset in half-turns; native delta is pi*phase.",
        "exprWide": true
      }
    ],
    "ast": [
      {
        "ph": "scale",
        "def": "1",
        "scalarExpr": true,
        "title": "Astroid scale applied to both axes.",
        "exprWide": true
      }
    ],
    "asp": [
      {
        "ph": "a",
        "def": "0",
        "scalarExpr": true,
        "title": "Starting radius in r=a+b*theta.",
        "exprWide": true
      },
      {
        "ph": "b",
        "def": "0.1",
        "scalarExpr": true,
        "title": "Linear radial growth per radian in r=a+b*theta.",
        "exprWide": true
      }
    ],
    "lsp": [
      {
        "ph": "a",
        "def": "0.1",
        "scalarExpr": true,
        "title": "Initial radius multiplier in r=a*exp(b*theta).",
        "exprWide": true
      },
      {
        "ph": "b",
        "def": "0.15",
        "scalarExpr": true,
        "title": "Exponential radial growth rate in r=a*exp(b*theta).",
        "exprWide": true
      }
    ],
    "dlt": [
      {
        "ph": "R",
        "def": "1",
        "scalarExpr": true,
        "title": "Deltoid scale/radius.",
        "exprWide": true
      }
    ],
    "rply": [
      {
        "ph": "sides",
        "def": "5",
        "scalarExpr": true,
        "title": "Number of polygon sides; truncated to an integer and clamped to at least 3.",
        "exprWide": true
      },
      {
        "ph": "radius",
        "def": "1",
        "scalarExpr": true,
        "title": "Radius of the polygon vertices.",
        "exprWide": true
      },
      {
        "ph": "turns",
        "def": "0",
        "scalarExpr": true,
        "title": "Rotation in full turns after the polygon point is generated.",
        "exprWide": true
      }
    ],
    "star": [
      {
        "ph": "points",
        "def": "5",
        "scalarExpr": true,
        "title": "Number of star points; truncated to an integer and clamped to at least 3.",
        "exprWide": true
      },
      {
        "ph": "outer",
        "def": "1",
        "scalarExpr": true,
        "title": "Outer vertex radius.",
        "exprWide": true
      },
      {
        "ph": "inner_ratio",
        "def": "0.5",
        "scalarExpr": true,
        "title": "Inner vertex radius as a fraction of outer.",
        "exprWide": true
      }
    ],
    "rect": [
      {
        "ph": "w",
        "def": "2",
        "scalarExpr": true,
        "title": "Rectangle width.",
        "exprWide": true
      },
      {
        "ph": "h",
        "def": "1",
        "scalarExpr": true,
        "title": "Rectangle height.",
        "exprWide": true
      },
      {
        "ph": "turns",
        "def": "0",
        "scalarExpr": true,
        "title": "Rotation in full turns after walking the rectangle perimeter; 0.25 rotates by 90 degrees.",
        "exprWide": true
      }
    ],
    "rrect": [
      {
        "ph": "w",
        "def": "2",
        "scalarExpr": true,
        "title": "Bounding-box width.",
        "exprWide": true
      },
      {
        "ph": "h",
        "def": "1",
        "scalarExpr": true,
        "title": "Bounding-box height.",
        "exprWide": true
      },
      {
        "ph": "m",
        "def": "4",
        "scalarExpr": true,
        "title": "Superellipse exponent control; native code uses e=2/max(m,0.01).",
        "exprWide": true
      }
    ],
    "t1radd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "title": "Real amount added to Re(t1).",
        "exprWide": true
      }
    ],
    "t1iadd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "title": "Real amount added to Im(t1).",
        "exprWide": true
      }
    ],
    "t2radd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "title": "Real amount added to Re(t2).",
        "exprWide": true
      }
    ],
    "t2iadd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "title": "Real amount added to Im(t2).",
        "exprWide": true
      }
    ],
    "radd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "title": "Real amount added to Re(t1) and Re(t2).",
        "exprWide": true
      }
    ],
    "iadd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "title": "Real amount added to Im(t1) and Im(t2).",
        "exprWide": true
      }
    ],
    "cadd": [
      {
        "ph": "re",
        "def": "0",
        "scalarExpr": true,
        "title": "Real part of the complex offset added to both parameters.",
        "exprWide": true
      },
      {
        "ph": "im",
        "def": "0",
        "scalarExpr": true,
        "title": "Imaginary part of the complex offset added to both parameters.",
        "exprWide": true
      }
    ],
    "rscale": [
      {
        "ph": "v",
        "def": "1",
        "scalarExpr": true,
        "title": "Factor multiplying Re(t1) and Re(t2).",
        "exprWide": true
      }
    ],
    "iscale": [
      {
        "ph": "v",
        "def": "1",
        "scalarExpr": true,
        "title": "Factor multiplying Im(t1) and Im(t2).",
        "exprWide": true
      }
    ],
    "scale": [
      {
        "ph": "v",
        "def": "1",
        "scalarExpr": true,
        "title": "Real factor multiplying all four components.",
        "exprWide": true
      }
    ],
    "sdith": [
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Dither width in grid spacings; native width is d/N.",
        "exprWide": true
      }
    ],
    "ddith": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "title": "Legacy target selector: 0=p1, 1=p2, 2=both.",
        "exprWide": true
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Disk dither radius in grid spacings; native radius is d/N.",
        "exprWide": true
      },
      {
        "ph": "exp",
        "def": "0.5",
        "scalarExpr": true,
        "title": "Radial distribution exponent; 0.5 gives uniform disk area.",
        "exprWide": true
      }
    ],
    "ndith": [
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Gaussian jitter sigma in grid spacings; native sigma is d/N.",
        "exprWide": true
      }
    ],
    "adth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "title": "Legacy target selector: 0=p1, 1=p2, 2=both.",
        "exprWide": true
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Outer annulus radius in grid spacings; native radius is d/N.",
        "exprWide": true
      },
      {
        "ph": "inner",
        "def": "0.4",
        "scalarExpr": true,
        "title": "Inner radius fraction of the outer radius, clamped to [0,1].",
        "exprWide": true
      }
    ],
    "ldth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "title": "Legacy target selector: 0=p1, 1=p2, 2=both.",
        "exprWide": true
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Line dither base length in grid spacings; native half-length is (d/N)*len.",
        "exprWide": true
      },
      {
        "ph": "len",
        "def": "1",
        "scalarExpr": true,
        "title": "Multiplier for the line segment half-length.",
        "exprWide": true
      },
      {
        "ph": "angle",
        "def": "0",
        "scalarExpr": true,
        "title": "Line angle in radians.",
        "exprWide": true
      }
    ],
    "crdth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "title": "Legacy target selector: 0=p1, 1=p2, 2=both.",
        "exprWide": true
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Cross dither half-length in grid spacings; native half-length is d/N.",
        "exprWide": true
      }
    ],
    "scdth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "title": "Legacy target selector: 0=p1, 1=p2, 2=both.",
        "exprWide": true
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Sector dither radius in grid spacings; native radius is d/N.",
        "exprWide": true
      },
      {
        "ph": "half_ap",
        "def": "0.25",
        "scalarExpr": true,
        "title": "Sector half-aperture as a fraction of pi radians.",
        "exprWide": true
      },
      {
        "ph": "center",
        "def": "0",
        "scalarExpr": true,
        "title": "Sector center angle in radians.",
        "exprWide": true
      }
    ]
  },
  "targetArgIndexes": {
    "rtheta": 1,
    "crd": 0,
    "hrt": 0,
    "spdl": 0,
    "lmc": 0,
    "rsc": 0,
    "lss": 0,
    "ast": 0,
    "asp": 0,
    "lsp": 0,
    "dlt": 0,
    "rply": 0,
    "star": 0,
    "rect": 0,
    "rrect": 0
  },
  "variableArgCounts": {
    "moebius": [
      0,
      4,
      8
    ],
    "inv_t_plus_2": [
      0,
      1,
      2,
      3,
      4
    ],
    "add": [
      0,
      1,
      2
    ]
  },
  "variableArgForms": {
    "moebius": {
      "counts": [
        0,
        4,
        8
      ],
      "forms": [
        "none",
        "a,b,c,d as complex values",
        "old a_re,a_im,b_re,b_im,c_re,c_im,d_re,d_im components"
      ]
    },
    "inv_t_plus_2": {
      "counts": [
        0,
        1,
        2,
        3,
        4
      ],
      "forms": [
        "none",
        "z1",
        "z1,z2",
        "old z1_re,z1_im,z2_re components (z2_im defaults to 0)",
        "old z1_re,z1_im,z2_re,z2_im components"
      ]
    },
    "add": {
      "counts": [
        0,
        1,
        2
      ],
      "forms": [
        "none",
        "one real scalar offset for both parameters",
        "two complex offsets for p1 and p2"
      ]
    }
  },
  "independentTargets": [
    "conjugate",
    "cube",
    "exp",
    "negate",
    "reciprocal",
    "square",
    "unit_circle",
    "xim"
  ]
};
