// AUTO-GENERATED by lambda/gen_param_vocab.py from lambda Param Program metadata; do not edit
// Legacy Param transform names, argument display specs, and bridge compatibility metadata.
window._paramRegistryVocab = {
  "names": [
    "none",
    "unit_circle",
    "square",
    "cube",
    "reciprocal",
    "conjugate",
    "negate",
    "exp",
    "xim",
    "add_sub",
    "mul_div",
    "swap",
    "sum_prod",
    "roots2",
    "roots3",
    "roots5",
    "roots6",
    "rtheta",
    "moebius",
    "inv_t_plus_2",
    "crd",
    "hrt",
    "spdl",
    "lmc",
    "rsc",
    "lss",
    "ast",
    "asp",
    "lsp",
    "dlt",
    "rply",
    "star",
    "rect",
    "rrect",
    "z01",
    "coeff2",
    "coeff3",
    "coeff3a",
    "coeff4",
    "coeff5",
    "coeff5a",
    "coeff6",
    "coeff7",
    "coeff8",
    "coeff9",
    "coeff10",
    "coeff11",
    "coeff12",
    "zzold",
    "zz1",
    "zz2",
    "zz3",
    "t1radd",
    "t1iadd",
    "t2radd",
    "t2iadd",
    "radd",
    "iadd",
    "add",
    "cadd",
    "rscale",
    "iscale",
    "scale",
    "sdith",
    "ddith",
    "ndith",
    "adth",
    "ldth",
    "crdth",
    "scdth"
  ],
  "categoryMeta": {
    "maps": {
      "title": "Maps",
      "help": "direct complex maps applied to t1/t2"
    },
    "arithmetic": {
      "title": "Arithmetic",
      "help": "offset, scale, invert, or remix parameter values"
    },
    "shapes": {
      "title": "Curves + shapes",
      "help": "replace selected parameters with points on analytic curves"
    },
    "roots": {
      "title": "Root-derived",
      "help": "derive t1/t2 from roots of small polynomials"
    },
    "dither": {
      "title": "Dither",
      "help": "jitter parameters before coefficient generation"
    },
    "legacy": {
      "title": "Legacy coefficient maps",
      "help": "older named parameter recipes kept for compatibility"
    }
  },
  "uiFunctions": {
    "unit_circle": {
      "category": "maps",
      "desc": "map real t to exp(2*pi*i*t)"
    },
    "rtheta": {
      "category": "maps",
      "desc": "polar disk map using t1/t2 as radius and angle"
    },
    "square": {
      "category": "maps",
      "desc": "square both complex parameters"
    },
    "cube": {
      "category": "maps",
      "desc": "cube both complex parameters"
    },
    "reciprocal": {
      "category": "maps",
      "desc": "replace each parameter with 1/t"
    },
    "conjugate": {
      "category": "maps",
      "desc": "complex conjugate t1 and t2"
    },
    "swap": {
      "category": "maps",
      "desc": "swap t1 and t2"
    },
    "add_sub": {
      "category": "arithmetic",
      "desc": "emit t1+t2 and t1-t2"
    },
    "mul_div": {
      "category": "arithmetic",
      "desc": "emit t1*t2 and t1/t2"
    },
    "moebius": {
      "category": "maps",
      "desc": "Mobius map on t1 and t2; 0-arg runs keep legacy 1/(t+2)"
    },
    "negate": {
      "category": "maps",
      "desc": "negate t1 and t2"
    },
    "exp": {
      "category": "maps",
      "desc": "complex exponential of each parameter"
    },
    "xim": {
      "category": "maps",
      "desc": "move real part into the imaginary axis"
    },
    "zzold": {
      "category": "arithmetic",
      "desc": "legacy t1+i*t2 remix into both slots"
    },
    "zz1": {
      "category": "arithmetic",
      "desc": "t1+i*t2 and t1*t2+i*(t1+t2)"
    },
    "zz2": {
      "category": "arithmetic",
      "desc": "t1+i*t2 and t1-i*t2"
    },
    "zz3": {
      "category": "arithmetic",
      "desc": "cross-imaginary remix of t1 and t2"
    },
    "inv_t_plus_2": {
      "category": "arithmetic",
      "desc": "t1=1/(t1+a), t2=1/(t2+b)"
    },
    "t1radd": {
      "category": "arithmetic",
      "desc": "add to real part of t1 only"
    },
    "t1iadd": {
      "category": "arithmetic",
      "desc": "add to imaginary part of t1 only"
    },
    "t2radd": {
      "category": "arithmetic",
      "desc": "add to real part of t2 only"
    },
    "t2iadd": {
      "category": "arithmetic",
      "desc": "add to imaginary part of t2 only"
    },
    "radd": {
      "category": "arithmetic",
      "desc": "add to real parts of both parameters"
    },
    "iadd": {
      "category": "arithmetic",
      "desc": "add to imaginary parts of both parameters"
    },
    "add": {
      "category": "arithmetic",
      "desc": "z1=z1+c1 and z2=z2+c2 using complex offsets"
    },
    "cadd": {
      "category": "arithmetic",
      "desc": "add a complex constant to t1 and t2"
    },
    "rscale": {
      "category": "arithmetic",
      "desc": "scale real parts only"
    },
    "iscale": {
      "category": "arithmetic",
      "desc": "scale imaginary parts only"
    },
    "scale": {
      "category": "arithmetic",
      "desc": "scale all components"
    },
    "crd": {
      "category": "shapes",
      "desc": "cardioid curve"
    },
    "hrt": {
      "category": "shapes",
      "desc": "heart curve"
    },
    "spdl": {
      "category": "shapes",
      "desc": "spindle curve"
    },
    "lmc": {
      "category": "shapes",
      "desc": "limacon curve"
    },
    "rsc": {
      "category": "shapes",
      "desc": "rose curve"
    },
    "lss": {
      "category": "shapes",
      "desc": "Lissajous curve"
    },
    "ast": {
      "category": "shapes",
      "desc": "astroid curve"
    },
    "asp": {
      "category": "shapes",
      "desc": "Archimedean spiral"
    },
    "lsp": {
      "category": "shapes",
      "desc": "log spiral"
    },
    "dlt": {
      "category": "shapes",
      "desc": "deltoid curve"
    },
    "rply": {
      "category": "shapes",
      "desc": "regular polygon perimeter"
    },
    "star": {
      "category": "shapes",
      "desc": "star polygon perimeter"
    },
    "rect": {
      "category": "shapes",
      "desc": "rectangle perimeter"
    },
    "rrect": {
      "category": "shapes",
      "desc": "rounded rectangle / superellipse"
    },
    "z01": {
      "category": "arithmetic",
      "desc": "real-part mirror remix"
    },
    "sum_prod": {
      "category": "arithmetic",
      "desc": "emit t1+t2 and t1*t2"
    },
    "roots2": {
      "category": "roots",
      "desc": "quadratic roots of (9/64)z^2+t1*z+t2"
    },
    "roots3": {
      "category": "roots",
      "desc": "cubic roots from t1+t2, 1, 1, t1*t2"
    },
    "roots5": {
      "category": "roots",
      "desc": "cubic roots from trig/i*t parameters"
    },
    "roots6": {
      "category": "roots",
      "desc": "quartic roots from mixed t1/t2 polynomial"
    },
    "sdith": {
      "category": "dither",
      "desc": "square uniform jitter"
    },
    "ddith": {
      "category": "dither",
      "desc": "disk jitter"
    },
    "adth": {
      "category": "dither",
      "desc": "annulus jitter"
    },
    "ldth": {
      "category": "dither",
      "desc": "line-segment jitter"
    },
    "crdth": {
      "category": "dither",
      "desc": "cross-shaped jitter"
    },
    "scdth": {
      "category": "dither",
      "desc": "sector jitter"
    },
    "ndith": {
      "category": "dither",
      "desc": "normal/Gaussian jitter"
    },
    "coeff2": {
      "category": "legacy",
      "desc": "legacy t1+t2 and t1*t2 map"
    },
    "coeff3": {
      "category": "legacy",
      "desc": "legacy 1/(t+2) map"
    },
    "coeff3a": {
      "category": "legacy",
      "desc": "legacy 1/(t+1) map"
    },
    "coeff4": {
      "category": "legacy",
      "desc": "legacy cos(t1), sin(t2)"
    },
    "coeff5": {
      "category": "legacy",
      "desc": "legacy reciprocal cross map"
    },
    "coeff5a": {
      "category": "legacy",
      "desc": "legacy reciprocal self map"
    },
    "coeff6": {
      "category": "legacy",
      "desc": "legacy cubic fractional map"
    },
    "coeff7": {
      "category": "legacy",
      "desc": "legacy trig fractional map"
    },
    "coeff8": {
      "category": "legacy",
      "desc": "legacy cross trig map"
    },
    "coeff9": {
      "category": "legacy",
      "desc": "legacy squared fractional map"
    },
    "coeff10": {
      "category": "legacy",
      "desc": "legacy fourth-power fractional map"
    },
    "coeff11": {
      "category": "legacy",
      "desc": "legacy log fourth-power map"
    },
    "coeff12": {
      "category": "legacy",
      "desc": "legacy mixed polynomial map"
    }
  },
  "fnIndexByName": {
    "none": 1,
    "unit_circle": 2,
    "square": 3,
    "cube": 4,
    "reciprocal": 5,
    "conjugate": 6,
    "negate": 7,
    "exp": 8,
    "xim": 9,
    "add_sub": 10,
    "mul_div": 11,
    "swap": 12,
    "sum_prod": 13,
    "roots2": 14,
    "roots3": 15,
    "roots5": 16,
    "roots6": 17,
    "rtheta": 18,
    "moebius": 19,
    "inv_t_plus_2": 20,
    "crd": 21,
    "hrt": 22,
    "spdl": 23,
    "lmc": 24,
    "rsc": 25,
    "lss": 26,
    "ast": 27,
    "asp": 28,
    "lsp": 29,
    "dlt": 30,
    "rply": 31,
    "star": 32,
    "rect": 33,
    "rrect": 34,
    "z01": 35,
    "coeff2": 36,
    "coeff3": 37,
    "coeff3a": 38,
    "coeff4": 39,
    "coeff5": 40,
    "coeff5a": 41,
    "coeff6": 42,
    "coeff7": 43,
    "coeff8": 44,
    "coeff9": 45,
    "coeff10": 46,
    "coeff11": 47,
    "coeff12": 48,
    "zzold": 49,
    "zz1": 50,
    "zz2": 51,
    "zz3": 52,
    "t1radd": 53,
    "t1iadd": 54,
    "t2radd": 55,
    "t2iadd": 56,
    "radd": 57,
    "iadd": 58,
    "add": 59,
    "cadd": 60,
    "rscale": 61,
    "iscale": 62,
    "scale": 63,
    "sdith": 64,
    "ddith": 65,
    "ndith": 66,
    "adth": 67,
    "ldth": 68,
    "crdth": 69,
    "scdth": 70
  },
  "specs": {
    "none": {
      "name": "none",
      "fn_index": 1,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {}
    },
    "unit_circle": {
      "name": "unit_circle",
      "fn_index": 2,
      "kind": "unary",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "map real t to exp(2*pi*i*t)"
      }
    },
    "square": {
      "name": "square",
      "fn_index": 3,
      "kind": "unary",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "square both complex parameters"
      }
    },
    "cube": {
      "name": "cube",
      "fn_index": 4,
      "kind": "unary",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "cube both complex parameters"
      }
    },
    "reciprocal": {
      "name": "reciprocal",
      "fn_index": 5,
      "kind": "unary",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "replace each parameter with 1/t"
      }
    },
    "conjugate": {
      "name": "conjugate",
      "fn_index": 6,
      "kind": "unary",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "complex conjugate t1 and t2"
      }
    },
    "negate": {
      "name": "negate",
      "fn_index": 7,
      "kind": "unary",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "negate t1 and t2"
      }
    },
    "exp": {
      "name": "exp",
      "fn_index": 8,
      "kind": "unary",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "complex exponential of each parameter"
      }
    },
    "xim": {
      "name": "xim",
      "fn_index": 9,
      "kind": "unary",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "move real part into the imaginary axis"
      }
    },
    "add_sub": {
      "name": "add_sub",
      "fn_index": 10,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "emit t1+t2 and t1-t2"
      }
    },
    "mul_div": {
      "name": "mul_div",
      "fn_index": 11,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "emit t1*t2 and t1/t2"
      }
    },
    "swap": {
      "name": "swap",
      "fn_index": 12,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "swap t1 and t2"
      }
    },
    "sum_prod": {
      "name": "sum_prod",
      "fn_index": 13,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "emit t1+t2 and t1*t2"
      }
    },
    "roots2": {
      "name": "roots2",
      "fn_index": 14,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "roots",
        "desc": "quadratic roots of (9/64)z^2+t1*z+t2"
      }
    },
    "roots3": {
      "name": "roots3",
      "fn_index": 15,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "roots",
        "desc": "cubic roots from t1+t2, 1, 1, t1*t2"
      }
    },
    "roots5": {
      "name": "roots5",
      "fn_index": 16,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "roots",
        "desc": "cubic roots from trig/i*t parameters"
      }
    },
    "roots6": {
      "name": "roots6",
      "fn_index": 17,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "roots",
        "desc": "quartic roots from mixed t1/t2 polynomial"
      }
    },
    "rtheta": {
      "name": "rtheta",
      "fn_index": 18,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "p",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "maps",
        "desc": "polar disk map using t1/t2 as radius and angle"
      }
    },
    "moebius": {
      "name": "moebius",
      "fn_index": 19,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "maps",
        "desc": "Mobius map on t1 and t2; 0-arg runs keep legacy 1/(t+2)"
      }
    },
    "inv_t_plus_2": {
      "name": "inv_t_plus_2",
      "fn_index": 20,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "t1=1/(t1+a), t2=1/(t2+b)"
      }
    },
    "crd": {
      "name": "crd",
      "fn_index": 21,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "size",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "cardioid curve"
      }
    },
    "hrt": {
      "name": "hrt",
      "fn_index": 22,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "size",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "turns",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "heart curve"
      }
    },
    "spdl": {
      "name": "spdl",
      "fn_index": 23,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "va",
          "type": "real",
          "default": 0.5
        },
        {
          "name": "vb",
          "type": "real",
          "default": 0.2
        },
        {
          "name": "vp",
          "type": "real",
          "default": 1.5
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "spindle curve"
      }
    },
    "lmc": {
      "name": "lmc",
      "fn_index": 24,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "a",
          "type": "real",
          "default": 0.3
        },
        {
          "name": "b",
          "type": "real",
          "default": 0.5
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "limacon curve"
      }
    },
    "rsc": {
      "name": "rsc",
      "fn_index": 25,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "amp",
          "type": "real",
          "default": 0.5
        },
        {
          "name": "k",
          "type": "real",
          "default": 2.0
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "rose curve"
      }
    },
    "lss": {
      "name": "lss",
      "fn_index": 26,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "A",
          "type": "real",
          "default": 0.5
        },
        {
          "name": "B",
          "type": "real",
          "default": 0.5
        },
        {
          "name": "a",
          "type": "real",
          "default": 3.0
        },
        {
          "name": "b",
          "type": "real",
          "default": 2.0
        },
        {
          "name": "phase",
          "type": "real",
          "default": 0.5
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "Lissajous curve"
      }
    },
    "ast": {
      "name": "ast",
      "fn_index": 27,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "scale",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "astroid curve"
      }
    },
    "asp": {
      "name": "asp",
      "fn_index": 28,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "a",
          "type": "real",
          "default": 0.0
        },
        {
          "name": "b",
          "type": "real",
          "default": 0.1
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "Archimedean spiral"
      }
    },
    "lsp": {
      "name": "lsp",
      "fn_index": 29,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "a",
          "type": "real",
          "default": 0.1
        },
        {
          "name": "b",
          "type": "real",
          "default": 0.15
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "log spiral"
      }
    },
    "dlt": {
      "name": "dlt",
      "fn_index": 30,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "R",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "deltoid curve"
      }
    },
    "rply": {
      "name": "rply",
      "fn_index": 31,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "sides",
          "type": "real",
          "default": 5.0
        },
        {
          "name": "radius",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "turns",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "regular polygon perimeter"
      }
    },
    "star": {
      "name": "star",
      "fn_index": 32,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "points",
          "type": "real",
          "default": 5.0
        },
        {
          "name": "outer",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "inner_ratio",
          "type": "real",
          "default": 0.5
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "star polygon perimeter"
      }
    },
    "rect": {
      "name": "rect",
      "fn_index": 33,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "w",
          "type": "real",
          "default": 2.0
        },
        {
          "name": "h",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "turns",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "rectangle perimeter"
      }
    },
    "rrect": {
      "name": "rrect",
      "fn_index": 34,
      "kind": "unary_pair",
      "allowed_src": [
        "p1",
        "p2",
        "both",
        "pop1",
        "pop2"
      ],
      "allowed_tgt": [
        "p1",
        "p2",
        "both",
        "push1",
        "push2"
      ],
      "args": [
        {
          "name": "w",
          "type": "real",
          "default": 2.0
        },
        {
          "name": "h",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "m",
          "type": "real",
          "default": 4.0
        }
      ],
      "ui": {
        "category": "shapes",
        "desc": "rounded rectangle / superellipse"
      }
    },
    "z01": {
      "name": "z01",
      "fn_index": 35,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "real-part mirror remix"
      }
    },
    "coeff2": {
      "name": "coeff2",
      "fn_index": 36,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy t1+t2 and t1*t2 map"
      }
    },
    "coeff3": {
      "name": "coeff3",
      "fn_index": 37,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy 1/(t+2) map"
      }
    },
    "coeff3a": {
      "name": "coeff3a",
      "fn_index": 38,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy 1/(t+1) map"
      }
    },
    "coeff4": {
      "name": "coeff4",
      "fn_index": 39,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy cos(t1), sin(t2)"
      }
    },
    "coeff5": {
      "name": "coeff5",
      "fn_index": 40,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy reciprocal cross map"
      }
    },
    "coeff5a": {
      "name": "coeff5a",
      "fn_index": 41,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy reciprocal self map"
      }
    },
    "coeff6": {
      "name": "coeff6",
      "fn_index": 42,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy cubic fractional map"
      }
    },
    "coeff7": {
      "name": "coeff7",
      "fn_index": 43,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy trig fractional map"
      }
    },
    "coeff8": {
      "name": "coeff8",
      "fn_index": 44,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy cross trig map"
      }
    },
    "coeff9": {
      "name": "coeff9",
      "fn_index": 45,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy squared fractional map"
      }
    },
    "coeff10": {
      "name": "coeff10",
      "fn_index": 46,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy fourth-power fractional map"
      }
    },
    "coeff11": {
      "name": "coeff11",
      "fn_index": 47,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy log fourth-power map"
      }
    },
    "coeff12": {
      "name": "coeff12",
      "fn_index": 48,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "legacy",
        "desc": "legacy mixed polynomial map"
      }
    },
    "zzold": {
      "name": "zzold",
      "fn_index": 49,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "legacy t1+i*t2 remix into both slots"
      }
    },
    "zz1": {
      "name": "zz1",
      "fn_index": 50,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "t1+i*t2 and t1*t2+i*(t1+t2)"
      }
    },
    "zz2": {
      "name": "zz2",
      "fn_index": 51,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "t1+i*t2 and t1-i*t2"
      }
    },
    "zz3": {
      "name": "zz3",
      "fn_index": 52,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "cross-imaginary remix of t1 and t2"
      }
    },
    "t1radd": {
      "name": "t1radd",
      "fn_index": 53,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "v",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "add to real part of t1 only"
      }
    },
    "t1iadd": {
      "name": "t1iadd",
      "fn_index": 54,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "v",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "add to imaginary part of t1 only"
      }
    },
    "t2radd": {
      "name": "t2radd",
      "fn_index": 55,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "v",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "add to real part of t2 only"
      }
    },
    "t2iadd": {
      "name": "t2iadd",
      "fn_index": 56,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "v",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "add to imaginary part of t2 only"
      }
    },
    "radd": {
      "name": "radd",
      "fn_index": 57,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "v",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "add to real parts of both parameters"
      }
    },
    "iadd": {
      "name": "iadd",
      "fn_index": 58,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "v",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "add to imaginary parts of both parameters"
      }
    },
    "add": {
      "name": "add",
      "fn_index": 59,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [],
      "ui": {
        "category": "arithmetic",
        "desc": "z1=z1+c1 and z2=z2+c2 using complex offsets"
      }
    },
    "cadd": {
      "name": "cadd",
      "fn_index": 60,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "re",
          "type": "real",
          "default": 0.0
        },
        {
          "name": "im",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "add a complex constant to t1 and t2"
      }
    },
    "rscale": {
      "name": "rscale",
      "fn_index": 61,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "v",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "scale real parts only"
      }
    },
    "iscale": {
      "name": "iscale",
      "fn_index": 62,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "v",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "scale imaginary parts only"
      }
    },
    "scale": {
      "name": "scale",
      "fn_index": 63,
      "kind": "pair",
      "allowed_src": [
        "both",
        "pop2"
      ],
      "allowed_tgt": [
        "both",
        "push2"
      ],
      "args": [
        {
          "name": "v",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "arithmetic",
        "desc": "scale all components"
      }
    },
    "sdith": {
      "name": "sdith",
      "fn_index": 64,
      "kind": "pair",
      "allowed_src": [
        "both"
      ],
      "allowed_tgt": [
        "both"
      ],
      "args": [
        {
          "name": "d",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "dither",
        "desc": "square uniform jitter"
      }
    },
    "ddith": {
      "name": "ddith",
      "fn_index": 65,
      "kind": "pair",
      "allowed_src": [
        "both"
      ],
      "allowed_tgt": [
        "both"
      ],
      "args": [
        {
          "name": "target",
          "type": "real",
          "default": 2.0
        },
        {
          "name": "d",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "exp",
          "type": "real",
          "default": 0.5
        }
      ],
      "ui": {
        "category": "dither",
        "desc": "disk jitter"
      }
    },
    "ndith": {
      "name": "ndith",
      "fn_index": 66,
      "kind": "pair",
      "allowed_src": [
        "both"
      ],
      "allowed_tgt": [
        "both"
      ],
      "args": [
        {
          "name": "d",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "dither",
        "desc": "normal/Gaussian jitter"
      }
    },
    "adth": {
      "name": "adth",
      "fn_index": 67,
      "kind": "pair",
      "allowed_src": [
        "both"
      ],
      "allowed_tgt": [
        "both"
      ],
      "args": [
        {
          "name": "target",
          "type": "real",
          "default": 2.0
        },
        {
          "name": "d",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "inner",
          "type": "real",
          "default": 0.4
        }
      ],
      "ui": {
        "category": "dither",
        "desc": "annulus jitter"
      }
    },
    "ldth": {
      "name": "ldth",
      "fn_index": 68,
      "kind": "pair",
      "allowed_src": [
        "both"
      ],
      "allowed_tgt": [
        "both"
      ],
      "args": [
        {
          "name": "target",
          "type": "real",
          "default": 2.0
        },
        {
          "name": "d",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "len",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "angle",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "dither",
        "desc": "line-segment jitter"
      }
    },
    "crdth": {
      "name": "crdth",
      "fn_index": 69,
      "kind": "pair",
      "allowed_src": [
        "both"
      ],
      "allowed_tgt": [
        "both"
      ],
      "args": [
        {
          "name": "target",
          "type": "real",
          "default": 2.0
        },
        {
          "name": "d",
          "type": "real",
          "default": 1.0
        }
      ],
      "ui": {
        "category": "dither",
        "desc": "cross-shaped jitter"
      }
    },
    "scdth": {
      "name": "scdth",
      "fn_index": 70,
      "kind": "pair",
      "allowed_src": [
        "both"
      ],
      "allowed_tgt": [
        "both"
      ],
      "args": [
        {
          "name": "target",
          "type": "real",
          "default": 2.0
        },
        {
          "name": "d",
          "type": "real",
          "default": 1.0
        },
        {
          "name": "half_ap",
          "type": "real",
          "default": 0.25
        },
        {
          "name": "center",
          "type": "real",
          "default": 0.0
        }
      ],
      "ui": {
        "category": "dither",
        "desc": "sector jitter"
      }
    }
  },
  "argSpecs": {
    "rtheta": [
      {
        "ph": "p",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "moebius": [
      {
        "ph": "a",
        "def": "1",
        "scalarExpr": true,
        "title": "Complex coefficient a.",
        "complexWide": true
      },
      {
        "ph": "b",
        "def": "0",
        "scalarExpr": true,
        "title": "Complex coefficient b.",
        "complexWide": true
      },
      {
        "ph": "c",
        "def": "0",
        "scalarExpr": true,
        "title": "Complex coefficient c.",
        "complexWide": true
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Complex coefficient d.",
        "complexWide": true
      }
    ],
    "inv_t_plus_2": [
      {
        "ph": "z1",
        "def": "2",
        "scalarExpr": true,
        "title": "Complex expression for the first offset.",
        "complexWide": true
      },
      {
        "ph": "z2",
        "def": "2",
        "scalarExpr": true,
        "title": "Complex expression for the second offset.",
        "complexWide": true
      }
    ],
    "crd": [
      {
        "ph": "size",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "hrt": [
      {
        "ph": "size",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "turns",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "spdl": [
      {
        "ph": "va",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "vb",
        "def": "0.2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "vp",
        "def": "1.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "lmc": [
      {
        "ph": "a",
        "def": "0.3",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "b",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rsc": [
      {
        "ph": "amp",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "k",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "lss": [
      {
        "ph": "A",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "B",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "a",
        "def": "3",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "b",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "phase",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "ast": [
      {
        "ph": "scale",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "asp": [
      {
        "ph": "a",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "b",
        "def": "0.1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "lsp": [
      {
        "ph": "a",
        "def": "0.1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "b",
        "def": "0.15",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "dlt": [
      {
        "ph": "R",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rply": [
      {
        "ph": "sides",
        "def": "5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "radius",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "turns",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "star": [
      {
        "ph": "points",
        "def": "5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "outer",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "inner_ratio",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rect": [
      {
        "ph": "w",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "h",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "turns",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rrect": [
      {
        "ph": "w",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "h",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "m",
        "def": "4",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "t1radd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "t1iadd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "t2radd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "t2iadd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "radd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "iadd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "cadd": [
      {
        "ph": "re",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "im",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rscale": [
      {
        "ph": "v",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "iscale": [
      {
        "ph": "v",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "scale": [
      {
        "ph": "v",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "sdith": [
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "ddith": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "exp",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "ndith": [
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "adth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "inner",
        "def": "0.4",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "ldth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "len",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "angle",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "crdth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "scdth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "half_ap",
        "def": "0.25",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "center",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ]
  },
  "targetArgIndexes": {
    "rtheta": 1,
    "crd": 0,
    "hrt": 0,
    "spdl": 0,
    "lmc": 0,
    "rsc": 0,
    "lss": 0,
    "ast": 0,
    "asp": 0,
    "lsp": 0,
    "dlt": 0,
    "rply": 0,
    "star": 0,
    "rect": 0,
    "rrect": 0
  },
  "variableArgCounts": {
    "moebius": [
      0,
      4,
      8
    ],
    "inv_t_plus_2": [
      0,
      1,
      2,
      3,
      4
    ],
    "add": [
      0,
      1,
      2
    ]
  },
  "targetFirst": [
    "asp",
    "ast",
    "crd",
    "dlt",
    "hrt",
    "lmc",
    "lsp",
    "lss",
    "rect",
    "rply",
    "rrect",
    "rsc",
    "spdl",
    "star"
  ],
  "targetLast": [
    "rtheta"
  ],
  "ditherTargetFirst": [
    "adth",
    "crdth",
    "ddith",
    "ldth",
    "scdth"
  ],
  "independentTargets": [
    "conjugate",
    "cube",
    "exp",
    "negate",
    "reciprocal",
    "square",
    "unit_circle",
    "xim"
  ],
  "programProfiles": {
    "version": 1,
    "profiles": {
      "param": {
        "program_kind": "param_program",
        "value_caps": {
          "program_tokens": 64,
          "total_stack": 16,
          "vector_len": 0,
          "vector_capable_stack": 0,
          "max_args": 8,
          "scalar_exprs": 64,
          "expr_tokens": 32,
          "lowered_expr_tokens": 32
        },
        "symbols": {
          "t1": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr",
              "selector"
            ]
          },
          "t2": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr",
              "selector"
            ]
          },
          "p1": {
            "type": "scalar_complex",
            "access": "read_write",
            "role": "output",
            "initial": "t1",
            "contexts": [
              "expr",
              "lhs",
              "selector"
            ]
          },
          "p2": {
            "type": "scalar_complex",
            "access": "read_write",
            "role": "output",
            "initial": "t2",
            "contexts": [
              "expr",
              "lhs",
              "selector"
            ]
          }
        },
        "selectors": {
          "legacy_src": [
            "p1",
            "p2",
            "both",
            "pop1",
            "pop2"
          ],
          "legacy_tgt": [
            "p1",
            "p2",
            "both",
            "push1",
            "push2"
          ],
          "push": [
            "t1",
            "t2"
          ],
          "emit": [
            "p1",
            "p2"
          ]
        },
        "selector_aliases": {
          "push": {
            "0": "t1",
            "1": "t2"
          },
          "emit": {
            "0": "p1",
            "1": "p2"
          }
        },
        "source": {
          "stack_op_aliases": {
            "dup": "duplicate",
            "duplicate": "duplicate",
            "swap": "swap",
            "pop": "pop",
            "flush": "flush"
          },
          "binary_ops": [
            "add",
            "subtract",
            "sub",
            "mul",
            "ratio",
            "div"
          ],
          "unary_ops": [
            "negate",
            "conj",
            "conjugate",
            "reciprocal",
            "unit_circle",
            "square",
            "cube",
            "exp"
          ],
          "targetable_unary": [
            "negate",
            "conj",
            "conjugate",
            "reciprocal",
            "unit_circle",
            "square",
            "cube",
            "exp"
          ],
          "unary_targets": [
            "p1",
            "p2"
          ],
          "push_sources": [
            "t1",
            "t2"
          ],
          "emit_aliases": {
            "emit_p1": "p1",
            "emit_p2": "p2"
          },
          "expression_namespace": {
            "constants": [
              "pi",
              "pi2",
              "pi2i"
            ],
            "functions": [
              "exp",
              "real",
              "imag",
              "abs",
              "mod"
            ]
          },
          "rejected_forms": [
            {
              "form": "push(both)",
              "code": "bad_selector",
              "use": "push(t1) or push(t2)"
            },
            {
              "form": "emit(p1)",
              "code": "noncanonical_emit",
              "use": "emit_p1, emit_p2, or p1 = expr"
            }
          ]
        },
        "outputs": [
          "p1",
          "p2"
        ],
        "output_contract": {
          "kind": "scalar_registers",
          "default_initialization": true
        }
      },
      "coeff": {
        "program_kind": "coeff_program",
        "value_caps": {
          "program_tokens": 256,
          "total_stack": 64,
          "vector_len": 256,
          "vector_capable_stack": 64,
          "max_args": 8,
          "scalar_exprs": 64,
          "expr_tokens": 32,
          "legacy_int_arg": 4096
        },
        "symbols": {
          "t1": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr"
            ]
          },
          "t2": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr"
            ]
          },
          "p1": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr"
            ]
          },
          "p2": {
            "type": "scalar_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr"
            ]
          },
          "cf": {
            "type": "vector_complex",
            "access": "read",
            "role": "input",
            "contexts": [
              "expr_index_base",
              "selector",
              "rhs"
            ]
          },
          "poly": {
            "type": "vector_complex",
            "access": "read_write",
            "role": "output",
            "initial": "cf",
            "contexts": [
              "expr_index_base",
              "selector",
              "lhs",
              "rhs"
            ]
          },
          "poly_len": {
            "type": "int",
            "access": "read",
            "role": "derived",
            "from": "poly.length",
            "contexts": [
              "expr",
              "length_arg"
            ]
          },
          "tos": {
            "type": "stack_pseudo",
            "access": "read",
            "role": "stack_top",
            "contexts": [
              "expr_index_base",
              "rhs"
            ]
          }
        },
        "selectors": {
          "src": [
            "cf",
            "poly",
            "pop",
            "peek"
          ],
          "tgt": [
            "poly",
            "push"
          ],
          "push_src": [
            "cf",
            "poly"
          ],
          "set_tgt": [
            "poly"
          ],
          "vector_src": [
            "poly",
            "pop",
            "peek"
          ],
          "typed_vector_src": [
            "cf",
            "poly",
            "pop",
            "peek",
            "tos"
          ]
        },
        "outputs": [
          "poly"
        ],
        "output_contract": {
          "kind": "fixed_vector",
          "initial": "cf",
          "fixed_output_length": true
        }
      },
      "root": {
        "program_kind": "root_program",
        "value_caps": {
          "program_tokens": 64,
          "total_stack": 0,
          "vector_len": 256,
          "vector_capable_stack": 0
        },
        "source": {
          "registry": "root_legacy_registry.json",
          "args": "finite_real_static"
        },
        "symbols": {
          "roots": {
            "type": "vector_float",
            "access": "read_write",
            "role": "input_output",
            "contexts": [
              "lhs",
              "rhs"
            ]
          }
        },
        "selectors": {},
        "outputs": [
          "roots"
        ],
        "output_contract": {
          "kind": "in_place_vector",
          "length_preserving": true,
          "nan_policy": "poison"
        }
      },
      "solve_score": {
        "program_kind": "solve_score_program",
        "value_caps": {
          "program_tokens": 32,
          "total_stack": 64,
          "vector_len": 0,
          "vector_capable_stack": 0,
          "max_metric_slots": 16,
          "max_output_channels": 8
        },
        "source": {
          "locals": {
            "type": "scalar_score",
            "access": "read_write"
          },
          "reserved_output": "score",
          "metric_sources": [
            "slv",
            "cf",
            "pm"
          ],
          "output_calls": [
            "emit",
            "emit_norm",
            "emit_none"
          ],
          "metric_kwargs": {
            "q": "percent",
            "lag": [
              0,
              1
            ]
          }
        },
        "symbols": {
          "metrics": {
            "type": "metric_slot",
            "access": "read",
            "role": "metric",
            "namespace": {
              "prefix": "m",
              "count": 16,
              "lag_depths": [
                0,
                1
              ]
            },
            "contexts": [
              "expr",
              "rhs"
            ]
          }
        },
        "selectors": {},
        "outputs": [
          "score"
        ],
        "output_contract": {
          "kind": "terminal_scalar_or_emit_channels",
          "default_terminal_stack": true
        }
      }
    }
  }
};
