// AUTO-GENERATED by lambda/gen_param_vocab.py from lambda Param Program metadata; do not edit
// Legacy Param transform names, argument display specs, and bridge compatibility metadata.
window._paramRegistryVocab = {
  "names": [
    "none",
    "unit_circle",
    "square",
    "cube",
    "reciprocal",
    "conjugate",
    "negate",
    "exp",
    "xim",
    "add_sub",
    "mul_div",
    "swap",
    "sum_prod",
    "roots2",
    "roots3",
    "roots5",
    "roots6",
    "rtheta",
    "moebius",
    "inv_t_plus_2",
    "crd",
    "hrt",
    "spdl",
    "lmc",
    "rsc",
    "lss",
    "ast",
    "asp",
    "lsp",
    "dlt",
    "rply",
    "star",
    "rect",
    "rrect",
    "z01",
    "coeff2",
    "coeff3",
    "coeff3a",
    "coeff4",
    "coeff5",
    "coeff5a",
    "coeff6",
    "coeff7",
    "coeff8",
    "coeff9",
    "coeff10",
    "coeff11",
    "coeff12",
    "zzold",
    "zz1",
    "zz2",
    "zz3",
    "t1radd",
    "t1iadd",
    "t2radd",
    "t2iadd",
    "radd",
    "iadd",
    "add",
    "cadd",
    "rscale",
    "iscale",
    "scale",
    "sdith",
    "ddith",
    "ndith",
    "adth",
    "ldth",
    "crdth",
    "scdth"
  ],
  "categoryMeta": {
    "maps": {
      "title": "Maps",
      "help": "direct complex maps applied to t1/t2"
    },
    "arithmetic": {
      "title": "Arithmetic",
      "help": "offset, scale, invert, or remix parameter values"
    },
    "shapes": {
      "title": "Curves + shapes",
      "help": "replace selected parameters with points on analytic curves"
    },
    "roots": {
      "title": "Root-derived",
      "help": "derive t1/t2 from roots of small polynomials"
    },
    "dither": {
      "title": "Dither",
      "help": "jitter parameters before coefficient generation"
    },
    "legacy": {
      "title": "Legacy coefficient maps",
      "help": "older named parameter recipes kept for compatibility"
    }
  },
  "uiFunctions": {
    "unit_circle": {
      "category": "maps",
      "desc": "map z to exp(2*pi*i*z)",
      "effect": "f(z) = exp(2*pi*i*z). For z = a + i*b: f(z) = exp(-2*pi*b) * (cos(2*pi*a) + i*sin(2*pi*a)).",
      "notes": [
        "For normal real grid inputs x, this is x -> cos(2*pi*x) + i*sin(2*pi*x), mapping [0,1] around the unit circle.",
        "If the input has an imaginary part, it changes the radius: positive imaginary shrinks by exp(-2*pi*b), negative imaginary expands.",
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "rtheta": {
      "category": "maps",
      "desc": "polar disk map using paired real parts as radius and angle",
      "effect": "For inputs z1,z2, let x=Re(z1), y=Re(z2). out1 = x^p * (cos(2*pi*y) + i*sin(2*pi*y)); out2 = y^p * (cos(2*pi*x) + i*sin(2*pi*x)).",
      "notes": [
        "The imaginary parts of both inputs are ignored.",
        "p defaults to 1 and is applied as a power to the radius coordinate.",
        "In Param Program source, use legacy(rtheta, src, tgt, p). The old raw target selector argument is represented by src/tgt.",
        "src=both applies the paired map to p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs."
      ]
    },
    "square": {
      "category": "maps",
      "desc": "square both complex parameters"
    },
    "cube": {
      "category": "maps",
      "desc": "cube both complex parameters"
    },
    "reciprocal": {
      "category": "maps",
      "desc": "replace each parameter with 1/t"
    },
    "conjugate": {
      "category": "maps",
      "desc": "complex conjugate t1 and t2"
    },
    "swap": {
      "category": "maps",
      "desc": "swap t1 and t2"
    },
    "add_sub": {
      "category": "arithmetic",
      "desc": "emit t1+t2 and t1-t2"
    },
    "mul_div": {
      "category": "arithmetic",
      "desc": "emit t1*t2 and t1/t2"
    },
    "moebius": {
      "category": "maps",
      "desc": "Mobius map on t1 and t2; 0-arg runs keep legacy 1/(t+2)"
    },
    "negate": {
      "category": "maps",
      "desc": "negate t1 and t2"
    },
    "exp": {
      "category": "maps",
      "desc": "complex exponential of each parameter",
      "effect": "f(z) = exp(z). For z = a + i*b: f(z) = exp(a) * (cos(b) + i*sin(b)).",
      "notes": [
        "This is the ordinary complex exponential, not unit_circle; angles are in radians, not turns.",
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "xim": {
      "category": "maps",
      "desc": "move real part into the imaginary axis",
      "effect": "f(z) = i*Re(z). For z = a + i*b: f(z) = 0 + i*a.",
      "notes": [
        "The original imaginary part is discarded.",
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1 pops one stack value and applies f.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1 pushes the first output."
      ]
    },
    "zzold": {
      "category": "arithmetic",
      "desc": "legacy t1+i*t2 remix into both slots"
    },
    "zz1": {
      "category": "arithmetic",
      "desc": "t1+i*t2 and t1*t2+i*(t1+t2)"
    },
    "zz2": {
      "category": "arithmetic",
      "desc": "t1+i*t2 and t1-i*t2"
    },
    "zz3": {
      "category": "arithmetic",
      "desc": "cross-imaginary remix of t1 and t2"
    },
    "inv_t_plus_2": {
      "category": "arithmetic",
      "desc": "t1=1/(t1+a), t2=1/(t2+b)"
    },
    "t1radd": {
      "category": "arithmetic",
      "desc": "add to real part of t1 only"
    },
    "t1iadd": {
      "category": "arithmetic",
      "desc": "add to imaginary part of t1 only"
    },
    "t2radd": {
      "category": "arithmetic",
      "desc": "add to real part of t2 only"
    },
    "t2iadd": {
      "category": "arithmetic",
      "desc": "add to imaginary part of t2 only"
    },
    "radd": {
      "category": "arithmetic",
      "desc": "add to real parts of both parameters"
    },
    "iadd": {
      "category": "arithmetic",
      "desc": "add to imaginary parts of both parameters"
    },
    "add": {
      "category": "arithmetic",
      "desc": "z1=z1+c1 and z2=z2+c2 using complex offsets"
    },
    "cadd": {
      "category": "arithmetic",
      "desc": "add a complex constant to t1 and t2"
    },
    "rscale": {
      "category": "arithmetic",
      "desc": "scale real parts only"
    },
    "iscale": {
      "category": "arithmetic",
      "desc": "scale imaginary parts only"
    },
    "scale": {
      "category": "arithmetic",
      "desc": "scale all components"
    },
    "crd": {
      "category": "shapes",
      "desc": "cardioid curve",
      "effect": "theta = 2*pi*Re(z); r = size * (1 + cos(theta)); f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the cardioid angle.",
        "size defaults to 1. The maximum radius is 2*size at theta=0, and the cusp is at theta=pi.",
        "In Param Program source, use legacy(crd, src, tgt, size). The old raw n selector is represented by src/tgt; size is the only explicit transform argument.",
        "src=p1 applies f to p1; src=p2 applies f to p2; src=both applies f to p1 and p2; src=pop1/pop2 read one/two stack values.",
        "tgt=both writes both outputs to p1,p2; tgt=p1 or tgt=p2 writes the first output to that register; tgt=push1/push2 push one/two outputs."
      ]
    },
    "hrt": {
      "category": "shapes",
      "desc": "heart curve",
      "effect": "t = 2*pi*Re(z) + pi/2; base = (16*sin(t)^3)/40 + i*((13*cos(t)-5*cos(2*t)-2*cos(3*t)-cos(4*t))/40 + 0.1); f(z) = size * exp(2*pi*i*turns) * base.",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the curve parameter.",
        "size defaults to 1 and scales the heart. turns defaults to 0 and rotates the result by full turns.",
        "In Param Program source, use legacy(hrt, src, tgt, size, turns). The old raw n selector is represented by src/tgt."
      ]
    },
    "spdl": {
      "category": "shapes",
      "desc": "spindle / superellipse-like curve",
      "effect": "theta = 2*pi*Re(z); e = 2/max(vp, 0.01); f(z) = va*sign(cos(theta))*abs(cos(theta))^e + i*vb*sign(sin(theta))*abs(sin(theta))^e.",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the curve angle.",
        "va and vb scale the horizontal and vertical axes. vp controls the superellipse exponent through e=2/max(vp,0.01).",
        "In Param Program source, use legacy(spdl, src, tgt, va, vb, vp). The old raw n selector is represented by src/tgt."
      ]
    },
    "lmc": {
      "category": "shapes",
      "desc": "limacon curve",
      "effect": "theta = 2*pi*Re(z); r = a + b*cos(theta); f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the polar angle.",
        "a sets the base radius; b sets the cosine modulation.",
        "In Param Program source, use legacy(lmc, src, tgt, a, b). The old raw n selector is represented by src/tgt."
      ]
    },
    "rsc": {
      "category": "shapes",
      "desc": "rose curve",
      "effect": "theta = 2*pi*Re(z); r = amp*cos(k*theta); f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the polar angle.",
        "amp scales the radius; k controls the rose frequency/petal structure.",
        "In Param Program source, use legacy(rsc, src, tgt, amp, k). The old raw n selector is represented by src/tgt."
      ]
    },
    "lss": {
      "category": "shapes",
      "desc": "Lissajous curve",
      "effect": "theta = 2*pi*Re(z); delta = pi*phase; f(z) = A*sin(a*theta + delta) + i*B*sin(b*theta).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the time parameter.",
        "A/B scale x/y; a/b are the x/y frequencies; phase is measured in half-turns because delta=pi*phase.",
        "In Param Program source, use legacy(lss, src, tgt, A, B, a, b, phase). The old raw n selector is represented by src/tgt."
      ]
    },
    "ast": {
      "category": "shapes",
      "desc": "astroid curve",
      "effect": "theta = 2*pi*Re(z); f(z) = scale*cos(theta)^3 + i*scale*sin(theta)^3.",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the curve angle.",
        "scale defaults to 1 and scales both axes.",
        "In Param Program source, use legacy(ast, src, tgt, scale). The old raw n selector is represented by src/tgt."
      ]
    },
    "asp": {
      "category": "shapes",
      "desc": "Archimedean spiral",
      "effect": "theta = 2*pi*Re(z); r = a + b*theta; f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the spiral angle.",
        "a is the starting radius; b is the radial growth per radian.",
        "In Param Program source, use legacy(asp, src, tgt, a, b). The old raw n selector is represented by src/tgt."
      ]
    },
    "lsp": {
      "category": "shapes",
      "desc": "logarithmic spiral",
      "effect": "theta = 2*pi*Re(z); r = a*exp(b*theta); f(z) = r * (cos(theta) + i*sin(theta)).",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the spiral angle.",
        "a sets the initial radius; b sets exponential radial growth.",
        "In Param Program source, use legacy(lsp, src, tgt, a, b). The old raw n selector is represented by src/tgt."
      ]
    },
    "dlt": {
      "category": "shapes",
      "desc": "deltoid curve",
      "effect": "theta = 2*pi*Re(z); f(z) = R*(2*cos(theta)+cos(2*theta))/3 + i*R*(2*sin(theta)-sin(2*theta))/3.",
      "notes": [
        "The imaginary part of the input is ignored; Re(z) is used as the curve angle.",
        "R defaults to 1 and scales the deltoid.",
        "In Param Program source, use legacy(dlt, src, tgt, R). The old raw n selector is represented by src/tgt."
      ]
    },
    "rply": {
      "category": "shapes",
      "desc": "regular polygon perimeter",
      "effect": "t = fract(Re(z)); ns = max(int(sides), 3); linearly interpolate along the ns regular-polygon edges at radius, then rotate by exp(2*pi*i*turns).",
      "notes": [
        "The imaginary part of the input is ignored; fract(Re(z)) chooses distance along the perimeter.",
        "sides is truncated to an integer and clamped to at least 3. turns rotates the polygon by full turns.",
        "In Param Program source, use legacy(rply, src, tgt, sides, radius, turns). The old raw n selector is represented by src/tgt."
      ]
    },
    "star": {
      "category": "shapes",
      "desc": "star polygon perimeter",
      "effect": "t = fract(Re(z)); np = max(int(points), 3); walk 2*np alternating vertices with radii outer and outer*inner_ratio, linearly interpolating along each edge.",
      "notes": [
        "The imaginary part of the input is ignored; fract(Re(z)) chooses distance along the star perimeter.",
        "points is truncated to an integer and clamped to at least 3. inner_ratio controls the inner radius as a fraction of outer.",
        "In Param Program source, use legacy(star, src, tgt, points, outer, inner_ratio). The old raw n selector is represented by src/tgt."
      ]
    },
    "rect": {
      "category": "shapes",
      "desc": "rectangle perimeter",
      "effect": "t = fract(Re(z)); walk distance t*2*(w+h) around a centered rectangle of width w and height h, then rotate by exp(2*pi*i*turns).",
      "notes": [
        "The imaginary part of the input is ignored; fract(Re(z)) chooses arc-length position around the rectangle perimeter.",
        "The walk starts on the bottom edge from left to right, then right edge, top edge, and left edge. turns rotates the result by full turns.",
        "In Param Program source, use legacy(rect, src, tgt, w, h, turns). The old raw n selector is represented by src/tgt."
      ]
    },
    "rrect": {
      "category": "shapes",
      "desc": "rounded rectangle / superellipse",
      "effect": "theta = 2*pi*fract(Re(z)); e = 2/max(m, 0.01); f(z) = (w/2)*sign(cos(theta))*abs(cos(theta))^e + i*(h/2)*sign(sin(theta))*abs(sin(theta))^e.",
      "notes": [
        "The imaginary part of the input is ignored; fract(Re(z)) is used as the curve parameter.",
        "w and h set the bounding box. m controls the superellipse exponent through e=2/max(m,0.01).",
        "In Param Program source, use legacy(rrect, src, tgt, w, h, m). The old raw n selector is represented by src/tgt."
      ]
    },
    "z01": {
      "category": "arithmetic",
      "desc": "real-part mirror remix",
      "effect": "For inputs z1,z2, let x=Re(z1), y=Re(z2). out1 = x + i*y; out2 = y + i*x.",
      "notes": [
        "The imaginary parts of both inputs are ignored.",
        "This is a pair transform: src=both reads p1,p2; src=pop2 pops two stack values. tgt=both writes p1,p2; tgt=push2 pushes both outputs.",
        "It takes no explicit transform arguments."
      ]
    },
    "sum_prod": {
      "category": "arithmetic",
      "desc": "emit t1+t2 and t1*t2"
    },
    "roots2": {
      "category": "roots",
      "desc": "quadratic roots of (9/64)z^2+t1*z+t2"
    },
    "roots3": {
      "category": "roots",
      "desc": "cubic roots from t1+t2, 1, 1, t1*t2"
    },
    "roots5": {
      "category": "roots",
      "desc": "cubic roots from trig/i*t parameters"
    },
    "roots6": {
      "category": "roots",
      "desc": "quartic roots from mixed t1/t2 polynomial"
    },
    "sdith": {
      "category": "dither",
      "desc": "square uniform jitter"
    },
    "ddith": {
      "category": "dither",
      "desc": "disk jitter"
    },
    "adth": {
      "category": "dither",
      "desc": "annulus jitter"
    },
    "ldth": {
      "category": "dither",
      "desc": "line-segment jitter"
    },
    "crdth": {
      "category": "dither",
      "desc": "cross-shaped jitter"
    },
    "scdth": {
      "category": "dither",
      "desc": "sector jitter"
    },
    "ndith": {
      "category": "dither",
      "desc": "normal/Gaussian jitter"
    },
    "coeff2": {
      "category": "legacy",
      "desc": "legacy t1+t2 and t1*t2 map"
    },
    "coeff3": {
      "category": "legacy",
      "desc": "legacy 1/(t+2) map"
    },
    "coeff3a": {
      "category": "legacy",
      "desc": "legacy 1/(t+1) map"
    },
    "coeff4": {
      "category": "legacy",
      "desc": "legacy cos(t1), sin(t2)"
    },
    "coeff5": {
      "category": "legacy",
      "desc": "legacy reciprocal cross map"
    },
    "coeff5a": {
      "category": "legacy",
      "desc": "legacy reciprocal self map"
    },
    "coeff6": {
      "category": "legacy",
      "desc": "legacy cubic fractional map"
    },
    "coeff7": {
      "category": "legacy",
      "desc": "legacy trig fractional map"
    },
    "coeff8": {
      "category": "legacy",
      "desc": "legacy cross trig map"
    },
    "coeff9": {
      "category": "legacy",
      "desc": "legacy squared fractional map"
    },
    "coeff10": {
      "category": "legacy",
      "desc": "legacy fourth-power fractional map"
    },
    "coeff11": {
      "category": "legacy",
      "desc": "legacy log fourth-power map"
    },
    "coeff12": {
      "category": "legacy",
      "desc": "legacy mixed polynomial map"
    }
  },
  "argSpecs": {
    "rtheta": [
      {
        "ph": "p",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "moebius": [
      {
        "ph": "a",
        "def": "1",
        "scalarExpr": true,
        "title": "Complex coefficient a.",
        "complexWide": true
      },
      {
        "ph": "b",
        "def": "0",
        "scalarExpr": true,
        "title": "Complex coefficient b.",
        "complexWide": true
      },
      {
        "ph": "c",
        "def": "0",
        "scalarExpr": true,
        "title": "Complex coefficient c.",
        "complexWide": true
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "title": "Complex coefficient d.",
        "complexWide": true
      }
    ],
    "inv_t_plus_2": [
      {
        "ph": "z1",
        "def": "2",
        "scalarExpr": true,
        "title": "Complex expression for the first offset.",
        "complexWide": true
      },
      {
        "ph": "z2",
        "def": "2",
        "scalarExpr": true,
        "title": "Complex expression for the second offset.",
        "complexWide": true
      }
    ],
    "crd": [
      {
        "ph": "size",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "hrt": [
      {
        "ph": "size",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "turns",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "spdl": [
      {
        "ph": "va",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "vb",
        "def": "0.2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "vp",
        "def": "1.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "lmc": [
      {
        "ph": "a",
        "def": "0.3",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "b",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rsc": [
      {
        "ph": "amp",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "k",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "lss": [
      {
        "ph": "A",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "B",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "a",
        "def": "3",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "b",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "phase",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "ast": [
      {
        "ph": "scale",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "asp": [
      {
        "ph": "a",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "b",
        "def": "0.1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "lsp": [
      {
        "ph": "a",
        "def": "0.1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "b",
        "def": "0.15",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "dlt": [
      {
        "ph": "R",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rply": [
      {
        "ph": "sides",
        "def": "5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "radius",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "turns",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "star": [
      {
        "ph": "points",
        "def": "5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "outer",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "inner_ratio",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rect": [
      {
        "ph": "w",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "h",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "turns",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rrect": [
      {
        "ph": "w",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "h",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "m",
        "def": "4",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "t1radd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "t1iadd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "t2radd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "t2iadd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "radd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "iadd": [
      {
        "ph": "v",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "cadd": [
      {
        "ph": "re",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "im",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "rscale": [
      {
        "ph": "v",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "iscale": [
      {
        "ph": "v",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "scale": [
      {
        "ph": "v",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "sdith": [
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "ddith": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "exp",
        "def": "0.5",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "ndith": [
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "adth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "inner",
        "def": "0.4",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "ldth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "len",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "angle",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "crdth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ],
    "scdth": [
      {
        "ph": "target",
        "def": "2",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "d",
        "def": "1",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "half_ap",
        "def": "0.25",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      },
      {
        "ph": "center",
        "def": "0",
        "scalarExpr": true,
        "exprWide": true,
        "title": "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. Use real(...), imag(...), abs(...), or mod(...) for complex registers."
      }
    ]
  },
  "targetArgIndexes": {
    "rtheta": 1,
    "crd": 0,
    "hrt": 0,
    "spdl": 0,
    "lmc": 0,
    "rsc": 0,
    "lss": 0,
    "ast": 0,
    "asp": 0,
    "lsp": 0,
    "dlt": 0,
    "rply": 0,
    "star": 0,
    "rect": 0,
    "rrect": 0
  },
  "variableArgCounts": {
    "moebius": [
      0,
      4,
      8
    ],
    "inv_t_plus_2": [
      0,
      1,
      2,
      3,
      4
    ],
    "add": [
      0,
      1,
      2
    ]
  },
  "independentTargets": [
    "conjugate",
    "cube",
    "exp",
    "negate",
    "reciprocal",
    "square",
    "unit_circle",
    "xim"
  ]
};
