// AUTO-GENERATED by lambda/gen_program_profiles.py from lambda/program_profiles.json; do not edit
window._programProfiles = {
  "profiles": {
    "coeff": {
      "output_contract": {
        "fixed_output_length": true,
        "initial": "cf",
        "kind": "fixed_vector"
      },
      "outputs": [
        "poly"
      ],
      "program_kind": "coeff_program",
      "selectors": {
        "push_src": [
          "cf",
          "poly"
        ],
        "set_tgt": [
          "poly"
        ],
        "src": [
          "cf",
          "poly",
          "pop",
          "peek"
        ],
        "tgt": [
          "poly",
          "push"
        ],
        "typed_vector_src": [
          "cf",
          "poly",
          "pop",
          "peek",
          "tos"
        ],
        "vector_src": [
          "poly",
          "pop",
          "peek"
        ]
      },
      "symbols": {
        "cf": {
          "access": "read",
          "contexts": [
            "expr_index_base",
            "selector",
            "rhs"
          ],
          "role": "input",
          "type": "vector_complex"
        },
        "p1": {
          "access": "read",
          "contexts": [
            "expr"
          ],
          "role": "input",
          "type": "scalar_complex"
        },
        "p2": {
          "access": "read",
          "contexts": [
            "expr"
          ],
          "role": "input",
          "type": "scalar_complex"
        },
        "poly": {
          "access": "read_write",
          "contexts": [
            "expr_index_base",
            "selector",
            "lhs",
            "rhs"
          ],
          "initial": "cf",
          "role": "output",
          "type": "vector_complex"
        },
        "poly_len": {
          "access": "read",
          "contexts": [
            "expr",
            "length_arg"
          ],
          "from": "poly.length",
          "role": "derived",
          "type": "int"
        },
        "t1": {
          "access": "read",
          "contexts": [
            "expr"
          ],
          "role": "input",
          "type": "scalar_complex"
        },
        "t2": {
          "access": "read",
          "contexts": [
            "expr"
          ],
          "role": "input",
          "type": "scalar_complex"
        },
        "tos": {
          "access": "read",
          "contexts": [
            "expr_index_base",
            "rhs"
          ],
          "role": "stack_top",
          "type": "stack_pseudo"
        }
      },
      "value_caps": {
        "expr_tokens": 32,
        "legacy_int_arg": 4096,
        "max_args": 8,
        "program_tokens": 256,
        "scalar_exprs": 64,
        "total_stack": 64,
        "vector_capable_stack": 64,
        "vector_len": 256
      }
    },
    "param": {
      "output_contract": {
        "default_initialization": true,
        "kind": "scalar_registers"
      },
      "outputs": [
        "p1",
        "p2"
      ],
      "program_kind": "param_program",
      "selector_aliases": {
        "emit": {
          "0": "p1",
          "1": "p2"
        },
        "push": {
          "0": "t1",
          "1": "t2"
        }
      },
      "selectors": {
        "emit": [
          "p1",
          "p2"
        ],
        "legacy_src": [
          "p1",
          "p2",
          "both",
          "pop1",
          "pop2"
        ],
        "legacy_tgt": [
          "p1",
          "p2",
          "both",
          "push1",
          "push2"
        ],
        "push": [
          "t1",
          "t2"
        ]
      },
      "source": {
        "binary_ops": [
          "add",
          "subtract",
          "sub",
          "mul",
          "ratio",
          "div"
        ],
        "emit_aliases": {
          "emit_p1": "p1",
          "emit_p2": "p2"
        },
        "expression_namespace": {
          "constants": [
            "pi",
            "pi2",
            "pi2i"
          ],
          "functions": [
            "exp",
            "real",
            "imag",
            "abs",
            "mod"
          ]
        },
        "push_sources": [
          "t1",
          "t2"
        ],
        "rejected_forms": [
          {
            "code": "bad_selector",
            "form": "push(both)",
            "use": "push(t1) or push(t2)"
          },
          {
            "code": "noncanonical_emit",
            "form": "emit(p1)",
            "use": "emit_p1, emit_p2, or p1 = expr"
          }
        ],
        "stack_op_aliases": {
          "dup": "duplicate",
          "duplicate": "duplicate",
          "flush": "flush",
          "pop": "pop",
          "swap": "swap"
        },
        "targetable_unary": [
          "negate",
          "conj",
          "conjugate",
          "reciprocal",
          "unit_circle",
          "square",
          "cube",
          "exp"
        ],
        "unary_ops": [
          "negate",
          "conj",
          "conjugate",
          "reciprocal",
          "unit_circle",
          "square",
          "cube",
          "exp"
        ],
        "unary_targets": [
          "p1",
          "p2"
        ]
      },
      "symbols": {
        "p1": {
          "access": "read_write",
          "contexts": [
            "expr",
            "lhs",
            "selector"
          ],
          "initial": "t1",
          "role": "output",
          "type": "scalar_complex"
        },
        "p2": {
          "access": "read_write",
          "contexts": [
            "expr",
            "lhs",
            "selector"
          ],
          "initial": "t2",
          "role": "output",
          "type": "scalar_complex"
        },
        "t1": {
          "access": "read",
          "contexts": [
            "expr",
            "selector"
          ],
          "role": "input",
          "type": "scalar_complex"
        },
        "t2": {
          "access": "read",
          "contexts": [
            "expr",
            "selector"
          ],
          "role": "input",
          "type": "scalar_complex"
        }
      },
      "value_caps": {
        "expr_tokens": 32,
        "lowered_expr_tokens": 32,
        "max_args": 8,
        "program_tokens": 64,
        "scalar_exprs": 64,
        "total_stack": 16,
        "vector_capable_stack": 0,
        "vector_len": 0
      }
    },
    "root": {
      "output_contract": {
        "kind": "in_place_vector",
        "length_preserving": true,
        "nan_policy": "poison"
      },
      "outputs": [
        "roots"
      ],
      "program_kind": "root_program",
      "selectors": {},
      "source": {
        "args": "finite_real_static",
        "registry": "root_legacy_registry.json"
      },
      "symbols": {
        "roots": {
          "access": "read_write",
          "contexts": [
            "lhs",
            "rhs"
          ],
          "role": "input_output",
          "type": "vector_float"
        }
      },
      "value_caps": {
        "program_tokens": 64,
        "total_stack": 0,
        "vector_capable_stack": 0,
        "vector_len": 256
      }
    },
    "solve_score": {
      "output_contract": {
        "default_terminal_stack": true,
        "kind": "terminal_scalar_or_emit_channels"
      },
      "outputs": [
        "score"
      ],
      "program_kind": "solve_score_program",
      "selectors": {},
      "source": {
        "locals": {
          "access": "read_write",
          "type": "scalar_score"
        },
        "metric_kwargs": {
          "lag": [
            0,
            1
          ],
          "q": "percent"
        },
        "metric_sources": [
          "slv",
          "cf",
          "pm"
        ],
        "output_calls": [
          "emit",
          "emit_norm",
          "emit_none"
        ],
        "reserved_output": "score"
      },
      "symbols": {
        "metrics": {
          "access": "read",
          "contexts": [
            "expr",
            "rhs"
          ],
          "namespace": {
            "count": 16,
            "lag_depths": [
              0,
              1
            ],
            "prefix": "m"
          },
          "role": "metric",
          "type": "metric_slot"
        }
      },
      "value_caps": {
        "max_metric_slots": 16,
        "max_output_channels": 8,
        "program_tokens": 32,
        "total_stack": 64,
        "vector_capable_stack": 0,
        "vector_len": 0
      }
    }
  },
  "version": 1
};
