// AUTO-GENERATED by lambda/gen_root_vocab.py from lambda Root Program metadata; do not edit
// Root transform names, argument display specs, and descriptions for the text editor.
window._rootRegistryVocab = {
  "names": [
    "rotate_roots",
    "pull_unit_circle",
    "roots_toline",
    "line_to_unit_circle",
    "invert_roots",
    "add_complex",
    "mul_complex",
    "moebius",
    "pull_towards_center"
  ],
  "catalog": {
    "rotate_roots": {
      "desc": "Rotate all roots about the origin by turns full revolutions: z * exp(i*2*pi*turns).",
      "params": [
        {
          "ph": "turns",
          "def": "0",
          "title": "Rotation in full turns (1 = 360 degrees). Finite real number."
        }
      ]
    },
    "pull_unit_circle": {
      "desc": "Pull each root radially toward the unit circle: r' = r - alpha*d*exp(-(d/sigma)^2) with d = r-1. Angles unchanged.",
      "params": [
        {
          "ph": "sigma",
          "def": "0.75",
          "title": "Gaussian width of the pull around |z| = 1. Finite real number."
        },
        {
          "ph": "alpha",
          "def": "1",
          "title": "Pull strength: 1 snaps nearby roots onto the circle, 0 is identity. Finite real number."
        }
      ]
    },
    "roots_toline": {
      "desc": "Cayley transform w = i*(1+z)/(1-z): unit circle maps to the real line, disk interior to the upper half-plane. The pole at z = 1 is clipped.",
      "label": "Cayley"
    },
    "line_to_unit_circle": {
      "desc": "Inverse Cayley transform z = (w-i)/(w+i): real line maps to the unit circle, upper half-plane to the disk. The pole at w = -i is clipped.",
      "label": "inverse Cayley"
    },
    "invert_roots": {
      "desc": "Complex inversion z' = 1/z: swaps the inside and outside of the unit circle. The pole at z = 0 is clipped.",
      "label": "1/z"
    },
    "add_complex": {
      "desc": "Translate every root by the constant re + i*im.",
      "label": "z+(a+ib)",
      "params": [
        {
          "ph": "re",
          "def": "0",
          "title": "Real part of the translation. Finite real number."
        },
        {
          "ph": "im",
          "def": "0",
          "title": "Imaginary part of the translation. Finite real number."
        }
      ]
    },
    "mul_complex": {
      "desc": "Multiply every root by the constant re + i*im (scale and rotate).",
      "label": "z*(a+ib)",
      "params": [
        {
          "ph": "re",
          "def": "1",
          "title": "Real part of the multiplier. Finite real number."
        },
        {
          "ph": "im",
          "def": "0",
          "title": "Imaginary part of the multiplier. Finite real number."
        }
      ]
    },
    "moebius": {
      "desc": "Real-coefficient Moebius transform z' = (a*z + b)/(c*z + d). Roots where c*z + d = 0 are clipped.",
      "params": [
        {
          "ph": "a",
          "def": "1",
          "title": "Numerator z coefficient. Finite real number."
        },
        {
          "ph": "b",
          "def": "0",
          "title": "Numerator constant. Finite real number."
        },
        {
          "ph": "c",
          "def": "0",
          "title": "Denominator z coefficient. Finite real number."
        },
        {
          "ph": "d",
          "def": "1",
          "title": "Denominator constant. Finite real number."
        }
      ]
    },
    "pull_towards_center": {
      "desc": "Gaussian radial shrink toward the origin: r' = r * (1 - alpha*exp(-(r/sigma)^2)). Angles unchanged.",
      "params": [
        {
          "ph": "alpha",
          "def": "1",
          "title": "Shrink strength at the origin: 1 collapses central roots, 0 is identity. Finite real number."
        },
        {
          "ph": "sigma",
          "def": "0.75",
          "title": "Gaussian radius of the shrink region. Finite real number."
        }
      ]
    }
  },
  "maxStatements": 16
};
