// AUTO-GENERATED by lambda/gen_solve_score_vocab.py from solve_score_chain.py — do not edit
// Solve-score metric/source/op vocabulary shared with the frontend.
window._solveScoreVocab = {
  "metricNames": [
    "angular_entropy_16",
    "angular_order_2",
    "angular_order_3",
    "angular_order_4",
    "anisotropy",
    "area",
    "asymmetry_re",
    "centroid_dist",
    "centroid_im",
    "centroid_re",
    "clusteriness",
    "crowding",
    "diagonal_proximity",
    "dist_unit_circle",
    "imag_axis_proximity",
    "inside_unit_fraction",
    "max_im",
    "max_mod",
    "max_re",
    "mean_log_mod",
    "min_angular_separation",
    "min_im",
    "min_mod",
    "min_re",
    "nn_variation",
    "outlierness",
    "proximity",
    "real_axis_proximity",
    "sd_log_mod",
    "sector_max_share_16",
    "shelliness",
    "spread",
    "t1_abs",
    "t1_im",
    "t1_phase",
    "t1_re",
    "t2_abs",
    "t2_im",
    "t2_phase",
    "t2_re",
    "unit_annulus_fraction_01"
  ],
  "paramMetricNames": [
    "t1_abs",
    "t1_im",
    "t1_phase",
    "t1_re",
    "t2_abs",
    "t2_im",
    "t2_phase",
    "t2_re"
  ],
  "paramCapableMetricNames": [
    "max_im",
    "max_mod",
    "max_re",
    "min_im",
    "min_mod",
    "min_re"
  ],
  "allowedSourcesByMetric": {
    "angular_entropy_16": [
      "cf",
      "slv"
    ],
    "angular_order_2": [
      "cf",
      "slv"
    ],
    "angular_order_3": [
      "cf",
      "slv"
    ],
    "angular_order_4": [
      "cf",
      "slv"
    ],
    "anisotropy": [
      "cf",
      "slv"
    ],
    "area": [
      "cf",
      "slv"
    ],
    "asymmetry_re": [
      "cf",
      "slv"
    ],
    "centroid_dist": [
      "cf",
      "slv"
    ],
    "centroid_im": [
      "cf",
      "slv"
    ],
    "centroid_re": [
      "cf",
      "slv"
    ],
    "clusteriness": [
      "cf",
      "slv"
    ],
    "crowding": [
      "cf",
      "slv"
    ],
    "diagonal_proximity": [
      "cf",
      "slv"
    ],
    "dist_unit_circle": [
      "cf",
      "slv"
    ],
    "imag_axis_proximity": [
      "cf",
      "slv"
    ],
    "inside_unit_fraction": [
      "cf",
      "slv"
    ],
    "max_im": [
      "cf",
      "pm",
      "slv"
    ],
    "max_mod": [
      "cf",
      "pm",
      "slv"
    ],
    "max_re": [
      "cf",
      "pm",
      "slv"
    ],
    "mean_log_mod": [
      "cf",
      "slv"
    ],
    "min_angular_separation": [
      "cf",
      "slv"
    ],
    "min_im": [
      "cf",
      "pm",
      "slv"
    ],
    "min_mod": [
      "cf",
      "pm",
      "slv"
    ],
    "min_re": [
      "cf",
      "pm",
      "slv"
    ],
    "nn_variation": [
      "cf",
      "slv"
    ],
    "outlierness": [
      "cf",
      "slv"
    ],
    "proximity": [
      "cf",
      "slv"
    ],
    "real_axis_proximity": [
      "cf",
      "slv"
    ],
    "sd_log_mod": [
      "cf",
      "slv"
    ],
    "sector_max_share_16": [
      "cf",
      "slv"
    ],
    "shelliness": [
      "cf",
      "slv"
    ],
    "spread": [
      "cf",
      "slv"
    ],
    "t1_abs": [
      "pm"
    ],
    "t1_im": [
      "pm"
    ],
    "t1_phase": [
      "pm"
    ],
    "t1_re": [
      "pm"
    ],
    "t2_abs": [
      "pm"
    ],
    "t2_im": [
      "pm"
    ],
    "t2_phase": [
      "pm"
    ],
    "t2_re": [
      "pm"
    ],
    "unit_annulus_fraction_01": [
      "cf",
      "slv"
    ]
  },
  "sourceNames": [
    "cf",
    "pm",
    "slv"
  ],
  "lagDepths": [
    0,
    1
  ],
  "genericMetricPublicName": "metric",
  "genericMetricChipName": "__metric",
  "genericMetricSources": [
    "cf",
    "slv"
  ],
  "genericMetricNames": [
    "angular_entropy_16",
    "angular_order_2",
    "angular_order_3",
    "angular_order_4",
    "anisotropy",
    "area",
    "asymmetry_re",
    "centroid_dist",
    "centroid_im",
    "centroid_re",
    "clusteriness",
    "crowding",
    "diagonal_proximity",
    "dist_unit_circle",
    "imag_axis_proximity",
    "inside_unit_fraction",
    "max_im",
    "max_mod",
    "max_re",
    "mean_log_mod",
    "min_angular_separation",
    "min_im",
    "min_mod",
    "min_re",
    "nn_variation",
    "outlierness",
    "proximity",
    "real_axis_proximity",
    "sd_log_mod",
    "sector_max_share_16",
    "shelliness",
    "spread",
    "unit_annulus_fraction_01"
  ],
  "unarySpecs": {
    "clamp": {
      "arity": 1,
      "params": [],
      "tooltip": "clamp the top stack value to [0,1]"
    },
    "cos": {
      "arity": 1,
      "params": [],
      "tooltip": "raw cos(score), radians"
    },
    "exp": {
      "arity": 1,
      "params": [],
      "tooltip": "raw exp(score); overflow becomes 0"
    },
    "flip": {
      "arity": 1,
      "params": [],
      "tooltip": "unary stack op: 1-score"
    },
    "log": {
      "arity": 1,
      "params": [],
      "tooltip": "natural log; invalid inputs become 0"
    },
    "omega_cosine": {
      "arity": 1,
      "params": [
        {
          "ph": "w",
          "def": "1"
        },
        {
          "ph": "phase",
          "def": "0"
        }
      ],
      "tooltip": "unary stack op: g(u)=0.5*(cos(omega*2*pi*u+phase)+1)"
    },
    "pow": {
      "arity": 1,
      "params": [
        {
          "ph": "pow",
          "def": "2"
        }
      ],
      "tooltip": "raw pow(score, exponent)"
    },
    "sawtooth": {
      "arity": 1,
      "params": [
        {
          "ph": "mult",
          "def": "10"
        }
      ],
      "tooltip": "unary stack op: frac(score*mult)"
    },
    "sin": {
      "arity": 1,
      "params": [],
      "tooltip": "raw sin(score), radians"
    }
  },
  "combineSpecs": {
    "abs_diff": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1"
    },
    "add": {
      "arity": 2,
      "params": [],
      "tooltip": "raw a+b"
    },
    "avg": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1"
    },
    "ema": {
      "arity": 2,
      "params": [
        {
          "ph": "alpha",
          "def": "0.99"
        }
      ],
      "tooltip": "a*alpha + b*(1-alpha), b is top/latest"
    },
    "geometric_mean": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1"
    },
    "max": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1"
    },
    "min": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1"
    },
    "mul": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1"
    },
    "mult": {
      "arity": 2,
      "params": [],
      "tooltip": "raw a*b"
    },
    "ratio": {
      "arity": 2,
      "params": [],
      "tooltip": "raw a/b; zero if denominator is zero"
    },
    "subtract": {
      "arity": 2,
      "params": [],
      "tooltip": "raw a-b; top of stack is b"
    },
    "weighted_sum": {
      "arity": 2,
      "params": [
        {
          "ph": "a",
          "def": "0.5"
        },
        {
          "ph": "b",
          "def": "0.5"
        }
      ],
      "tooltip": "stack 2 -> 1"
    }
  },
  "outputSpecs": {
    "emit": {
      "arity": 1,
      "params": [
        {
          "ph": "mode",
          "def": "norm",
          "choices": [
            "raw",
            "norm",
            "none"
          ]
        }
      ],
      "tooltip": "pop one score; raw/norm emit a byte, none discards it for debugging branches"
    },
    "emit_none": {
      "arity": 1,
      "params": [],
      "tooltip": "legacy alias for emit(none)",
      "legacy_alias": [
        "emit",
        "none"
      ]
    },
    "emit_norm": {
      "arity": 1,
      "params": [],
      "tooltip": "legacy alias for emit(norm)",
      "legacy_alias": [
        "emit",
        "norm"
      ]
    }
  },
  "stackSpecs": {
    "const": {
      "arity": 0,
      "params": [
        {
          "ph": "value",
          "def": "0"
        }
      ],
      "tooltip": "push a finite constant onto the stack",
      "delta": 1
    },
    "dup": {
      "arity": 1,
      "params": [],
      "tooltip": "duplicate the top stack value",
      "delta": 1
    },
    "flush": {
      "arity": 0,
      "params": [],
      "tooltip": "clear the entire score stack",
      "delta": null
    }
  }
};
