// AUTO-GENERATED by lambda/gen_solve_score_vocab.py from solve_score_chain.py — do not edit
// Solve-score metric/source/op vocabulary shared with the frontend.
window._solveScoreVocab = {
  "metricNames": [
    "angular_entropy_16",
    "angular_order_2",
    "angular_order_3",
    "angular_order_4",
    "anisotropy",
    "area",
    "asymmetry_re",
    "centroid_dist",
    "centroid_im",
    "centroid_re",
    "clusteriness",
    "crowding",
    "diagonal_proximity",
    "dist_unit_circle",
    "imag_axis_proximity",
    "inside_unit_fraction",
    "max_im",
    "max_mod",
    "max_re",
    "mean_log_mod",
    "min_angular_separation",
    "min_im",
    "min_mod",
    "min_re",
    "nn_variation",
    "outlierness",
    "proximity",
    "real_axis_proximity",
    "sd_log_mod",
    "sector_max_share_16",
    "shelliness",
    "spread",
    "t1_abs",
    "t1_im",
    "t1_phase",
    "t1_re",
    "t2_abs",
    "t2_im",
    "t2_phase",
    "t2_re",
    "unit_annulus_fraction_01"
  ],
  "paramMetricNames": [
    "t1_abs",
    "t1_im",
    "t1_phase",
    "t1_re",
    "t2_abs",
    "t2_im",
    "t2_phase",
    "t2_re"
  ],
  "paramCapableMetricNames": [
    "max_im",
    "max_mod",
    "max_re",
    "min_im",
    "min_mod",
    "min_re"
  ],
  "allowedSourcesByMetric": {
    "angular_entropy_16": [
      "slv",
      "cf"
    ],
    "angular_order_2": [
      "slv",
      "cf"
    ],
    "angular_order_3": [
      "slv",
      "cf"
    ],
    "angular_order_4": [
      "slv",
      "cf"
    ],
    "anisotropy": [
      "slv",
      "cf"
    ],
    "area": [
      "slv",
      "cf"
    ],
    "asymmetry_re": [
      "slv",
      "cf"
    ],
    "centroid_dist": [
      "slv",
      "cf"
    ],
    "centroid_im": [
      "slv",
      "cf"
    ],
    "centroid_re": [
      "slv",
      "cf"
    ],
    "clusteriness": [
      "slv",
      "cf"
    ],
    "crowding": [
      "slv",
      "cf"
    ],
    "diagonal_proximity": [
      "slv",
      "cf"
    ],
    "dist_unit_circle": [
      "slv",
      "cf"
    ],
    "imag_axis_proximity": [
      "slv",
      "cf"
    ],
    "inside_unit_fraction": [
      "slv",
      "cf"
    ],
    "max_im": [
      "slv",
      "cf",
      "pm"
    ],
    "max_mod": [
      "slv",
      "cf",
      "pm"
    ],
    "max_re": [
      "slv",
      "cf",
      "pm"
    ],
    "mean_log_mod": [
      "slv",
      "cf"
    ],
    "min_angular_separation": [
      "slv",
      "cf"
    ],
    "min_im": [
      "slv",
      "cf",
      "pm"
    ],
    "min_mod": [
      "slv",
      "cf",
      "pm"
    ],
    "min_re": [
      "slv",
      "cf",
      "pm"
    ],
    "nn_variation": [
      "slv",
      "cf"
    ],
    "outlierness": [
      "slv",
      "cf"
    ],
    "proximity": [
      "slv",
      "cf"
    ],
    "real_axis_proximity": [
      "slv",
      "cf"
    ],
    "sd_log_mod": [
      "slv",
      "cf"
    ],
    "sector_max_share_16": [
      "slv",
      "cf"
    ],
    "shelliness": [
      "slv",
      "cf"
    ],
    "spread": [
      "slv",
      "cf"
    ],
    "t1_abs": [
      "pm"
    ],
    "t1_im": [
      "pm"
    ],
    "t1_phase": [
      "pm"
    ],
    "t1_re": [
      "pm"
    ],
    "t2_abs": [
      "pm"
    ],
    "t2_im": [
      "pm"
    ],
    "t2_phase": [
      "pm"
    ],
    "t2_re": [
      "pm"
    ],
    "unit_annulus_fraction_01": [
      "slv",
      "cf"
    ]
  },
  "sourceNames": [
    "slv",
    "cf",
    "pm"
  ],
  "quantilePercentRange": [
    0.1,
    5.0
  ],
  "lagDepths": [
    0,
    1
  ],
  "starterSnippets": [
    {
      "label": "score = proximity",
      "snippet": "score = metric(proximity, slv, q=0.1%)"
    },
    {
      "label": "emit_norm proximity",
      "snippet": "emit_norm(metric(proximity, slv, q=0.1%))"
    },
    {
      "label": "two channels",
      "snippet": "emit_norm(metric(proximity, slv, q=0.1%))\nemit_norm(metric(spread, slv, q=0.1%))"
    }
  ],
  "metricSnippets": {
    "angular_entropy_16": "score = metric(angular_entropy_16, slv, q=0.1%)",
    "angular_order_2": "score = metric(angular_order_2, slv, q=0.1%)",
    "angular_order_3": "score = metric(angular_order_3, slv, q=0.1%)",
    "angular_order_4": "score = metric(angular_order_4, slv, q=0.1%)",
    "anisotropy": "score = metric(anisotropy, slv, q=0.1%)",
    "area": "score = metric(area, slv, q=0.1%)",
    "asymmetry_re": "score = metric(asymmetry_re, slv, q=0.1%)",
    "centroid_dist": "score = metric(centroid_dist, slv, q=0.1%)",
    "centroid_im": "score = metric(centroid_im, slv, q=0.1%)",
    "centroid_re": "score = metric(centroid_re, slv, q=0.1%)",
    "clusteriness": "score = metric(clusteriness, slv, q=0.1%)",
    "crowding": "score = metric(crowding, slv, q=0.1%)",
    "diagonal_proximity": "score = metric(diagonal_proximity, slv, q=0.1%)",
    "dist_unit_circle": "score = metric(dist_unit_circle, slv, q=0.1%)",
    "imag_axis_proximity": "score = metric(imag_axis_proximity, slv, q=0.1%)",
    "inside_unit_fraction": "score = metric(inside_unit_fraction, slv, q=0.1%)",
    "max_im": "score = metric(max_im, slv, q=0.1%)",
    "max_mod": "score = metric(max_mod, slv, q=0.1%)",
    "max_re": "score = metric(max_re, slv, q=0.1%)",
    "mean_log_mod": "score = metric(mean_log_mod, slv, q=0.1%)",
    "min_angular_separation": "score = metric(min_angular_separation, slv, q=0.1%)",
    "min_im": "score = metric(min_im, slv, q=0.1%)",
    "min_mod": "score = metric(min_mod, slv, q=0.1%)",
    "min_re": "score = metric(min_re, slv, q=0.1%)",
    "nn_variation": "score = metric(nn_variation, slv, q=0.1%)",
    "outlierness": "score = metric(outlierness, slv, q=0.1%)",
    "proximity": "score = metric(proximity, slv, q=0.1%)",
    "real_axis_proximity": "score = metric(real_axis_proximity, slv, q=0.1%)",
    "sd_log_mod": "score = metric(sd_log_mod, slv, q=0.1%)",
    "sector_max_share_16": "score = metric(sector_max_share_16, slv, q=0.1%)",
    "shelliness": "score = metric(shelliness, slv, q=0.1%)",
    "spread": "score = metric(spread, slv, q=0.1%)",
    "t1_abs": "score = metric(t1_abs, pm, q=0.1%)",
    "t1_im": "score = metric(t1_im, pm, q=0.1%)",
    "t1_phase": "score = metric(t1_phase, pm, q=0.1%)",
    "t1_re": "score = metric(t1_re, pm, q=0.1%)",
    "t2_abs": "score = metric(t2_abs, pm, q=0.1%)",
    "t2_im": "score = metric(t2_im, pm, q=0.1%)",
    "t2_phase": "score = metric(t2_phase, pm, q=0.1%)",
    "t2_re": "score = metric(t2_re, pm, q=0.1%)",
    "unit_annulus_fraction_01": "score = metric(unit_annulus_fraction_01, slv, q=0.1%)"
  },
  "genericMetricPublicName": "metric",
  "genericMetricChipName": "__metric",
  "genericMetricSources": [
    "slv",
    "cf"
  ],
  "genericMetricNames": [
    "angular_entropy_16",
    "angular_order_2",
    "angular_order_3",
    "angular_order_4",
    "anisotropy",
    "area",
    "asymmetry_re",
    "centroid_dist",
    "centroid_im",
    "centroid_re",
    "clusteriness",
    "crowding",
    "diagonal_proximity",
    "dist_unit_circle",
    "imag_axis_proximity",
    "inside_unit_fraction",
    "max_im",
    "max_mod",
    "max_re",
    "mean_log_mod",
    "min_angular_separation",
    "min_im",
    "min_mod",
    "min_re",
    "nn_variation",
    "outlierness",
    "proximity",
    "real_axis_proximity",
    "sd_log_mod",
    "sector_max_share_16",
    "shelliness",
    "spread",
    "unit_annulus_fraction_01"
  ],
  "unarySpecs": {
    "clamp": {
      "arity": 1,
      "params": [],
      "tooltip": "clamp the top stack value to [0,1]",
      "snippet": "score = clamp(metric(proximity, slv, q=0.1%))"
    },
    "cos": {
      "arity": 1,
      "params": [],
      "tooltip": "raw cos(score), radians",
      "snippet": "score = cos(metric(proximity, slv, q=0.1%))"
    },
    "exp": {
      "arity": 1,
      "params": [],
      "tooltip": "raw exp(score); overflow becomes 0",
      "snippet": "score = exp(metric(proximity, slv, q=0.1%))"
    },
    "flip": {
      "arity": 1,
      "params": [],
      "tooltip": "unary stack op: 1-score",
      "snippet": "score = flip(metric(proximity, slv, q=0.1%))"
    },
    "log": {
      "arity": 1,
      "params": [],
      "tooltip": "natural log; invalid inputs become 0",
      "snippet": "score = log(metric(proximity, slv, q=0.1%))"
    },
    "omega_cosine": {
      "arity": 1,
      "params": [
        {
          "ph": "w",
          "def": "1"
        },
        {
          "ph": "phase",
          "def": "0"
        }
      ],
      "tooltip": "unary stack op: g(u)=0.5*(cos(omega*2*pi*u+phase)+1)",
      "snippet": "score = omega_cosine(metric(proximity, slv, q=0.1%), 1, 0)"
    },
    "pow": {
      "arity": 1,
      "params": [
        {
          "ph": "pow",
          "def": "2"
        }
      ],
      "tooltip": "raw pow(score, exponent)",
      "snippet": "score = pow(metric(proximity, slv, q=0.1%), 2)"
    },
    "sawtooth": {
      "arity": 1,
      "params": [
        {
          "ph": "mult",
          "def": "10"
        }
      ],
      "tooltip": "unary stack op: frac(score*mult)",
      "snippet": "score = sawtooth(metric(proximity, slv, q=0.1%), 10)"
    },
    "sin": {
      "arity": 1,
      "params": [],
      "tooltip": "raw sin(score), radians",
      "snippet": "score = sin(metric(proximity, slv, q=0.1%))"
    }
  },
  "combineSpecs": {
    "abs_diff": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1",
      "snippet": "score = abs_diff(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "add": {
      "arity": 2,
      "params": [],
      "tooltip": "raw a+b",
      "snippet": "score = add(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "avg": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1",
      "snippet": "score = avg(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "ema": {
      "arity": 2,
      "params": [
        {
          "ph": "alpha",
          "def": "0.99"
        }
      ],
      "tooltip": "a*alpha + b*(1-alpha), b is top/latest",
      "snippet": "score = ema(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%), 0.99)"
    },
    "geometric_mean": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1",
      "snippet": "score = geometric_mean(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "max": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1",
      "snippet": "score = max(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "min": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1",
      "snippet": "score = min(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "mul": {
      "arity": 2,
      "params": [],
      "tooltip": "stack 2 -> 1",
      "snippet": "score = mul(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "mult": {
      "arity": 2,
      "params": [],
      "tooltip": "raw a*b",
      "snippet": "score = mult(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "ratio": {
      "arity": 2,
      "params": [],
      "tooltip": "raw a/b; zero if denominator is zero",
      "snippet": "score = ratio(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "subtract": {
      "arity": 2,
      "params": [],
      "tooltip": "raw a-b; top of stack is b",
      "snippet": "score = subtract(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%))"
    },
    "weighted_sum": {
      "arity": 2,
      "params": [
        {
          "ph": "a",
          "def": "0.5"
        },
        {
          "ph": "b",
          "def": "0.5"
        }
      ],
      "tooltip": "stack 2 -> 1",
      "snippet": "score = weighted_sum(metric(proximity, slv, q=0.1%), metric(spread, slv, q=0.1%), 0.5, 0.5)"
    }
  },
  "outputSpecs": {
    "emit": {
      "arity": 1,
      "params": [
        {
          "ph": "mode",
          "def": "norm",
          "choices": [
            "raw",
            "norm",
            "none"
          ]
        }
      ],
      "tooltip": "pop one score; raw/norm emit a byte, none discards it for debugging branches",
      "snippet": "emit(metric(proximity, slv, q=0.1%))"
    },
    "emit_none": {
      "arity": 1,
      "params": [],
      "tooltip": "legacy alias for emit(none)",
      "snippet": "emit_none(metric(proximity, slv, q=0.1%))\nemit_norm(metric(proximity, slv, q=0.1%))",
      "legacy_alias": [
        "emit",
        "none"
      ]
    },
    "emit_norm": {
      "arity": 1,
      "params": [],
      "tooltip": "legacy alias for emit(norm)",
      "snippet": "emit_norm(metric(proximity, slv, q=0.1%))",
      "legacy_alias": [
        "emit",
        "norm"
      ]
    }
  },
  "stackSpecs": {
    "const": {
      "arity": 0,
      "params": [
        {
          "ph": "value",
          "def": "0"
        }
      ],
      "tooltip": "push a finite constant onto the stack",
      "snippet": "score = add(metric(proximity, slv, q=0.1%), const(0))",
      "delta": 1
    },
    "dup": {
      "arity": 1,
      "params": [],
      "tooltip": "duplicate the top stack value",
      "snippet": "push(metric(proximity, slv, q=0.1%))\ndup()\nflush()\nscore = metric(proximity, slv, q=0.1%)",
      "delta": 1
    },
    "flush": {
      "arity": 0,
      "params": [],
      "tooltip": "clear the entire score stack",
      "snippet": "push(metric(proximity, slv, q=0.1%))\nflush()\nscore = metric(proximity, slv, q=0.1%)",
      "delta": null
    }
  }
};
