#!/usr/bin/env python3
"""
Generate coefficient function artifacts from the single source catalog.

coeff_func_catalog.json is the single source of truth for which
coefficient functions exist, their C symbols, kind, parameters, etc.

This generator produces:
  1. coeff_func_lookup.h  — C lookup function + CoeffFuncSpec table
     (replaces the hand-maintained lookupCoeffFuncC in sweep_cli.c)
  2. coeff_func_catalog_js.js — JS catalog for frontend dropdown
     (degree is probed from the sweep binary)

The C header is consumed at compile time. The JS is consumed at runtime.
Both are derived from the same catalog JSON.

Reads:  coeff_func_catalog.json  — source catalog
        coeff_func_metrics.json  — overlay (agreement %)
        sweep_test binary        — probes actual degree for JS

Writes: coeff_func_lookup.h      — C generated lookup + spec
        ../coeff_func_catalog_js.js — JS catalog for frontend

Usage:  cd lambda && python3 gen_catalog.py
"""
import json
import os
import subprocess
import sys

LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
SWEEP = os.environ.get("SWEEP_BIN", os.path.join(LAMBDA_DIR, "sweep_test"))
CATALOG_PATH = os.path.join(LAMBDA_DIR, "coeff_func_catalog.json")
METRICS_PATH = os.path.join(LAMBDA_DIR, "coeff_func_metrics.json")
JS_OUT = os.path.join(LAMBDA_DIR, "..", "coeff_func_catalog_js.js")
H_OUT = os.path.join(LAMBDA_DIR, "coeff_func_lookup.h")


def probe_degree(func_name):
    """Run sweep binary to get actual degree for a function."""
    spec = json.dumps({
        "mode": "coeffgen",
        "function": func_name,
        "n1": 2, "n2": 2,
        "i1_start": 0, "i1_end": 1,
        "param_transforms": [["unit_circle"]],
        "coeff_transforms": [],
        "times": 1,
    })
    try:
        r = subprocess.run(
            [SWEEP, "/tmp/_cat_probe.bin"],
            input=spec, capture_output=True, text=True, timeout=10,
        )
        if r.returncode == 0:
            meta = json.loads(r.stdout)
            return meta["n_coeffs"] - 1
    except Exception:
        pass
    return None


def load_catalog():
    with open(CATALOG_PATH) as f:
        return json.load(f)


def load_metrics():
    if os.path.exists(METRICS_PATH):
        with open(METRICS_PATH) as f:
            return json.load(f)
    return {}


def generate_c_header(catalog):
    """Generate C lookup header from catalog."""
    lines = [
        "/* AUTO-GENERATED by gen_catalog.py from coeff_func_catalog.json */",
        "/* Do not edit — regenerate with: python3 gen_catalog.py */",
        "",
        "typedef struct {",
        "    const char *name;",
        "    CoeffFuncC func;",
        "    int n_params;",
        "    const double *defaults;",
        "} CoeffFuncSpec;",
        "",
    ]

    # Emit default arrays for parametric functions
    for entry in catalog:
        params = entry.get("params", [])
        if params:
            defaults = ", ".join(str(float(p["default"])) for p in params)
            lines.append(f"static const double _cfpv_defaults_{entry['name']}[] = {{{defaults}}};")
    lines.append("")

    # Emit lookupCoeffFuncC
    lines.append("static CoeffFuncC lookupCoeffFuncC(const char *name) {")
    for entry in catalog:
        lines.append(f'    if (strcmp(name, "{entry["name"]}") == 0) return {entry["c_symbol"]};')
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")

    # Emit lookupCoeffFuncSpec
    lines.append("static const CoeffFuncSpec _coeffFuncSpecs[] = {")
    for entry in catalog:
        params = entry.get("params", [])
        n_params = len(params)
        defaults_ref = f"_cfpv_defaults_{entry['name']}" if params else "NULL"
        lines.append(f'    {{"{entry["name"]}", {entry["c_symbol"]}, {n_params}, {defaults_ref}}},')
    lines.append("};")
    lines.append(f"static const int _nCoeffFuncSpecs = {len(catalog)};")
    lines.append("")
    lines.append("static const CoeffFuncSpec *lookupCoeffFuncSpec(const char *name) {")
    lines.append("    for (int i = 0; i < _nCoeffFuncSpecs; i++) {")
    lines.append('        if (strcmp(name, _coeffFuncSpecs[i].name) == 0) return &_coeffFuncSpecs[i];')
    lines.append("    }")
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def generate_js(catalog, metrics):
    """Generate JS catalog with probed degrees."""
    entries = []
    probe_failures = []
    for entry in catalog:
        name = entry["name"]
        met = metrics.get(name, {})
        degree = probe_degree(name)
        if degree is None:
            print(f"  WARNING: {name} probe failed, included with degree=0", file=sys.stderr)
            probe_failures.append(name)
            degree = 0

        js_entry = {
            "name": name,
            "kind": entry["kind"],
            "source": entry.get("source", ""),
            "degree": degree,
            "params": entry.get("params", []),
        }
        if degree == 0 and name in probe_failures:
            js_entry["probe_failed"] = True
        if "agreement_pct" in met:
            js_entry["agreement_pct"] = met["agreement_pct"]

        entries.append(js_entry)

    if probe_failures:
        print(f"  {len(probe_failures)} probe failures (included with degree=0): {', '.join(probe_failures)}", file=sys.stderr)

    js = f"// AUTO-GENERATED by gen_catalog.py — do not edit\n"
    js += f"// {len(entries)} coefficient functions\n"
    js += f"window._coeffFuncCatalog = {json.dumps(entries, indent=2)};\n"
    return js


def main():
    if not os.path.exists(SWEEP):
        print(f"ERROR: {SWEEP} not found. Build first.", file=sys.stderr)
        sys.exit(1)

    catalog = load_catalog()
    metrics = load_metrics()
    print(f"Catalog: {len(catalog)} functions")
    print(f"Metrics: {len(metrics)} entries")
    print(f"Sweep binary: {SWEEP}")

    # Generate C header
    h_code = generate_c_header(catalog)
    with open(H_OUT, "w") as f:
        f.write(h_code)
    print(f"Wrote {H_OUT}")

    # Generate JS catalog
    print("Probing degrees...")
    js = generate_js(catalog, metrics)
    with open(JS_OUT, "w") as f:
        f.write(js)
    print(f"Wrote {JS_OUT}")

    import re
    count = len(re.findall(r'"name":', js))
    print(f"JS catalog: {count} functions")


if __name__ == "__main__":
    main()
