#!/usr/bin/env python3
"""Generate coeff_vocab_js.js from lambda program metadata.

coeff_legacy_registry.json remains the source of truth for registry-transform
vocabulary. structural_chips.json and program_profiles.json are Phase-1
metadata: browser/frontend and drift-test inputs only, not runtime execution
configuration. The generated JS mirror lets the frontend consume the same
metadata without hand-copying it.

Usage:
    gen_coeff_vocab.py            write coeff_vocab_js.js at the repo root
    gen_coeff_vocab.py --check    exit 1 if the file on disk is stale
"""
import os
import sys

import coeff_program_chain as chain
from registry_common import (
    check_generated_file,
    default_text,
    extract_category_meta,
    load_json,
    registry_functions,
    render_js_assignment,
    require_function_ui_desc,
    require_registry_version,
)

LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
REGISTRY_PATH = os.path.join(LAMBDA_DIR, "coeff_legacy_registry.json")
STRUCTURAL_CHIPS_PATH = os.path.join(LAMBDA_DIR, "structural_chips.json")
PROGRAM_PROFILES_PATH = os.path.join(LAMBDA_DIR, "program_profiles.json")
JS_OUT = os.path.join(LAMBDA_DIR, "..", "coeff_vocab_js.js")

SCALAR_EXPR_HELP_PLACEHOLDER = "{SCALAR_EXPR_HELP}"


def build_structural_chips():
    return load_json(STRUCTURAL_CHIPS_PATH)


def build_program_profiles():
    return load_json(PROGRAM_PROFILES_PATH)


def _arg_default_text(arg):
    return default_text(arg.get("default", ""))


def _ui_param_from_arg(arg):
    ui = dict(arg.get("ui") or {})
    if ui:
        return ui
    name = str(arg.get("name") or "").strip()
    arg_type = str(arg.get("type") or "real").strip().lower()
    return {
        "ph": name,
        "label": name,
        "def": _arg_default_text(arg),
        "scalarExpr": "complex" if arg_type == "complex" else "real",
        "title": f"{name} parameter. {SCALAR_EXPR_HELP_PLACEHOLDER}",
    }


def build_vocab():
    payload = load_json(REGISTRY_PATH)
    require_registry_version(payload, "coeff")
    functions = registry_functions(payload)
    registry = chain.legacy_registry()
    ct_catalog = {}
    program_param_defs = {}
    for fn in functions:
        name = fn["name"]
        loaded = registry["by_name"][name]
        ui = require_function_ui_desc(fn, "registry")
        entry = {"category": fn["category"], "desc": ui["desc"]}
        if ui.get("label"):
            entry["label"] = ui["label"]
        params = list(ui.get("params") or [])
        params.extend(_ui_param_from_arg(arg) for arg in (loaded.get("optional_args") or ()))
        if params:
            entry["params"] = params
        ct_catalog[name] = entry
        if ui.get("program_params"):
            program_params = list(ui["program_params"])
            program_params.extend(_ui_param_from_arg(arg) for arg in (loaded.get("optional_args") or ()))
            program_param_defs[name] = program_params
    alias_to_canonical = {}
    source_alias_by_name = {}
    chip_name_by_registry_name = {}
    for fn in functions:
        name = fn["name"]
        for alias in list(fn.get("aliases") or []) + list(fn.get("chain_only_aliases") or []):
            alias_to_canonical[alias] = name
        for alias in list(fn.get("aliases") or [])[:1]:
            source_alias_by_name[name] = alias
        if fn.get("chip_name") and fn["chip_name"] != name:
            chip_name_by_registry_name[name] = fn["chip_name"]
    # Emit only fields the frontend consumes. names/fnIndexByName/
    # effectiveArgs/compatSignatures were shipped for a while with zero JS
    # readers — false-authority payload; the loader spec (Python) and the
    # registry JSON are the sources for that data.
    return {
        "aliasToCanonical": alias_to_canonical,
        "sourceAliasByName": source_alias_by_name,
        "chipNameByRegistryName": chip_name_by_registry_name,
        "ctCatalog": ct_catalog,
        "categoryMeta": extract_category_meta(payload, paths=(("category_meta",),), label="coeff"),
        "programParamDefs": program_param_defs,
        "structuralChips": build_structural_chips(),
        "programProfiles": build_program_profiles(),
    }


def render_js():
    vocab = build_vocab()
    # Insertion order is meaningful and ends up in the UI: ctCatalog keys
    # drive the transform picker (fn_index order) and categoryMeta drives
    # category order (registry order). Do not sort.
    return render_js_assignment(
        "window._coeffRegistryVocab",
        vocab,
        header=(
            "// AUTO-GENERATED by lambda/gen_coeff_vocab.py from lambda program metadata — do not edit\n"
            "// Registry transforms, structural chips, and profile metadata shared with the frontend.\n"
        ),
    )


def main(argv):
    rendered = render_js()
    if "--check" in argv[1:]:
        if not check_generated_file(JS_OUT, rendered, label="coeff_vocab_js.js"):
            return 1
        print("coeff_vocab_js.js: OK")
        return 0
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"Wrote {os.path.normpath(JS_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
