#!/usr/bin/env python3
"""Generate param_vocab_js.js from Param Program registry metadata.

The legacy Param transform registry is authoritative for accepted transform
names and source/target selector legality. This mirror prevents the frontend
from maintaining its own shorter transform list.
"""
from __future__ import annotations

import os
import sys

from registry_common import (
    check_generated_file,
    default_text,
    extract_category_meta,
    load_json,
    normalize_name_int_map,
    normalize_name_int_set_map,
    normalize_name_set,
    registry_functions,
    render_js_assignment,
    require_function_ui_desc,
    require_registry_version,
)


LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.normpath(os.path.join(LAMBDA_DIR, ".."))
REGISTRY_PATH = os.path.join(LAMBDA_DIR, "param_legacy_registry.json")
JS_OUT = os.path.join(ROOT_DIR, "param_vocab_js.js")


SCALAR_EXPR_TITLE = (
    "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. "
    "Use real(...), imag(...), abs(...), or mod(...) for complex registers."
)
COMPLEX_EXPR_TITLE = (
    "Complex expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. "
    "Functions: exp, real, imag, abs, mod."
)


def _arg_spec(arg):
    name = str(arg.get("name") or "arg")
    arg_type = str(arg.get("type") or "real")
    declared_title = str(arg.get("title") or arg.get("help") or "")
    spec = {
        "ph": name,
        "def": default_text(arg.get("default", "")),
        "scalarExpr": True,
    }
    if arg_type == "real":
        spec["exprWide"] = True
        spec["title"] = declared_title or SCALAR_EXPR_TITLE
    elif arg_type == "complex":
        spec["complexWide"] = True
        spec["title"] = declared_title or COMPLEX_EXPR_TITLE
    else:
        spec["title"] = declared_title or f"{arg_type} argument."
    return spec


def _ui_arg_spec(arg):
    arg_type = str(arg.get("type") or "real")
    spec = {
        "ph": str(arg.get("ph") or arg.get("name") or "arg"),
        "def": default_text(arg.get("def", arg.get("default", ""))),
        "scalarExpr": True,
        "title": str(arg.get("title") or ""),
    }
    if arg_type == "complex":
        spec["complexWide"] = True
        if not spec["title"]:
            spec["title"] = COMPLEX_EXPR_TITLE
    else:
        spec["exprWide"] = True
        if not spec["title"]:
            spec["title"] = SCALAR_EXPR_TITLE
    return spec


def _special_arg_specs(name, declared_args):
    return [_arg_spec(arg) for arg in declared_args]


def build_vocab():
    registry = load_json(REGISTRY_PATH)
    require_registry_version(registry, "param")
    compat_raw = registry.get("compat") or {}
    compat = {
        "target_arg_indexes": normalize_name_int_map(compat_raw.get("target_arg_indexes")),
        "independent_targets": normalize_name_set(compat_raw.get("independent_targets")),
        "variable_arg_counts": normalize_name_int_set_map(compat_raw.get("variable_arg_counts")),
    }
    functions = registry_functions(registry)
    names = [str(fn["name"]) for fn in functions]
    arg_specs = {}
    target_arg_indexes = {}
    variable_arg_counts = {}
    independent_targets = sorted(compat["independent_targets"])
    target_arg_index_source = compat["target_arg_indexes"]
    variable_arg_count_source = compat["variable_arg_counts"]
    ui_functions = {}
    for fn in functions:
        name = str(fn["name"])
        local_ui = require_function_ui_desc(fn, "param legacy")
        ui_functions[name] = {
            key: value
            for key, value in local_ui.items()
            if key != "params"
        }
        display_args = [_ui_arg_spec(arg) for arg in (local_ui.get("params") or [])]
        runtime_args = list(fn.get("args") or [])
        if runtime_args and len(display_args) != len(runtime_args):
            raise SystemExit(
                f"param legacy function {name} must define ui.params for all {len(runtime_args)} runtime args"
            )
        if not display_args:
            display_args = _special_arg_specs(name, runtime_args)
        if display_args:
            arg_specs[name] = display_args
        if name in target_arg_index_source:
            target_arg_indexes[name] = int(target_arg_index_source[name])
        if name in variable_arg_count_source:
            variable_arg_counts[name] = sorted(variable_arg_count_source[name])
    return {
        "names": names,
        "categoryMeta": extract_category_meta(registry, paths=(("ui", "categories"),), label="param"),
        "uiFunctions": ui_functions,
        "argSpecs": arg_specs,
        "targetArgIndexes": target_arg_indexes,
        "variableArgCounts": variable_arg_counts,
        "independentTargets": independent_targets,
    }


def render_js():
    return render_js_assignment(
        "window._paramRegistryVocab",
        build_vocab(),
        header=(
            "// AUTO-GENERATED by lambda/gen_param_vocab.py from lambda Param Program metadata; do not edit\n"
            "// Legacy Param transform names, argument display specs, and bridge compatibility metadata.\n"
        ),
    )


def _check(path, text):
    return check_generated_file(path, text, label="param_vocab_js.js")


def main(argv):
    rendered = render_js()
    if "--check" in argv[1:]:
        if _check(JS_OUT, rendered):
            print("param_vocab_js.js: OK")
            return 0
        return 1
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"Wrote {os.path.normpath(JS_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
