#!/usr/bin/env python3
"""Generate program profile mirrors from program_profiles.json.

`program_profiles.json` is the reviewed source of truth. The generated Python
module is what parser code imports at runtime; the generated JS file is what
the browser consumes for selector/profile metadata. Keeping both generated and
byte-checked prevents quiet profile drift across Python/JS/JSON.
"""
from __future__ import annotations

import json
import os
import pprint
import sys


LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.normpath(os.path.join(LAMBDA_DIR, ".."))
PROFILE_JSON = os.path.join(LAMBDA_DIR, "program_profiles.json")
PY_OUT = os.path.join(LAMBDA_DIR, "program_profiles.py")
JS_OUT = os.path.join(ROOT_DIR, "program_profiles_js.js")


def _load_profiles():
    with open(PROFILE_JSON, "r", encoding="utf-8") as fh:
        return json.load(fh)


def render_py():
    payload = _load_profiles()
    body = pprint.pformat(payload, width=100, sort_dicts=True)
    return (
        "# AUTO-GENERATED by lambda/gen_program_profiles.py from program_profiles.json; do not edit\n"
        "PROGRAM_PROFILES = "
        f"{body}\n"
    )


def render_js():
    payload = _load_profiles()
    body = json.dumps(payload, indent=2, sort_keys=True)
    return (
        "// AUTO-GENERATED by lambda/gen_program_profiles.py from lambda/program_profiles.json; do not edit\n"
        f"window._programProfiles = {body};\n"
    )


def _write(path, text):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _check(path, text):
    try:
        with open(path, "r", encoding="utf-8") as fh:
            current = fh.read()
    except FileNotFoundError:
        current = ""
    if current != text:
        sys.stderr.write(f"FATAL: {os.path.basename(path)} is stale; regenerate with lambda/gen_program_profiles.py\n")
        return False
    return True


def main(argv):
    py_text = render_py()
    js_text = render_js()
    if "--check" in argv[1:]:
        ok = _check(PY_OUT, py_text)
        ok = _check(JS_OUT, js_text) and ok
        if ok:
            print("program_profiles.py/js: OK")
            return 0
        return 1
    _write(PY_OUT, py_text)
    _write(JS_OUT, js_text)
    print(f"Wrote {os.path.normpath(PY_OUT)}")
    print(f"Wrote {os.path.normpath(JS_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
