#!/usr/bin/env python3
"""Generate coeff_vocab_js.js from lambda/coeff_legacy_registry.json.

The registry JSON is the single source of truth for registry-transform
vocabulary: canonical names, fn indices, aliases (wire format — saved chip
rows carry them), chip-name shadowing (exp -> exp_affine, power ->
power_series), and andy support. The Python compilers derive their tables
from it at import (coeff_program_chain.legacy_registry); the browser
consumes the same data through the generated file, loaded as a script tag
before the main bundle. This is what retired the CR6/CR7 alias-drift class.

Usage:
    gen_coeff_vocab.py            write coeff_vocab_js.js at the repo root
    gen_coeff_vocab.py --check    exit 1 if the file on disk is stale
"""
import json
import os
import sys

LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
REGISTRY_PATH = os.path.join(LAMBDA_DIR, "coeff_legacy_registry.json")
JS_OUT = os.path.join(LAMBDA_DIR, "..", "coeff_vocab_js.js")


def build_vocab():
    with open(REGISTRY_PATH, "r", encoding="utf-8") as fh:
        payload = json.load(fh)
    functions = sorted(payload["functions"], key=lambda fn: int(fn["fn_index"]))
    names = [fn["name"] for fn in functions]
    alias_to_canonical = {}
    source_alias_by_name = {}
    chip_name_by_registry_name = {}
    supports_andy = {}
    fn_index_by_name = {}
    for fn in functions:
        name = fn["name"]
        fn_index_by_name[name] = int(fn["fn_index"])
        supports_andy[name] = bool(fn.get("supports_andy"))
        for alias in list(fn.get("aliases") or []) + list(fn.get("chain_only_aliases") or []):
            alias_to_canonical[alias] = name
        for alias in list(fn.get("aliases") or [])[:1]:
            source_alias_by_name[name] = alias
        if fn.get("chip_name") and fn["chip_name"] != name:
            chip_name_by_registry_name[name] = fn["chip_name"]
    return {
        "names": names,
        "fnIndexByName": fn_index_by_name,
        "aliasToCanonical": alias_to_canonical,
        "sourceAliasByName": source_alias_by_name,
        "chipNameByRegistryName": chip_name_by_registry_name,
        "supportsAndy": supports_andy,
    }


def render_js():
    vocab = build_vocab()
    body = json.dumps(vocab, indent=2, sort_keys=True)
    return (
        "// AUTO-GENERATED by lambda/gen_coeff_vocab.py from"
        " lambda/coeff_legacy_registry.json — do not edit\n"
        "// Registry-transform vocabulary shared with the Python compilers:\n"
        "// names, fn indices, aliases (wire format), chip-name shadowing,\n"
        "// andy support.\n"
        f"window._coeffRegistryVocab = {body};\n"
    )


def main(argv):
    rendered = render_js()
    if "--check" in argv[1:]:
        try:
            with open(JS_OUT, "r", encoding="utf-8") as fh:
                on_disk = fh.read()
        except FileNotFoundError:
            on_disk = ""
        if on_disk != rendered:
            sys.stderr.write(
                "FATAL: coeff_vocab_js.js is stale; regenerate with"
                " lambda/gen_coeff_vocab.py\n"
            )
            return 1
        print("coeff_vocab_js.js: OK")
        return 0
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"Wrote {os.path.normpath(JS_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
