#!/usr/bin/env python3
"""Generate root_vocab_js.js from the Root Program registry.

root_legacy_registry.json is authoritative for root transform names, args,
defaults, and ui descriptions. This mirror feeds the frontend Root Transforms
text editor (starter snippets, generated Help, dblclick inspector) so the
browser never maintains its own hand-written root catalog.
"""
from __future__ import annotations

import os
import sys

from registry_common import (
    check_generated_file,
    default_text,
    load_json,
    registry_functions,
    render_js_assignment,
    require_function_ui_desc,
    require_registry_version,
)


LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.normpath(os.path.join(LAMBDA_DIR, ".."))
REGISTRY_PATH = os.path.join(LAMBDA_DIR, "root_legacy_registry.json")
PROFILES_PATH = os.path.join(LAMBDA_DIR, "program_profiles.json")
JS_OUT = os.path.join(ROOT_DIR, "root_vocab_js.js")

REAL_ARG_TITLE = "Finite real number (static; no expressions)."


def _param_spec(arg, ui_param):
    ui_param = ui_param or {}
    ph = str(ui_param.get("ph") or arg.get("name") or "arg")
    def_text = default_text(ui_param.get("def", arg.get("default", "")))
    title = ui_param.get("title")
    if title is None:
        title = ui_param.get("help")
    title = str(title or "") or REAL_ARG_TITLE
    return {"ph": ph, "def": def_text, "title": title}


def build_vocab():
    registry = load_json(REGISTRY_PATH)
    require_registry_version(registry, "root")
    profiles = load_json(PROFILES_PATH)
    root_profile = (profiles.get("profiles") or {}).get("root") or {}
    max_statements = int(((root_profile.get("value_caps") or {}).get("program_tokens")) or 0)
    if max_statements <= 0:
        raise SystemExit("root profile value_caps.program_tokens missing; cannot pin maxStatements")
    functions = registry_functions(registry)
    names = []
    catalog = {}
    for fn in functions:
        name = str(fn["name"])
        local_ui = require_function_ui_desc(fn, "root legacy")
        runtime_args = list(fn.get("args") or [])
        ui_params = list(local_ui.get("params") or [])
        if runtime_args and len(ui_params) != len(runtime_args):
            raise SystemExit(
                f"root legacy function {name} must define ui.params for all {len(runtime_args)} runtime args"
            )
        entry = {"desc": str(local_ui.get("desc") or "")}
        if local_ui.get("label"):
            entry["label"] = str(local_ui["label"])
        params = [
            _param_spec(arg, ui_params[idx] if idx < len(ui_params) else None)
            for idx, arg in enumerate(runtime_args)
        ]
        if params:
            entry["params"] = params
        names.append(name)
        catalog[name] = entry
    return {
        "names": names,
        "catalog": catalog,
        "maxStatements": max_statements,
    }


def render_js():
    return render_js_assignment(
        "window._rootRegistryVocab",
        build_vocab(),
        header=(
            "// AUTO-GENERATED by lambda/gen_root_vocab.py from lambda Root Program metadata; do not edit\n"
            "// Root transform names, argument display specs, and descriptions for the text editor.\n"
        ),
    )


def _check(path, text):
    return check_generated_file(path, text, label="root_vocab_js.js")


def main(argv):
    rendered = render_js()
    if "--check" in argv[1:]:
        if _check(JS_OUT, rendered):
            print("root_vocab_js.js: OK")
            return 0
        return 1
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"Wrote {os.path.normpath(JS_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
