#!/usr/bin/env python3
"""Generate param_vocab_js.js from Param Program registry metadata.

The legacy Param transform registry is authoritative for accepted transform
names and source/target selector legality. This mirror prevents the frontend
from maintaining its own shorter transform list.
"""
from __future__ import annotations

import json
import os
import sys

import param_program_chain as chain


LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.normpath(os.path.join(LAMBDA_DIR, ".."))
REGISTRY_PATH = os.path.join(LAMBDA_DIR, "param_legacy_registry.json")
PROGRAM_PROFILES_PATH = os.path.join(LAMBDA_DIR, "program_profiles.json")
JS_OUT = os.path.join(ROOT_DIR, "param_vocab_js.js")


SCALAR_EXPR_TITLE = (
    "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. "
    "Use real(...), imag(...), abs(...), or mod(...) for complex registers."
)
COMPLEX_EXPR_TITLE = (
    "Complex expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. "
    "Functions: exp, real, imag, abs, mod."
)


def _load_json(path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def _fmt_default(value):
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _arg_spec(arg):
    name = str(arg.get("name") or "arg")
    arg_type = str(arg.get("type") or "real")
    spec = {
        "ph": name,
        "def": _fmt_default(arg.get("default", "")),
        "scalarExpr": True,
    }
    if arg_type == "real":
        spec["exprWide"] = True
        spec["title"] = SCALAR_EXPR_TITLE
    elif arg_type == "complex":
        spec["complexWide"] = True
        spec["title"] = COMPLEX_EXPR_TITLE
    else:
        spec["title"] = f"{arg_type} argument."
    return spec


def _special_arg_specs(name, declared_args):
    if name == "moebius":
        return [
            {"ph": "a", "def": "1", "scalarExpr": True, "complexWide": True, "title": COMPLEX_EXPR_TITLE},
            {"ph": "b", "def": "0", "scalarExpr": True, "complexWide": True, "title": COMPLEX_EXPR_TITLE},
            {"ph": "c", "def": "0", "scalarExpr": True, "complexWide": True, "title": COMPLEX_EXPR_TITLE},
            {"ph": "d", "def": "1", "scalarExpr": True, "complexWide": True, "title": COMPLEX_EXPR_TITLE},
        ]
    if name == "inv_t_plus_2":
        return [
            {"ph": "z1", "def": "2", "scalarExpr": True, "complexWide": True, "title": "Complex expression for the first offset."},
            {"ph": "z2", "def": "2", "scalarExpr": True, "complexWide": True, "title": "Complex expression for the second offset."},
        ]
    return [_arg_spec(arg) for arg in declared_args]


def build_vocab():
    registry = _load_json(REGISTRY_PATH)
    profiles = _load_json(PROGRAM_PROFILES_PATH)
    functions = sorted(registry["functions"], key=lambda fn: int(fn["fn_index"]))
    names = [str(fn["name"]) for fn in functions]
    specs = {}
    arg_specs = {}
    target_arg_indexes = {}
    variable_arg_counts = {}
    target_first = sorted(chain._LEGACY_TARGET_FIRST_CHIPS)
    target_last = sorted(chain._LEGACY_TARGET_LAST_CHIPS)
    dither_target_first = sorted(chain._LEGACY_DITHER_TARGET_FIRST_CHIPS)
    independent_targets = sorted(chain._REDUNDANT_LEGACY_TARGET_ARG_NAMES)
    fn_index_by_name = {}
    for fn in functions:
        name = str(fn["name"])
        fn_index_by_name[name] = int(fn["fn_index"])
        specs[name] = {
            "name": name,
            "fn_index": int(fn["fn_index"]),
            "kind": fn.get("kind") or "",
            "allowed_src": list(fn.get("allowed_src") or []),
            "allowed_tgt": list(fn.get("allowed_tgt") or []),
            "args": list(fn.get("args") or []),
        }
        display_args = _special_arg_specs(name, fn.get("args") or [])
        if display_args:
            arg_specs[name] = display_args
        if name in chain._LEGACY_TARGET_ARG_INDEXES:
            target_arg_indexes[name] = int(chain._LEGACY_TARGET_ARG_INDEXES[name])
        if name in chain._VARIABLE_LEGACY_ARG_COUNTS:
            variable_arg_counts[name] = sorted(int(v) for v in chain._VARIABLE_LEGACY_ARG_COUNTS[name])
    return {
        "names": names,
        "fnIndexByName": fn_index_by_name,
        "specs": specs,
        "argSpecs": arg_specs,
        "targetArgIndexes": target_arg_indexes,
        "variableArgCounts": variable_arg_counts,
        "targetFirst": target_first,
        "targetLast": target_last,
        "ditherTargetFirst": dither_target_first,
        "independentTargets": independent_targets,
        "programProfiles": profiles,
    }


def render_js():
    body = json.dumps(build_vocab(), indent=2)
    return (
        "// AUTO-GENERATED by lambda/gen_param_vocab.py from lambda Param Program metadata; do not edit\n"
        "// Legacy Param transform names, argument display specs, and bridge compatibility metadata.\n"
        f"window._paramRegistryVocab = {body};\n"
    )


def _check(path, text):
    try:
        with open(path, "r", encoding="utf-8") as fh:
            current = fh.read()
    except FileNotFoundError:
        current = ""
    if current != text:
        sys.stderr.write(
            "FATAL: param_vocab_js.js is stale; regenerate with lambda/gen_param_vocab.py\n"
        )
        return False
    return True


def main(argv):
    rendered = render_js()
    if "--check" in argv[1:]:
        if _check(JS_OUT, rendered):
            print("param_vocab_js.js: OK")
            return 0
        return 1
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"Wrote {os.path.normpath(JS_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
