#!/usr/bin/env python3
"""Generate merged program opcode mirrors from merged_opcodes.json."""
from __future__ import annotations

import json
import os
import pprint
import sys


LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.normpath(os.path.join(LAMBDA_DIR, ".."))
SOURCE_JSON = os.path.join(LAMBDA_DIR, "merged_opcodes.json")
PY_OUT = os.path.join(LAMBDA_DIR, "merged_opcodes.py")
H_OUT = os.path.join(LAMBDA_DIR, "merged_opcodes.h")
JS_OUT = os.path.join(ROOT_DIR, "merged_opcodes_js.js")


def _load_payload():
    with open(SOURCE_JSON, "r", encoding="utf-8") as fh:
        payload = json.load(fh)
    if int(payload.get("version") or 0) != 1:
        raise RuntimeError("merged opcode registry version must be 1")
    seen_ids = {}
    seen_symbols = set()
    for op in payload.get("opcodes") or []:
        op_id = int(op["id"])
        symbol = str(op["symbol"])
        if op_id in seen_ids:
            raise RuntimeError(f"duplicate merged opcode id {op_id}: {symbol} and {seen_ids[op_id]}")
        if symbol in seen_symbols:
            raise RuntimeError(f"duplicate merged opcode symbol {symbol}")
        seen_ids[op_id] = symbol
        seen_symbols.add(symbol)
    return payload


def render_py():
    payload = _load_payload()
    body = pprint.pformat(payload, width=100, sort_dicts=True)
    constants = []
    for name, value in sorted(payload["registries"].items(), key=lambda kv: kv[1]):
        constants.append(f"MERGED_REGISTRY_{name.upper()} = {int(value)}")
    for op in sorted(payload["opcodes"], key=lambda item: int(item["id"])):
        constants.append(f"{op['symbol']} = {int(op['id'])}")
    return (
        "# AUTO-GENERATED by lambda/gen_merged_opcodes.py from merged_opcodes.json; do not edit\n"
        "MERGED_OPCODE_REGISTRY = "
        f"{body}\n\n"
        + "\n".join(constants)
        + "\n"
    )


def render_h():
    payload = _load_payload()
    lines = [
        "/* AUTO-GENERATED by lambda/gen_merged_opcodes.py from merged_opcodes.json; do not edit */",
        "#ifndef POLYPAINT_MERGED_OPCODES_H",
        "#define POLYPAINT_MERGED_OPCODES_H",
        "",
        "enum MergedProgramRegistry {",
    ]
    registries = sorted(payload["registries"].items(), key=lambda kv: kv[1])
    for idx, (name, value) in enumerate(registries):
        suffix = "," if idx < len(registries) - 1 else ""
        lines.append(f"    MERGED_REGISTRY_{name.upper()} = {int(value)}{suffix}")
    lines.extend(["};", "", "enum MergedProgramOp {"])
    opcodes = sorted(payload["opcodes"], key=lambda item: int(item["id"]))
    for idx, op in enumerate(opcodes):
        suffix = "," if idx < len(opcodes) - 1 else ""
        lines.append(f"    {op['symbol']} = {int(op['id'])}{suffix}")
    lines.extend(["};", "", "#endif /* POLYPAINT_MERGED_OPCODES_H */", ""])
    return "\n".join(lines)


def render_js():
    payload = _load_payload()
    body = json.dumps(payload, indent=2, sort_keys=True)
    return (
        "// AUTO-GENERATED by lambda/gen_merged_opcodes.py from lambda/merged_opcodes.json; do not edit\n"
        f"window._mergedOpcodeRegistry = {body};\n"
    )


def _write(path, text):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _check(path, text):
    try:
        with open(path, "r", encoding="utf-8") as fh:
            current = fh.read()
    except FileNotFoundError:
        current = ""
    if current != text:
        sys.stderr.write(
            f"FATAL: {os.path.basename(path)} is stale; regenerate with lambda/gen_merged_opcodes.py\n"
        )
        return False
    return True


def main(argv):
    py_text = render_py()
    h_text = render_h()
    js_text = render_js()
    if "--check" in argv[1:]:
        ok = _check(PY_OUT, py_text)
        ok = _check(H_OUT, h_text) and ok
        ok = _check(JS_OUT, js_text) and ok
        if ok:
            print("merged_opcodes.py/h/js: OK")
            return 0
        return 1
    _write(PY_OUT, py_text)
    _write(H_OUT, h_text)
    _write(JS_OUT, js_text)
    print(f"Wrote {os.path.normpath(PY_OUT)}")
    print(f"Wrote {os.path.normpath(H_OUT)}")
    print(f"Wrote {os.path.normpath(JS_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
