#!/usr/bin/env python3
"""Generate coeff_vocab_js.js from lambda program metadata.

coeff_legacy_registry.json remains the source of truth for registry-transform
vocabulary. structural_chips.json and program_profiles.json are Phase-1
metadata: browser/frontend and drift-test inputs only, not runtime execution
configuration. The generated JS mirror lets the frontend consume the same
metadata without hand-copying it.

Usage:
    gen_coeff_vocab.py            write coeff_vocab_js.js at the repo root
    gen_coeff_vocab.py --check    exit 1 if the file on disk is stale
"""
import json
import os
import sys

LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
REGISTRY_PATH = os.path.join(LAMBDA_DIR, "coeff_legacy_registry.json")
STRUCTURAL_CHIPS_PATH = os.path.join(LAMBDA_DIR, "structural_chips.json")
PROGRAM_PROFILES_PATH = os.path.join(LAMBDA_DIR, "program_profiles.json")
JS_OUT = os.path.join(LAMBDA_DIR, "..", "coeff_vocab_js.js")


def _load_json(path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def build_structural_chips():
    return _load_json(STRUCTURAL_CHIPS_PATH)


def build_program_profiles():
    return _load_json(PROGRAM_PROFILES_PATH)


def build_vocab():
    payload = _load_json(REGISTRY_PATH)
    functions = sorted(payload["functions"], key=lambda fn: int(fn["fn_index"]))
    ct_catalog = {}
    program_param_defs = {}
    for fn in functions:
        ui = dict(fn.get("ui") or {})
        if not ui.get("desc"):
            raise SystemExit(f"registry function {fn['name']} is missing ui.desc")
        entry = {"category": fn["category"], "desc": ui["desc"]}
        if ui.get("label"):
            entry["label"] = ui["label"]
        if ui.get("params"):
            entry["params"] = ui["params"]
        ct_catalog[fn["name"]] = entry
        if ui.get("program_params"):
            program_param_defs[fn["name"]] = ui["program_params"]
    names = [fn["name"] for fn in functions]
    alias_to_canonical = {}
    source_alias_by_name = {}
    chip_name_by_registry_name = {}
    supports_andy = {}
    fn_index_by_name = {}
    for fn in functions:
        name = fn["name"]
        fn_index_by_name[name] = int(fn["fn_index"])
        supports_andy[name] = bool(fn.get("supports_andy"))
        for alias in list(fn.get("aliases") or []) + list(fn.get("chain_only_aliases") or []):
            alias_to_canonical[alias] = name
        for alias in list(fn.get("aliases") or [])[:1]:
            source_alias_by_name[name] = alias
        if fn.get("chip_name") and fn["chip_name"] != name:
            chip_name_by_registry_name[name] = fn["chip_name"]
    return {
        "names": names,
        "fnIndexByName": fn_index_by_name,
        "aliasToCanonical": alias_to_canonical,
        "sourceAliasByName": source_alias_by_name,
        "chipNameByRegistryName": chip_name_by_registry_name,
        "supportsAndy": supports_andy,
        "ctCatalog": ct_catalog,
        "categoryMeta": payload.get("category_meta") or {},
        "programParamDefs": program_param_defs,
        "structuralChips": build_structural_chips(),
        "programProfiles": build_program_profiles(),
    }


def render_js():
    vocab = build_vocab()
    # Insertion order is meaningful and ends up in the UI: ctCatalog keys
    # drive the transform picker (fn_index order) and categoryMeta drives
    # category order (registry order). Do not sort.
    body = json.dumps(vocab, indent=2)
    return (
        "// AUTO-GENERATED by lambda/gen_coeff_vocab.py from lambda program metadata — do not edit\n"
        "// Registry transforms, structural chips, and profile metadata shared with the frontend.\n"
        f"window._coeffRegistryVocab = {body};\n"
    )


def main(argv):
    rendered = render_js()
    if "--check" in argv[1:]:
        try:
            with open(JS_OUT, "r", encoding="utf-8") as fh:
                on_disk = fh.read()
        except FileNotFoundError:
            on_disk = ""
        if on_disk != rendered:
            sys.stderr.write(
                "FATAL: coeff_vocab_js.js is stale; regenerate with"
                " lambda/gen_coeff_vocab.py\n"
            )
            return 1
        print("coeff_vocab_js.js: OK")
        return 0
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"Wrote {os.path.normpath(JS_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
