#!/usr/bin/env python3
"""Generate param_vocab_js.js from Param Program registry metadata.

The legacy Param transform registry is authoritative for accepted transform
names and source/target selector legality. This mirror prevents the frontend
from maintaining its own shorter transform list.
"""
from __future__ import annotations

import json
import os
import sys

import param_program_chain as chain


LAMBDA_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.normpath(os.path.join(LAMBDA_DIR, ".."))
REGISTRY_PATH = os.path.join(LAMBDA_DIR, "param_legacy_registry.json")
JS_OUT = os.path.join(ROOT_DIR, "param_vocab_js.js")


SCALAR_EXPR_TITLE = (
    "Real expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. "
    "Use real(...), imag(...), abs(...), or mod(...) for complex registers."
)
COMPLEX_EXPR_TITLE = (
    "Complex expression. Registers: t1, t2, p1, p2. Constants: pi, pi2, pi2i. "
    "Functions: exp, real, imag, abs, mod."
)


def _load_json(path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def _fmt_default(value):
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def _arg_spec(arg):
    name = str(arg.get("name") or "arg")
    arg_type = str(arg.get("type") or "real")
    declared_title = str(arg.get("title") or arg.get("help") or "")
    spec = {
        "ph": name,
        "def": _fmt_default(arg.get("default", "")),
        "scalarExpr": True,
    }
    if arg_type == "real":
        spec["exprWide"] = True
        spec["title"] = declared_title or SCALAR_EXPR_TITLE
    elif arg_type == "complex":
        spec["complexWide"] = True
        spec["title"] = declared_title or COMPLEX_EXPR_TITLE
    else:
        spec["title"] = declared_title or f"{arg_type} argument."
    return spec


def _ui_arg_spec(arg):
    arg_type = str(arg.get("type") or "real")
    spec = {
        "ph": str(arg.get("ph") or arg.get("name") or "arg"),
        "def": _fmt_default(arg.get("def", arg.get("default", ""))),
        "scalarExpr": True,
        "title": str(arg.get("title") or ""),
    }
    if arg_type == "complex":
        spec["complexWide"] = True
        if not spec["title"]:
            spec["title"] = COMPLEX_EXPR_TITLE
    else:
        spec["exprWide"] = True
        if not spec["title"]:
            spec["title"] = SCALAR_EXPR_TITLE
    return spec


def _special_arg_specs(name, declared_args):
    return [_arg_spec(arg) for arg in declared_args]


def build_vocab():
    registry = _load_json(REGISTRY_PATH)
    ui = registry.get("ui") or {}
    compat = registry.get("compat") or {}
    functions = sorted(registry["functions"], key=lambda fn: int(fn["fn_index"]))
    names = [str(fn["name"]) for fn in functions]
    arg_specs = {}
    target_arg_indexes = {}
    variable_arg_counts = {}
    independent_targets = sorted(compat.get("independent_targets") or chain._REDUNDANT_LEGACY_TARGET_ARG_NAMES)
    target_arg_index_source = compat.get("target_arg_indexes") or chain._LEGACY_TARGET_ARG_INDEXES
    variable_arg_count_source = compat.get("variable_arg_counts") or chain._VARIABLE_LEGACY_ARG_COUNTS
    ui_functions = {}
    for fn in functions:
        name = str(fn["name"])
        local_ui = dict(fn.get("ui") or {})
        if not local_ui.get("desc"):
            raise SystemExit(f"param legacy function {name} is missing ui.desc")
        ui_functions[name] = {
            key: value
            for key, value in local_ui.items()
            if key != "params"
        }
        display_args = [_ui_arg_spec(arg) for arg in (local_ui.get("params") or [])]
        runtime_args = list(fn.get("args") or [])
        if runtime_args and len(display_args) != len(runtime_args):
            raise SystemExit(
                f"param legacy function {name} must define ui.params for all {len(runtime_args)} runtime args"
            )
        if not display_args:
            display_args = _special_arg_specs(name, runtime_args)
        if display_args:
            arg_specs[name] = display_args
        if name in target_arg_index_source:
            target_arg_indexes[name] = int(target_arg_index_source[name])
        if name in variable_arg_count_source:
            variable_arg_counts[name] = sorted(int(v) for v in variable_arg_count_source[name])
    return {
        "names": names,
        "categoryMeta": ui.get("categories") or {},
        "uiFunctions": ui_functions,
        "argSpecs": arg_specs,
        "targetArgIndexes": target_arg_indexes,
        "variableArgCounts": variable_arg_counts,
        "independentTargets": independent_targets,
    }


def render_js():
    body = json.dumps(build_vocab(), indent=2)
    return (
        "// AUTO-GENERATED by lambda/gen_param_vocab.py from lambda Param Program metadata; do not edit\n"
        "// Legacy Param transform names, argument display specs, and bridge compatibility metadata.\n"
        f"window._paramRegistryVocab = {body};\n"
    )


def _check(path, text):
    try:
        with open(path, "r", encoding="utf-8") as fh:
            current = fh.read()
    except FileNotFoundError:
        current = ""
    if current != text:
        sys.stderr.write(
            "FATAL: param_vocab_js.js is stale; regenerate with lambda/gen_param_vocab.py\n"
        )
        return False
    return True


def main(argv):
    rendered = render_js()
    if "--check" in argv[1:]:
        if _check(JS_OUT, rendered):
            print("param_vocab_js.js: OK")
            return 0
        return 1
    with open(JS_OUT, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"Wrote {os.path.normpath(JS_OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
